### PR TITLE
Fix docs access $this and protected property

### PR DESCRIPTION
**Pull request by howdu**

### CODE REVIEW

**Comment by zepfietje** [comment]
What's the issue here, @howdu?
I believe this should work just fine on an admin page.

**Comment by howdu** [comment]
Yeah standard admin page with Tables\Actions\DeleteAction. I got two errors:
> $this when not in object context.
> Cannot access protected property Filament\Tables\Actions\DeleteAction::$record

**Comment by zepfietje** [comment]
Ah, probably because of the longhand closure.

Thanks!

**Comment by danharrin** [comment]
Don't we need to inject `$record` into the closure?

**Comment by zepfietje** [comment]
> Don't we need to inject `$record` into the closure?

Maybe that's cleaner yeah.

**Comment by danharrin** [comment]
I don't agree with the change at all, this works with DeleteAction used on the Edit page. `$record` is for tables

**Comment by danharrin** [comment]
the longhand closure makes no difference to `$this` scope

**Comment by zepfietje** [comment]
But why is @howdu reporting errors then? 🤔

**Comment by danharrin** [comment]
because he's using `Tables\Actions\DeleteAction` which is meant for tables, not page actions

**Comment by zepfietje** [comment]
> because he's using `Tables\Actions\DeleteAction` which is meant for tables, not page actions

Lol, only see it now. 😅

**Comment by howdu** [comment]
Sorry guys I thought this was a straight forward fix and don't mean to be annoying :)

When I specifically pass Pages DeleteAction: `before(function (\Filament\Pages\Actions\DeleteAction $action)`. [Example Repository](https://github.com/howdu/filament-tester/blob/delete-action/app/Filament/Resources/ProductResource.php#L52) I still get the error that it's the wrong: 
> App\Filament\Resources\ProductResource::App\Filament\Resources\{closure}(): Argument #1 ($action) must be of type Filament\Pages\Actions\DeleteAction, Filament\Tables\Actions\DeleteAction given, called in /filament-tester/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php on line 36

**Comment by zepfietje** [comment]
@howdu, no worries.
Next time, try including some context (the error you ran into) in the PR description, that would make our lives a little easier.

As for your last error, make sure to use the right namespace with `DeleteAction::make()` as well.

**Pull request merged**
