### PR TITLE
Add Support For Multilevel Menu

### PR DESCRIPTION
**Pull request by Nuhel**
Add Support For Multilevel Menu Using Advanced Navigation Menu.

Add below code to any registered service provider boot method for testing.
`
Filament::serving(function () {

    Filament::navigation(function (NavigationBuilder $builder): NavigationBuilder {
        return $builder

            ->items([

                NavigationItem::make('Dashboard')

                    ->url('https://filament.pirsch.io', shouldOpenInNewTab: true)
                    ->icon('heroicon-o-home'),

                "G1" => NavigationGroup::make()
                    ->label('Level One Group')
                    ->icon('heroicon-o-menu')
                    ->items([

                        NavigationItem::make('Products')
                            ->isActiveWhen(fn()=>true)
                            ->url('https://filament.pirsch.io', shouldOpenInNewTab: true)
                            ->icon('heroicon-o-presentation-chart-line'),

                        NavigationGroup::make()
                            ->label('Reports')
                            ->icon('heroicon-o-view-grid')->items([
                                NavigationItem::make('Stock')
                                    ->url('https://filament.pirsch.io', shouldOpenInNewTab: true)
                                    ->icon('heroicon-o-lightning-bolt'),

                                NavigationItem::make('Order Report')
                                    ->url('https://filament.pirsch.io', shouldOpenInNewTab: true)
                                    ->icon('heroicon-o-shopping-bag'),

                                NavigationGroup::make()
                                    ->label('Charts')
                                    ->icon('heroicon-o-presentation-chart-line')->items([
                                        NavigationItem::make('Pie Chart')
                                            ->url('https://filament.pirsch.io', shouldOpenInNewTab: true)
                                            ->icon('heroicon-o-chart-pie'),

                                        NavigationItem::make('Bar Chart')
                                            ->url('https://filament.pirsch.io', shouldOpenInNewTab: true)
                                            ->icon('heroicon-o-chart-bar'),
                                    ]),

                            ]),

                    ]),

            ]);
    });

});
`

### CODE REVIEW

**Comment by Umar-Farooq-Shafi** [comment]
any support for Filament v3?

**Comment by danharrin** [comment]
https://filamentphp.com/docs/3.x/panels/navigation#grouping-navigation-items-under-other-items
https://filamentphp.com/docs/3.x/panels/clusters

**Comment by Umar-Farooq-Shafi** [comment]
I'm adding items inside `PanelProvider`

```
    /**
     * @throws Exception
     */
    public function panel(Panel $panel): Panel
    {
        $suppliers = [];

        if (Schema::hasTable(Supplier::getTableName())) {
            $suppliers = Supplier::all()->pluck('name', 'id');
        }

        $suppliersNavItem = [];

        foreach ($suppliers as $id => $supplier) {
            $suppliersNavItem[] = NavigationItem::make($supplier)
                ->url("/admin/suppliers/$id/line-items")
                ->isActiveWhen(function () use ($id) {
                    $route = Route::current();

                    return $route->uri() === "admin/suppliers/{record}/line-items" && $route->parameter('record') === "$id";
                })
                ->icon('heroicon-o-user')
                ->group('Line Items')
                ->sort($id);
        }

        return $panel
            ...
            ->navigationItems($suppliersNavItem);
    }
```

**Comment by Umar-Farooq-Shafi** [comment]
and want to `Line Items` inside the `Setting` navigation group

**Pull request merged**
