### PR TITLE
bug: changed persisting null to alpine store to empty array.

### PR DESCRIPTION
**Pull request by byt3sage**

### CODE REVIEW

**Comment by NoahNxT** [comment]
We also have this issue...
image

**Comment by byt3sage** [comment]
> We also have this issue...
> 
> image
> 
> 

Clear your view cache! Ours was because we had published all the views.

**Comment by NoahNxT** [comment]
After a couple hours of debugging we've found the issue. For some reason the **collapsedGroups** value was saved in localstorage as null...That's why it was crashing.

**Comment by byt3sage** [comment]
Yeah - ours is because we had published the views in our app so the cache was nackered!

**Pull request closed without merging**
