### PR TITLE
Disable registering certain resources to navigation

### PR DESCRIPTION
**Pull request by sawirricardo**
Currently, the way to disable resources is to add this
```
public static  function registerNavigationItems(): void
    {
        return;
    }
```
ref: https://discord.com/channels/883083792112300104/883085267383226478/918873716782403615

However, as discussed in Discord, ideally we can use static property directly.

### CODE REVIEW

**Comment by danharrin** [comment]
Hey, this looks good. Maybe add this to the Resources docs though, as the Navigation docs should be solely about the actual Navigation API IMO. Thoughts?

**Comment by sawirricardo** [comment]
> Hey, this looks good. Maybe add this to the Resources docs though, as the Navigation docs should be solely about the actual Navigation API IMO. Thoughts?

Agree @danharrin

**Comment by danharrin** [comment]
Thanks! I've just added the same API to custom pages, so moved the docs back to the Navigation section :)

**Comment by sawirricardo** [comment]
🙏🏻

**Pull request merged**
