### PR TITLE
Using Laravel App Call in colors method,

### PR DESCRIPTION
**Pull request by Nuhel**
To be able to place callback function params in any order like everywhere else.

### CODE REVIEW

**Comment by zepfietje** [comment]
The closure passed to the `colors()` method is evaluated using Laravel's `app()->call()`: https://filamentphp.com/docs/2.x/forms/advanced#using-closure-customisation.
I think that should work for your use case, right?

**Comment by danharrin** [comment]
No, @nuhel is right but we cant implement it until v3 as its a breaking change

**Comment by zepfietje** [comment]
Wouldn't it currently be possible to resolve the parameters from the main closure you pass in?

And yeah, thought this was part of the `[3.x] Use $this->evaluate() everywhere` roadmap entry.

**Comment by Nuhel** [comment]
> No, @Nuhel is right but we cant implement it until v3 as its a breaking change

Thank you :) .

**Comment by zepfietje** [comment]
I'll leave this PR closed as we'll need to update it in a few other places as well for v3.

Thanks anyway, @Nuhel!

**Comment by coolsam726** [comment]
I would like to revisit this, and submit a PR to support closures in Panel Colors.

**Comment by zepfietje** [comment]
Feel free to work on that, @coolsam726!

**Pull request closed without merging**
