### PR TITLE
Using Lravel propmts in panel builder commands.

### PR DESCRIPTION
**Pull request by Nuhel**
- [ ] Changes have been thoroughly tested to not break existing functionality.

As Laravel now ships with Laravel Prompts, we can use laravel prompts to take user inputs from terminal. 

This PR will make uses of prompts in panel builder commands.

Screenshot 2023-08-05 at 11 00 38 AM

### CODE REVIEW

**Comment by danharrin** [comment]
Please test your work, as there are syntax errors here in the code.

**Comment by Nuhel** [comment]
> Please test your work, as there are syntax errors here in the code.

I dont know why, but github desktop was not pushing the changes, this is wired. 

Screenshot 2023-08-05 at 11 21 05 AM

**Comment by Nuhel** [comment]
@danharrin Hi,
I am not sure how to pass this test?

Error: Used function Laravel\Prompts\select not found.
Error: Used function Laravel\Prompts\text not found.

**Comment by danharrin** [comment]
It's because prompts doesnt support L9. Livewire is also dropping L9, so we will have to soon too.

Don't worry about it, we will sort it

**Comment by danharrin** [comment]
Thanks

**Pull request merged**
