### PR TITLE
Improve section header

### PR DESCRIPTION
**Pull request by mischasigtermans**
## Description

This pull request improves the header of the Section Blade component.

- [x] Visual changes (if any) are shown using screenshots/recordings of before and after.

## Code style

- [x] `composer cs` command has been run.

## Testing

- [x] Changes have been tested.

## Documentation

- [x] Documentation is up-to-date.

### CODE REVIEW

**Comment by danharrin** [comment]
Please explain each of these changes with reasoning / what didnt work before

**Comment by mischasigtermans** [comment]
Sure thing.

Better alignment for icons when not using a description:
screenshot-001334 (2024-02-28)@2x

Make sure that `headerActions` won't trigger `collapsible`:
screenshot-001335 (2024-02-28)

Beter use of space for mobile:
screenshot-001336 (2024-02-28)@2x

`headerActions` still align left when there is no heading:
screenshot-001337 (2024-02-28)@2x

Compact still works:
screenshot-001338 (2024-02-28)@2x

Aside still works:
screenshot-001339 (2024-02-28)@2x

It also works with the new footer from PR #11457.

**Comment by danharrin** [comment]
Can you take a picture of all those cases again but with collapsible enabled?

**Comment by mischasigtermans** [comment]
Just a heading:
screenshot-001340 (2024-02-29)

With description:
screenshot-001341 (2024-02-29)

Header action collapse trigger fix:
screenshot-001342 (2024-02-29)

Mobile:
screenshot-001345 (2024-02-29)

Works with header end:
screenshot-001346 (2024-02-29)

Keeps aligned to the right on mobile where previously it didn't:
screenshot-001347 (2024-02-29)@2x

Skipped aside. It behaves the same as before, but probably not a combo that will be used.

**Comment by danharrin** [comment]
How about mobile with header actions and collapsible as per the original set of the screenshots?

**Comment by mischasigtermans** [comment]
Works the same as with `headerEnd`. If you want to check the different options, please checkout the PR for yourself as that's probably faster.

**Comment by danharrin** [comment]
I'm asking for that specific example since it is main problematic issue with this component that we need to keep fixing

**Comment by mischasigtermans** [comment]
It's exactly like this, but then headerActions. You can test them on the dev environment I sent you.

image

**Comment by danharrin** [comment]
Zep - for your review. I am not a fan of moving the actions to be inline with the heading and description on mobile, as it would result in squashing when the heading or description is over a certain length, or when there is more than one action or an action with a long label. Personally I think they should be on their own line when on mobile.

I also think there is scope to utilize a container query to decide whether they are inline or not, instead of a responsive breakpoint

**Comment by zepfietje** [comment]
I'm going to hold off on merging this.
As @danharrin explained above, actions are rendered below the heading on mobile on purpose.
This PR brings back an issue that Dan fixed some time ago.

The header end slot should probably be removed in v4 and replaced by the header actions slot, since the header end is only used for select filters on widgets. Essentially that's a select action, and an option for filter button will be added with https://github.com/filamentphp/filament/issues/10594.

Feel free to address the `x-on:click.stop` issue in a separate PR.

**Pull request closed without merging**
