### PR TITLE
add translation to breadcrumbs for the plural resource name

### PR DESCRIPTION
**Pull request by ronnytorresmtz**
apply translation to the breadcrumbs resource name

### CODE REVIEW

**Comment by zepfietje** [comment]
What's the issue here exactly?
The label returned from `getBreadcrumb` should be translated already.

**Comment by ronnytorresmtz** [comment]
For example if the application displays "Contacts >Edit" when apply translate as you mentioned that the getBredcrub translate the reality is that I got the action translate like "Contracts/Editar" but not the plural resource name.

I have this for example I used "hola" just to explicit the issue:

```
     public function getBreadcrumb(): ?string
      {
          return __('Hi');
      }
      
  
      public function getModelLabel(): ?string
      {
          return __('Contacts');
          
      }
  
      public function getTitle(): string | Htmlable
      {
          return __('Contacts');
      }
```
Te result is "**Contacts** > hola" insted of  "**Contactos** > hola"..... the plural resource name is not translated

withoutTrans

withTrans

**Comment by zepfietje** [comment]
You probably want to override `getPluralModelLabel`.

**Comment by ronnytorresmtz** [comment]
Thank you Zep, I tested and suppose to work as you mentioned but it did not.

withTrans2

result

Regards,

**Comment by zepfietje** [comment]
Make sure to pass the plural, since now you're still letting Laravel handle the pluralization, which only works well for English.

**Comment by ronnytorresmtz** [comment]
I not sure what do you mean because its a direct translation word I made the pluralization in the translation,....

The only way I could make work was modifing this (on purple color). (vendor/filament/filament/scr/Resources/Pages/Page.php)

codefix

Thank you Zep

**Pull request closed without merging**
