### PR TITLE
Enables autofocusing in wizard on page load

### PR DESCRIPTION
**Pull request by maltebaer**
Hey folks,

I noticed that autofocusing an input does not work on the first/default step of a wizard.

I'm not sure if that is a bug or intentionally omitted, due to some reason I'm not aware of.

If it was disabled on purpose, feel free to close this PR. Otherwise I'm happy to tackle the three points below (where necessary).

- [ ] Changes have been thoroughly tested to not break existing functionality.
- [ ] New functionality has been documented or existing documentation has been updated to reflect changes.
- [ ] Visual changes are explained in the PR description using a screenshot/recording of before and after.

### CODE REVIEW

**Comment by danharrin** [comment]
Can you explain why the fields inside the wizard arent autofocused in the same way that ones outside the wizard are by default?

**Comment by maltebaer** [comment]
Honestly, I do not really know why this happens. And apparently it does work from time to time.

I tried to reproduce the bug in the filament demo. At least on my machine it does not work as expected.

You can check it out here: https://github.com/filamentphp/demo/compare/main...maltebaer:filament-demo:main

**Comment by zepfietje** [comment]
@danharrin, I'm not sure if this is a good idea when you have other fields outside the wizard on the same page? I guess autofocus on those fields would be broken by the wizard field, or is that fine?

**Comment by danharrin** [comment]
I thought that too, before I realised that only one field on a page should be autofocused anyway

**Comment by zepfietje** [comment]
Yeah exactly, should be fine then.

**Pull request merged**
