### PR TITLE
fix-v3/sidebar flicker on refresh

### PR DESCRIPTION
**Pull request by wychoong**
before

https://user-images.githubusercontent.com/67364036/222981236-cc1335cd-d412-4426-b69f-312c654a74ec.mov

after

https://user-images.githubusercontent.com/67364036/222981241-4fc8c2b7-a3c0-44e9-9e81-e5758e6bec99.mov

### CODE REVIEW

**Comment by danharrin** [comment]
Theres also an issue when its partially collapsed, did you see that?

**Comment by wychoong** [comment]
> Theres also an issue when its partially collapsed, did you see that?

Not sure which one you referring. Is it from my changes?

**Comment by danharrin** [comment]
No but its a very similar problem... if you use `sidebarCollapsibleOnDesktop()` instead of `sidebarFullyCollapsibleOnDesktop()`

**Comment by wychoong** [comment]
> No but its a very similar problem... if you use `sidebarCollapsibleOnDesktop()` instead of `sidebarFullyCollapsibleOnDesktop()`

tried the `sidebarCollapsibleOnDesktop()`, not too sure, hope these transitions helps a little. 

for me is the `sidebarFullyCollapsibleOnDesktop()` is pretty obvious 😅

**Comment by wychoong** [comment]
there is another issue, when configured to topNavigation, on the first time login the sidebar is shown, due to the default is `isOpen = true`

https://github.com/filamentphp/filament/blob/e5dc098076e0aeb3974ed8a9f34844ecb0413639/packages/app/resources/js/index.js#L12

```php
// in context provider
 ->topNavigation()
  // ->sidebarCollapsibleOnDesktop()
  // ->sidebarFullyCollapsibleOnDesktop()
```

**Pull request merged**
