### PR TITLE
Allow modal close button to be hidden

### PR DESCRIPTION
**Pull request by archilex**
- [X] Changes have been thoroughly tested to not break existing functionality.
- [X] New functionality has been documented or existing documentation has been updated to reflect changes.
- [ ] Visual changes are explained in the PR description using a screenshot/recording of before and after.

Per my discussion with @zepfietje this adds an API to be able to hide the close button in modals. It can be hidden per modal or globally.

### CODE REVIEW

**Comment by zepfietje** [comment]
Thanks, @archilex!
Not sure about the naming yet, maybe something like `modalCloseButtonHidden()` would better match existing Filament APIs.
Looping in @danharrin as our native naming expert. 😄

**Comment by archilex** [comment]
@zepfietje Yeah I had that originally since it better reflects existing naming, but opted for this naming since it seems Filament naming usually reflects whatever state is usually `true`. But I'll do whatever you all prefer.

**Comment by zepfietje** [comment]
I see, @archilex.
Let's wait to hear what @danharrin thinks.

**Comment by danharrin** [comment]
IMO, `closeButton(false)`?

**Comment by archilex** [comment]
Dan again with the awesome naming! 👏

**Comment by zepfietje** [comment]
Damn Daniel.. back at it again.. 😜

Looks good to me, thanks Dan!

**Pull request merged**
