### PR TITLE
chore: update public asset paths

### PR DESCRIPTION
**Pull request by SupianIDz**
- [x] Changes have been thoroughly tested to not break existing functionality.
- [ ] New functionality has been documented or existing documentation has been updated to reflect changes.
- [x] Visual changes are explained in the PR description using a screenshot/recording of before and after.

For consistent placement of assets from vendors and have discussed #8415 

before :
Screenshot 2023-09-12 at 12 02 25

after :
Screenshot 2023-09-13 at 04 19 48

Screenshot 2023-09-13 at 04 21 11

### CODE REVIEW

**Comment by danharrin** [comment]
This is a breaking change. It needs to be a configuration option in config/filament.php if you want to see this.

**Comment by SupianIDz** [comment]
> This is a breaking change. It needs to be a configuration option in config/filament.php if you want to see this.

it will update automatically when the user does `composer update` or `composer dump` or `artisan filament:upgrade`

So there is no need for additional config just for that path.

even as if nothing had happened,
Screenshot 2023-09-13 at 07 14 40

**Comment by danharrin** [comment]
And it will leave a ton of dead files in their /public directory. No thanks.

**Comment by SupianIDz** [comment]
If I add config as you mean, will it be merged?

To be honest, it's very annoying when files from packages that shouldn't need to be done anything get mixed up with asset files from user development.

**Comment by danharrin** [comment]
Yup, I will merge config

**Pull request closed without merging**
