### PR TITLE
Update Ukrainian translations

### PR DESCRIPTION
**Pull request by noxoua**
Запис (Entry or Post):
Typically, "запис" can refer to the creation of new content, such as an article, news item, or blog post. An entry can contain substantial and important information, can be well-structured, include sections, headings, media insertions (images, videos), and more. You're essentially creating new content or an entry from scratch.

Допис (Update or Addition):
"Допис" can indicate adding additional information, updating, or editing existing content. A "допис" might be a short or supplementary update placed after the main entry. This can be useful when you need to make changes or add significant information to existing content.

- [x] Changes have been thoroughly tested to not break existing functionality.
- [x] New functionality has been documented or existing documentation has been updated to reflect changes.
- [x] Visual changes are explained in the PR description using a screenshot/recording of before and after.

### CODE REVIEW

**Comment by zepfietje** [comment]
@pxlrbt, do we have a Ukrainian translation manager to review these changes?

**Comment by noxoua** [comment]
If you have something that needs to be translated into Ukrainian, I can do it on weekends.

**Comment by zepfietje** [comment]
Cool! If you're part of our [Discord community](http://discord.gg/filament), @pxlrbt can add you as official translation manager.

**Comment by noxoua** [comment]
Just joined the discord. I have the same username there.

**Comment by zepfietje** [comment]
Thanks, @noxoua.
I'm going to merge this PR already.
Feel free to reach out to @pxlrbt on Discord to get assigned the translation manager role. 🙂

**Pull request merged**
