### PR TITLE
Fix chart widget filter responsiveness

### PR DESCRIPTION
**Pull request by bernhardh**
- [x] Changes have been thoroughly tested to not break existing functionality.
- [x] New functionality has been documented or existing documentation has been updated to reflect changes.
- [x] Visual changes are explained in the PR description using a screenshot/recording of before and after.

# Summary
This PR fixes the unreadable style of chart-headings with filters.

### With description

image

or even more extreme with viewport 375px

image

### Without description

image

### With description

image

### Without description

image

## Desktop

image

No changes

### CODE REVIEW

**Comment by zepfietje** [comment]
Could you rebase this PR on the `3.1` branch, @bernhardh?
There we added support for section header actions, and it needs to work well with that.

**Comment by bernhardh** [comment]
Thanks for feedback! I will have a look at this next week :)

**Comment by danharrin** [comment]
We do not need to delay 3.1 for this, so I've moved it to the v3 milestone

**Comment by zepfietje** [comment]
Yeah and 3.1 will potentially be released before this PR has been reworked already.

**Comment by bernhardh** [comment]
@zepfietje sorry for delay. Was a stressful week. Actually same changes for 3.1 with same effect

**Review by zepfietje — APPROVED** [review]

**Comment by zepfietje** [comment]
Thanks, @bernhardh.
I've fixed a number of cases that weren't properly handled yet.

**Comment by bernhardh** [comment]
@danharrin Why did you remove the `sm:flex-row sm:items-center` in your commit (https://github.com/filamentphp/filament/commit/36a1aa72abe7878293ad4dece334b4b79dab9f37#diff-4cbb45a38e248d0d4c26426ff92142f2d8d04651d2e75d1d8a4471d64657f672L61) ?

This results in having a wrong responsive behaviour of the filters again:

image


compared to v3.1.46

image

**Comment by danharrin** [comment]
The section icon and collapsible button were not inline with the heading on mobile, if you want to reattempt a fix while keeping that in mind you can

**Pull request merged**
