### PR TITLE
Docs update: Add info to hide column label

### PR DESCRIPTION
**Pull request by kachelle**
## Description
Add info to hide column label.

## Visual changes
new: 
image

## Functional changes

- [ ] Code style has been fixed by running the `composer cs` command.
- [ ] Changes have been tested to not break existing functionality.
- [x] Documentation is up-to-date.

### CODE REVIEW

**Comment by danharrin** [comment]
Thanks, but this is not official syntax or recommended since the column will not be accessible without a label

**Comment by kachelle** [comment]
> Thanks, but this is not official syntax or recommended since the column will not be accessible without a label

How would you recommend hiding a column header?

**Comment by danharrin** [comment]
If you want to make a PR, add a new method `hiddenHeaderLabel()` (getter is `isHeaderLabelHidden()`, property is `$isHeaderLabelHidden`), which applies a `sr-only` class around the label

**Comment by kachelle** [comment]
Ok! Maybe I'll try to make my first technical PR.

**Pull request closed without merging**
