### PR TITLE
Add hooks to relations

### PR DESCRIPTION
**Pull request by sebapastore**
This PR tries to provide hooks to create, edit and attach related records.

To implement a hook, you have to add it in the parent relation manager, i.e:

```
class OrdersRelationManager extends RelationManager
{

    ...

    public static function afterCreate($record)
    {
        // do some stuff and access the record data if you need 
    }
}
```

 I will be happy to receive any comments on this in order to improve it.

### CODE REVIEW

**Comment by ryangjchandler** [comment]
I think there might be a cleaner way of achieving this, without having to override each "action". Each of the modal handlers, i.e. `CreateRecord` should have access to the parent relation manager, so we could probably let users define hooks on that single class, reducing the amount of bloat.

**Comment by sebapastore** [comment]
Thanks for the insights! I will work on that.

**Comment by sebapastore** [comment]
There are cases in which is necessary to access record data in a hook. The relation manager doesn't have access to the record data. Should we pass the record in each hook?

**Comment by sebapastore** [comment]
Now each of the modal handler has access to the parent relation manager. I have updated the use case in my first comment. Let me know if there are other improvements to make.

**Comment by danharrin** [comment]
Hey! I've had to change the way relation managers work, so I've moved these changes to #281.

Thanks for your work!

**Comment by sebapastore** [comment]
Cool, thanks for considering this!

**Pull request closed without merging**
