### PR TITLE
feat: If labels are being used, include the labels in the headers of the example CSV.

### PR DESCRIPTION
**Pull request by bzy107**
## Description
The addition of functionality for headers during the download of example CSVs in the import modal.
スクリーンショット 2024-01-31 1 19 29

|use label|not use|
|---|---|
|スクリーンショット 2024-01-31 1 18 44result:スクリーンショット 2024-01-31 1 20 28|スクリーンショット 2024-01-31 1 21 07result:スクリーンショット 2024-01-31 1 21 37|

- [x] Visual changes (if any) are shown using screenshots/recordings of before and after.

## Code style

- [ ] `composer cs` command has been run.

## Testing

- [ ] Changes have been tested.

## Documentation

- [ ] Documentation is up-to-date.

### CODE REVIEW

**Comment by zhanang19** [comment]
Since this PR is changing default, I think this will make an issue for everyone who already using `ImportColumn` with label which resulting in unexpected CSV header. How about using flag like `labelAsHeader()` instead of changing the default?

**Comment by danharrin** [comment]
This isn't the desired behaviour IMO - as the computer-readable column name should take priority. That way, its guaranteed that the column will be matched when the example file is uploaded. The labels do not need to be unique, but the names do. The example should be downloadable and reuploadable.

**Comment by bzy107** [comment]
Thank you for your comment @danharrin.

The reasons for my submission of this PR are twofold:

- Labels are being utilized in validation.
- The characters specified in the labels are being used as headers in the exporter.

Additionally, since I am not a native English speaker, I would like the phrases specified in the labels to be used as headers. Based on these points, I believe that labels should also be used in examples.

Alternatively, should we consider implementing a flag like `labelAsHeader()` to address this?

**Comment by danharrin** [comment]
How about `exampleHeader()` where you can pass in whatever you want, which is more flexible?

**Comment by bzy107** [comment]
got it. I'll issue a PR if necessary.

**Pull request closed without merging**
