### PR TITLE
Show how to change default "per page" pagination value

### PR DESCRIPTION
**Pull request by amadeann**
- [ ] Changes have been thoroughly tested to not break existing functionality.
- [x] New functionality has been documented or existing documentation has been updated to reflect changes.
- [ ] Visual changes are explained in the PR description using a screenshot/recording of before and after.

### CODE REVIEW

**Comment by danharrin** [comment]
Thanks

**Comment by faydanube** [comment]
@danharrin Is there any way to change it globally instead of setting it up in every source file? I've searched the official documentation and issues for a long time, but I haven't found a solution yet.

**Comment by danharrin** [comment]
https://filamentphp.com/docs/3.x/tables/advanced#global-settings

**Comment by faydanube** [comment]
> https://filamentphp.com/docs/3.x/tables/advanced#global-settings

thx very very much!!!!

**Pull request merged**
