### PR TITLE
Update 05-viewing-records.md

### PR DESCRIPTION
**Pull request by sertxudev**
## Description

The infolist method inside `ViewRecord` isn't static.

### CODE REVIEW

**Comment by danharrin** [comment]
As per the line above

> you can define an `infolist()` method on the resource class:

**Comment by sertxudev** [comment]
@danharrin The code block is incorrect because the `infolist` method inside the `ViewRecord` class is not static. 

https://github.com/filamentphp/filament/blob/143e9b86d9633de53ecb086face0ba8bc6ba373b/packages/panels/src/Resources/Pages/ViewRecord.php#L219-L222

image

Later in this docs page the `infolist` method appears as non static.

https://github.com/filamentphp/filament/blob/143e9b86d9633de53ecb086face0ba8bc6ba373b/packages/panels/docs/03-resources/05-viewing-records.md?plain=1#L138-L148

**Comment by valpuia604** [comment]
@sertxudev read this https://filamentphp.com/docs/3.x/infolists/entries/getting-started#overview

**Comment by danharrin** [comment]
> you can define an infolist() method on the resource class:

The method is defined on the resource class, not on the resource page class

> Later in this docs page the infolist method appears as non static.

The section of the docs is about adding an additional page with an infolist, in which case the infolist is defined on the page and the method doesn't need to be static

**Comment by sertxudev** [comment]
Gotcha! Filament is so customizable that it is sometimes difficult to understand how to do it correctly. Thanks, awesome work!

**Pull request closed without merging**
