### PR TITLE
Split words on any whitespace for table search query string

### PR DESCRIPTION
**Pull request by judgej**
- [ ] Changes have been thoroughly tested to not break existing functionality.
- [ ] New functionality has been documented or existing documentation has been updated to reflect changes.
- [ ] Visual changes are explained in the PR description using a screenshot/recording of before and after.

### CODE REVIEW

**Comment by judgej** [comment]
I've got no idea what that auto-close is about. I cannot see any permissions settings when I create the PR, and none here on this closed PR. What am I missing?

The instructions says to go to the PR on the upstream repo - except the PR is here, not the upstream repo - that's where the changes are that I'm trying to PR. Am I supoosed to have created a PR of a PR?

**Comment by danharrin** [comment]
You need to use a branch off of 3.x on your fork, we cant write to the default branch

**Comment by judgej** [comment]
Okay, I thought I had - 3.x was showing as the default branch. I'll put my glasses on and try again.

**Comment by danharrin** [comment]
You need to make a PR **to** 3.x **from** a non-3.x branch on your fork

**Pull request closed without merging**
