### PR TITLE
Update Swedish translations

### PR DESCRIPTION
**Pull request by adevade**
Add missing translations and update some.

### CODE REVIEW

**Comment by adevade** [comment]
Well, that diff bot is just **insane**! Wow! 🤯

**Comment by danharrin** [comment]
Thanks

**Comment by danharrin** [comment]
> Well, that diff bot is just **insane**! Wow! 🤯

Well... that comment is pretty inaccurate tbh 😂

**Comment by mpociot** [comment]
> > Well, that diff bot is just **insane**! Wow! 🤯
> 
> Well... that comment is pretty inaccurate tbh 😂

haha I guess the bot tries to make sense of the translation keys 😅

**Comment by danharrin** [comment]
@mpociot are you feeding the Laravel Nova changelogs in there? 😂

**Comment by sschlein** [comment]
Maybe it fixed the multi select and you just haven't noticed that it was broken? 😂

**Comment by adevade** [comment]
Yeah, the last two points may not be that accurate. 😅 But the first two are really impressive!!

**Comment by danharrin** [comment]
> But the first two are really impressive!!

I promise that it works much better on other PRs that arent just translations :D

**Pull request merged**
