### PR TITLE
Apply rounding to collapsible header

### PR DESCRIPTION
**Pull request by howdu**
- [x] Changes have been thoroughly tested to not break existing functionality.
- [ ] New functionality has been documented or existing documentation has been updated to reflect changes.
- [ ] Visual changes are explained in the PR description using a screenshot/recording of before and after.

Changes requested from @zepfietje 
https://github.com/filamentphp/filament/pull/7882#issuecomment-1684902907

Also updated the builder + repeater to use a `<header>` tag.

### CODE REVIEW

**Comment by zepfietje** [comment]
Thanks for following up, @howdu!

Can the rounding be achieved by adding an `overflow-hidden` class instead? Would make it easier to maintain and apply different rounding to the box as a whole.

> Also updated the builder + repeater to use a `<header>` tag.

Can you revert this change please? The `<header>` tag is only valid semantically inside a sectioning element. No worries, I had to look this up during the redesign too. 😄

**Comment by howdu** [comment]
@zepfietje I see your point maybe best to revert all of this apart from the attribute reordering? 

Adding `overflow-hidden` could prevent absolute positioned elements from overflowing. Tested with dropdown at the bottom and Choices.js cleverly knows it's going to be hidden so works differently but it's not great UX.

https://github.com/filamentphp/filament/assets/533658/a9aad42d-ac45-4419-aed2-a563f7e1d4a1

**Comment by zepfietje** [comment]
Ah yeah that's the reason. Maybe just apply `overflow-hidden` when collapsed?

**Comment by danharrin** [comment]
Okay if you're planning to revert all of this, you might as well submit a new PR with that `overflow-hidden` only for collapsed sections, as Zep says 👍

**Pull request closed without merging**
