### PR TITLE
Fix searchable selects

### PR DESCRIPTION
**Pull request by archilex**
The PR fixes searchable selects in v3 that were not loading or searching, but were throwing this error:
`Cannot read properties of null (reading 'includes')`. 

You can see the problem in the most recent version of the v3 demo with any searchable select. 

- [ ] Changes have been thoroughly tested to not break existing functionality.
- [ ] New functionality has been documented or existing documentation has been updated to reflect changes.
- [ ] Visual changes are explained in the PR description using a screenshot/recording of before and after.

### CODE REVIEW

**Comment by zepfietje** [comment]
Hmm it's still not working for me and I'm getting this console error:
`Unhandled Promise Rejection: TypeError: this.state?.includes is not a function. (In 'this.state?.includes(n.value)', 'this.state?.includes' is undefined)`

**Comment by zepfietje** [comment]
Getting `Unhandled Promise Rejection: TypeError: this.state.includes is not a function. (In 'this.state.includes(n.value)', 'this.state.includes' is undefined)`

**Comment by archilex** [comment]
Where are you seeing this? In the demo app at least it's working on every select I can find.

**Comment by zepfietje** [comment]
The brand select on `/shop/products/1/edit` in the demo.

Edit: actually in other places too. Haven't found a case where it works yet.

**Comment by archilex** [comment]
Very weird. It's all working for me, including shop/products/1/edit

Screenshot 2023-07-21 at 1 51 33 AM

**Comment by zepfietje** [comment]
Have you only tested on `create` pages, @archilex?
Seems like it does work there but it fails on the `edit` page.

**Comment by archilex** [comment]
Now I see the problem. Thanks. I'll look into it.

**Comment by archilex** [comment]
Ok...now try 😜

**Comment by zepfietje** [comment]
Perfect, thanks!

**Pull request merged**
