### PR TITLE
Fix sidebar flickering

### PR DESCRIPTION
**Pull request by archilex**
This fixes the flickering that was happening when no sidebar collapsing was used. Basically, with the sidebar now being sticky, `main` also needs the same `style="display:flex"` and `hidden` as when collapsible is used.

Here's a video and you can't tell but there are multiple refreshes at the end too and `main` isn't flickering anymore. 

https://github.com/filamentphp/filament/assets/6097099/ed5a6ca2-78c5-4e42-9e73-033b879bfd88

(And forgive my lack of github knowledge here...since the other PR #8116  was merged and then reverted, I wasn't really sure if you can revert the previous revert and so this PR is enough...or do I need to create an entirely new PR with all the changes?)

### CODE REVIEW

**Comment by danharrin** [comment]
Can you include the changes from that PR in this one please?

**Comment by danharrin** [comment]
You should just be able to merge that branch into this one

**Comment by danharrin** [comment]
I've merged the old PR in and tested `sidebarCollapsibleOnDesktop` and `sidebarFullyCollapsibleOnDesktop`, here's whats happening for me:

Screenshot 2023-09-11 at 11 42 09

**Comment by archilex** [comment]
@danharrin So fix-code-style is deleteing the space before all the `lg:sticky` used to concatenate with `openSideBarClasses` which means when it's compiled it's joined with the class before it. 

I could adding another concatenated space like this: `@js($openSidebarClasses . ' ' . 'lg:sticky')`  but I'm not sure if that will get removed as well?  Or another suggestion?

**Comment by danharrin** [comment]
Probably add a format-ignore comment for now

**Comment by archilex** [comment]
Ah ok. I wondered what those comments were for!  I’ll do that.

**Comment by archilex** [comment]
I might have gone overboard with the `format-ignore` comments. haha. 

I also went ahead and changed the concatentation to make it more obvious that this needs to be there.

**Comment by danharrin** [comment]
Thanks

**Comment by coolsam726** [comment]
image
After doing a patch update to ^3.0.48, this seems to have successfully BROKEN my layout! I am developing my panel as a standalone plugin. I wonder if this merge is stable, or maybe there is something I am missing.

**Comment by danharrin** [comment]
Recompile your stylesheet.

**Comment by coolsam726** [comment]
> Recompile your stylesheet.

I was using a custom theme compiled into a package, I finally had to upgrade the theme package and re-build it for this to work. Thanks @danharrin.

**Comment by danharrin** [comment]
This is why we dont recommend people distributing compiled stylesheets in packages, it should be up to the user to do that

**Comment by faizananwerali** [comment]
Screenshot 2023-09-15 at 3 53 30 PM

~~Completely broke my layout, and I am not even developing a plugin. All I did was `composer update` and `npm run dev` and all the layout is broken. Downgrading to version 3.0.47.~~

~~I'm using a 13-inch Mac M1 Pro and the layout is totally off.~~

## Edit:
The issue is now resolved because I had overwritten the `vendor/filament/filament/resources/views/components/sidebar/index.blade.php` file to redesign the layout. Applied new changes made in this pull request manually to my code and it is working.

**Comment by zepfietje** [comment]
@danharrin @archilex, the format ignore comments don't work around HTML element attributes IIRC. Code style fixer totally messed up the formatting on 3.x now. Could you have a look and apply a fix, @archilex?

Please run Pint locally to see what the actual formatting result is like.

**Comment by archilex** [comment]
@zepfietje Im out of town until Monday so I can’t get to it until then. Might need to revert in the meantime

**Comment by archilex** [comment]
@zepfietje Im out of town until Monday so I can’t get to it until then. Might need to revert in the meantime

**Comment by zepfietje** [comment]
No worries, @archilex. It's fine if you work on it next week.

Not sure if the breaking reports above are due to the formatting, @danharrin?
Did you check after merging?

**Comment by danharrin** [comment]
Fixed in 71630f5ef01dae5c714df4bb254edeb9eac2f960

**Pull request merged**
