### PR TITLE
Fix sticky form actions with custom footer

### PR DESCRIPTION
**Pull request by joaovdiasb**
Improves the timing of the fixed footer appearing when you have a custom footer

### CODE REVIEW

**Comment by danharrin** [comment]
Hmmm... not sure about this. Shouldn't we calculate how far the buttons are from the bottom of the page and use that value? Otherwise it won't respect relation managers or anything.

**Comment by joaovdiasb** [comment]
> Hmmm... not sure about this. Shouldn't we calculate how far the buttons are from the bottom of the page and use that value? Otherwise it won't respect relation managers or anything.

Of course, I forgot about this scenario, I needed to create a reference element to check offsetTop because of sticky

**Comment by danharrin** [comment]
Please use Alpine's `x-ref` feature instead of an ID :)

**Comment by danharrin** [comment]
You could even get away with `$el` probably, then you don't need an extra element?

**Comment by joaovdiasb** [comment]
> You could even get away with `$el` probably, then you don't need an extra element?

it's because with sticky the offset changes and the element keeps flashing when scrolling

**Comment by zepfietje** [comment]
Are you able to finish this PR, @joaovdiasb? 🙂

**Comment by joaovdiasb** [comment]
> Are you able to finish this PR, @joaovdiasb? 🙂

it is not possible to resolve referencing the buttons itself with `$el`, because it is applied `isSticky` class losing offsetTop, it works but causes a visual bug where the element keeps blinking when scrolling, any other ideas?

**Comment by zepfietje** [comment]
Hmm not sure, but thanks for clarifying.
Could you explain why exactly the current approach is broken for custom footers?

**Comment by joaovdiasb** [comment]
Current:
CleanShot 2023-04-10 at 15 56 04

New
CleanShot 2023-04-10 at 16 02 23

it's a better sticky approach only when needed, which is when the current view is above the form's buttons

**Comment by zepfietje** [comment]
Hmm and how is this caused by a custom footer specifically?

**Comment by zepfietje** [comment]
> Hmm and how is this caused by a custom footer specifically?

Could you clarify, @joaovdiasb? 🙂

**Comment by danharrin** [comment]
I've reverted #5947 to fix this issue, that caused it for me. I don't know exactly what issue @oddvalue was experiencing as there was no issue report

**Pull request merged**
