### PR TITLE
fix: Actions inheriting props from groups

### LINKED ISSUE #11850: assertActionHidden() not accounting for Action's ActionGroup
### Package

filament/actions

### Package Version

v3.2.48

### Laravel Version

v11.0.5

### Livewire Version

v3.4.8

### PHP Version

PHP 8.3.3

### Problem description

Given the following header actions:
```php
protected function getHeaderActions(): array
{
    return [
        Actions\DeleteAction::make(),
        ActionGroup::make([
            Actions\Action::make('approve'),
            Actions\Action::make('decline'),
        ])
            ->label(__('Respond to request'))
            ->visible(fn () => $this->record->is_approvable)
            ->button(),
    ];
}
```
And running the following test:
```php
it('does not show the "approve" button when the record cannot be approved', function () {
    $test = Test::factory()->create([
        'is_approvable' => false,
    ]);

    livewire(EditTest::class, ['record' => $test->getRouteKey()])
        ->assertActionHidden('approve');
});
```
The test fails with the following error: `Failed asserting that an action with name [approve] is hidden on the [App\Filament\Resources\TestResource\Pages\EditTest] component.`
Even though when visiting the page the button does not appear.

### Expected behavior

I would expect the visibility of an Action's parent ActionGroup to get taken into account when testing if an action is visible or not.

### Steps to reproduce

- Clone my reproduction repository
- `php artisan migrate:fresh --seed`
- `php artisan test`
- Create a Test resource in the UI and see the "Respond to request" button appear and disappear depending on the value for `is_approvable`

### Reproduction repository

https://github.com/wout-o/filament-actiongroup-test

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by danharrin**
Fixes #11850.

### CODE REVIEW

**Comment by nicko170** [comment]
This has broken actions within a group on tables, if they're not the standard View / Edit / Delete action, downgrading back to 3.2.50 fixes.

```
$table
  ->actions([
    Tables\Actions\ActionGroup::make([
      Tables\Actions\ViewAction::make(),
      Tables\Actions\Action::make('download_invoice')
        ->label('Download Invoice')
        ->icon('heroicon-o-arrow-down-on-square')
        ->action(fn (Invoice $record) => static::run($record))
    ])
 ])
```

Now throws an error when `$record` is accessed, 
```
Argument #1 ($record) must be of type Illuminate\Database\Eloquent\Model, null given, called in /Users/nickp/code/node/vendor/filament/support/src/Concerns/EvaluatesClosures.php on line 35
```

**Comment by danharrin** [comment]
Fixed

**Comment by darkclow4** [comment]
> This has broken actions within a group on tables, if they're not the standard View / Edit / Delete action, downgrading back to 3.2.50 fixes.
> 
> ```
> $table
>   ->actions([
>     Tables\Actions\ActionGroup::make([
>       Tables\Actions\ViewAction::make(),
>       Tables\Actions\Action::make('download_invoice')
>         ->label('Download Invoice')
>         ->icon('heroicon-o-arrow-down-on-square')
>         ->action(fn (Invoice $record) => static::run($record))
>     ])
>  ])
> ```
> 
> Now throws an error when `$record` is accessed,
> 
> ```
> Argument #1 ($record) must be of type Illuminate\Database\Eloquent\Model, null given, called in /Users/nickp/code/node/vendor/filament/support/src/Concerns/EvaluatesClosures.php on line 35
> ```

i think i still get this error when i want to hide action group based on record's data

```php
$table
    ->actions([
        Tables\Actions\ActionGroup::make([
            Tables\Actions\EditAction::make(),
            Tables\Actions\DeleteAction::make(),
        ])->hidden(fn (Model $record) => $record->active)
    ])
```

downgrading back to 3.2.50 fixes this error.

**Comment by danharrin** [comment]
@darkclow4 #11955

**Pull request merged**
