### PR TITLE
Upgrade Blade Heroicons

### LINKED ISSUE #4490: Upgrade Blade Heroicons

### PR DESCRIPTION
**Pull request by zepfietje**

### CODE REVIEW

**Comment by danharrin** [comment]
l8 prob needs removing from the github actions

**Comment by zepfietje** [comment]
Will handle that in this PR. 👍

**Comment by danharrin** [comment]
Is this ready for review?

**Comment by zepfietje** [comment]
Icon size and color improvements will be handled in a separate PR.

**Pull request merged**
