### PR TITLE
Upgrade to esbuild v0.17.x

### PR DESCRIPTION
**Pull request by tanthammar**
As requested @danharrin 
esbuild 0.17.x has a new api.

### CODE REVIEW

**Comment by tanthammar** [comment]
Only one compiling error, but that is from the Trix src:
(but non-breaking, only a warning)

image

**Comment by zepfietje** [comment]
Thanks for the PR, @tanthammar!
Looks like the compiled JS is no longer minimized though?

**Comment by danharrin** [comment]
Just tested this, all form components are broken for me, similarly to what happened when I attempted this. I tested on all browsers with the same behaviour.

**Comment by tanthammar** [comment]
Let's check on Wednesday in my repo and yours.

**Pull request merged**
