### PR TITLE
Support hidden label in fieldset

### PR DESCRIPTION
**Pull request by josefbehr**
- [x] Changes have been thoroughly tested to not break existing functionality.
- [x] New functionality has been documented or existing documentation has been updated to reflect changes.
- [x] Visual changes are explained in the PR description using a screenshot/recording of before and after.

before: 
image

after:
image

### CODE REVIEW

**Comment by josefbehr** [comment]
I know that the label can be hidden by just setting an empty string as the label, but I think it should respect the `hiddenLabel()` method as well, which also enables dynamically showing or hiding the label.

**Comment by zepfietje** [comment]
Thanks for the PR, @josefbehr.
I've updated the implementation.
However, I think we should potentially still output the label, but add `sr-only`.

**Comment by danharrin** [comment]
We should add a `label-hidden` attribute to the fieldset Blade component that handles `sr-only`

**Comment by zepfietje** [comment]
> We should add a `label-hidden` attribute to the fieldset Blade component that handles `sr-only`

Agree. Mark as ready for review when you've handled that, @josefbehr. 🙂

**Comment by josefbehr** [comment]
done

**Pull request merged**
