### PR TITLE
Fix: padding when action is set to slideover

### LINKED ISSUE #4572: Actions with slideover - padding
### Package

filament/filament

### Package Version

v2.16.33

### Laravel Version

9.35.1

### Livewire Version

_No response_

### PHP Version

8.1.11 

### Problem description

I noticed that this problem was already solved in the older version, but in the latest version the problem reappeared.

Somehow the `->slideOver()` function behaves strangely for all Action classes. Even though it is defined in the blade file, the padding still appears in the html.

captures_chrome-capture-2022-9-17

### Expected behavior

Padding should only be included if the modal does not use slideover.

### Steps to reproduce

1. Create filament page `php artisan make:filament-page TestPage`.
2. Open `TestPage.php` and create `getActions()` function.
```
...
protected function getActions(): array
{
    return [
        Action::make('create')
            ->slideOver()
            ->action(function (array $data) {
                dd($data);
            })
            ->form([
                TextInput::make('title')
            ])
    ];
}
```
3. Visit page and click on `Create` button.

### Reproduction repository

https://github.com/rowdy4e/filamentphp-modal-slideover-padding

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by awcodes**
Fixes #4572

### CODE REVIEW

**Comment by zepfietje** [comment]
How's the padding around the modal on small screens now? Judging from the code, it looks like that's broken after this PR?

**Comment by awcodes** [comment]
Padding is the same. it was just moved to a different element. The issue causing this is a dom diffing issue. Moving the logic to a different element allows it to update properly.

Screen Shot 2022-10-22 at 1 04 05 PM

**Comment by awcodes** [comment]
Screen Shot 2022-10-22 at 1 12 35 PM

**Comment by danharrin** [comment]
Thanks

**Comment by zepfietje** [comment]
Great, thanks for fixing, @awcodes. 🙏

**Pull request merged**
