### PR TITLE
Add Octane documentation

### PR DESCRIPTION
**Pull request by haringsrob**
While working on a project I figured out that hooks etc are not working.

I solved it by registering a listener and decided to contribute my learnings.

### CODE REVIEW

**Comment by danharrin** [comment]
I'm confused, because the Serving event is being dispatched via middleware. Why would Octane not run middleware on multiple requests? 🤔

**Comment by haringsrob** [comment]
I believe it is because the service is scoped? 

```
        $this->app->scoped('filament', function (): FilamentManager {
            return new FilamentManager();
        });
```

There is no static caching inside that service, and octane does not reboot service providers so every request there is a new instance of FilamentManager, but it will be blank.

**Comment by haringsrob** [comment]
Did a quick test and changed scoped to singleton and all works fine (so no workaround needed).

I do not know what the impact of it is.

**Comment by danharrin** [comment]
Hm well I think it's probably best that we don't change it because it's probably got unintended consequences

**Comment by haringsrob** [comment]
- [ ] Update the docs to use a middleware instead of providers to ensure a consistent outcome instead of a octane specific approach.

**Comment by zepfietje** [comment]
Mark as ready for review when done, @haringsrob!

**Comment by zepfietje** [comment]
@haringsrob, are you still able to finish this PR? 😄

**Comment by zepfietje** [comment]
Closing due to inactivity.
Feel free to open a complete PR.

**Pull request closed without merging**
