### PR TITLE
Support extraAlpineAttributes on non-masked text input

### PR DESCRIPTION
**Pull request by leandrocfe**
Please note that the extraAlpineAttributes option is only available when using the mask option. However, with this feature, the position can be changed, allowing it to be used without a mask as well.

### CODE REVIEW

**Comment by zepfietje** [comment]
Thanks, @leandrocfe!
Doesn't it make sense to move it right above the line containing `$getExtraInputAttributeBag()` though?

**Comment by leandrocfe** [comment]
> Thanks, @leandrocfe!
> Doesn't it make sense to move it right above the line containing `$getExtraInputAttributeBag()` though?

Hi Zep! I agree :)

**Comment by danharrin** [comment]
Text inputs without a mask arent Alpine components, so why would we merge attributes?

There are other methods like extraInputAttributes() that are always applied

**Comment by danharrin** [comment]
Hmm I've just seen that they are actually Alpine components because of validation, sorry for that confusion 🤔

I agree with Zep about positioning

**Comment by zepfietje** [comment]
Mark as ready when you've applied the requested change, @leandrocfe! 🙂

**Comment by leandrocfe** [comment]
> Mark as ready when you've applied the requested change, @leandrocfe! slightly_smiling_face

Hi @zepfietje, fixed.
Sorry for the delay.

**Review by zepfietje — APPROVED** [review]

**Pull request merged**
