### PR TITLE
Disable cells while table loading

### LINKED ISSUE #7294: Disable interactive table cells while loading
Table cells containing a checkbox or input should be disabled during table loading states.

### PR DESCRIPTION
**Pull request by thethunderturner**
## Description

Closes #7294, reopens #13961. As @zepfietje mentioned, further research needs to be made to check if it works with disabled attribute.

EDIT: It appears to be working. Also made a minor UI change for the disabled state of the select column (I showed after and before).

## Visual changes

https://github.com/user-attachments/assets/4c04ff25-4576-41ef-a4d4-4928ba4a6634

## Functional changes

- [x] Code style has been fixed by running the `composer cs` command.
- [ ] Changes have been tested to not break existing functionality.
- [x] Documentation is up-to-date.

### CODE REVIEW

**Comment by thethunderturner** [comment]
Indeed it seems there is an issue with the select column :thinking:

**Comment by danharrin** [comment]
Hi, sorry but this is a v4 PR

**Comment by thethunderturner** [comment]
> Hi, sorry but this is a v4 PR

Cant I just change the target branch to 4.x @danharrin? Why close it?

**Comment by danharrin** [comment]
It won't merge into v4 as the column views dont exist in v4

**Comment by thethunderturner** [comment]
> It won't merge into v4 as the column views dont exist in v4

Understood. I will make a fix for v4 then. Thanks for elaborarating

**Pull request closed without merging**
