### PR TITLE
Add a new render hook at the end of view record page

### PR DESCRIPTION
**Pull request by krzysztofengineer**
## Description

I need to inject some code at the end of the view record template.It would be much easier if there was a render hook.

### CODE REVIEW

**Comment by dissto** [comment]
Isn't `PanelsRenderHook::SIMPLE_PAGE_END` or `PanelsRenderHook::PAGE_END` just what you need? 🤔

**Comment by danharrin** [comment]
Yeah or `PAGE_FOOTER_WIDGETS_BEFORE`

**Comment by krzysztofengineer** [comment]
Unfortunately I need to target only view pages. I need to call this from a package so I can’t scope only particular resources

**Comment by danharrin** [comment]
In the view you could check `@if ($this instanceof ViewRecord)`

**Comment by krzysztofengineer** [comment]
> In the view you could check `@if ($this instanceof ViewRecord)`

so should I publish a view-record view from a package?

**Comment by danharrin** [comment]
no? in the hook view

**Pull request closed without merging**
