### PR TITLE
Add Reset Password notification locale

### PR DESCRIPTION
**Pull request by donatiss**
## Description

Send reset password notification by user selected locale (app->getLocale()) 

## Visual changes

none

## Functional changes

- [x] Code style has been fixed by running the `composer cs` command.
- [x] Changes have been tested to not break existing functionality.
- [x] Documentation is up-to-date.

### CODE REVIEW

**Comment by danharrin** [comment]
Correct me if I'm wrong, but Filament isn't using this URL parameter at all even though you're setting it. So it feels weird to introduce it. But you can absolutely override any of these classes in your own app if you want to make this change. Feel free to push back if I am missing something and we can think about reopening

**Comment by donatiss** [comment]
app()->getLocale() is Laravel function. So when i'm using multi languages, password reset always send email in default language, not user selected language.

**Comment by danharrin** [comment]
I know, but we dont run setLocale() anywhere do we?

**Comment by donatiss** [comment]
Laravel doesn't by default?

`The default language for your application is stored in the config/app.php configuration file's locale configuration option, which is typically set using the APP_LOCALE environment variable. You are free to modify this value to suit the needs of your application.`

**Comment by danharrin** [comment]
It doesnt read the query string though?

**Comment by donatiss** [comment]
I'll check it next week

**Pull request closed without merging**
