### PR TITLE
Fix extra request on non-modal action mount

### PR DESCRIPTION
**Pull request by zepfietje**

### CODE REVIEW

**Comment by danharrin** [comment]
How about the other modals in this component?

**Comment by zepfietje** [comment]
Yeah, they would need to be changed in a similar way.
However, I just wanted to be sure this change is a good fix before implementing it in all places.
Could you confirm? Then I'll finish the PR.

**Comment by danharrin** [comment]
It looks fine, but have you tested by clicking on modal and non-modal actions sequentially to check that Alpine reregisters the new event listener?

**Comment by zepfietje** [comment]
I've updated this PR to handle all modals.
From my testing everything works fine.

**Pull request merged**
