### PR TITLE
Fix issue 8487 reported in for postgresql queries on Integer and BigInteger columns

### LINKED ISSUE #8487: TextColumn::make('myBigIntColumn')->searchable() on  with BigInteger value not working
### Package

filament/filament

### Package Version

3.0.46 (in lower versions like 3.0.8 the error does not exist)

### Laravel Version

V10.23.1

### Livewire Version

v3.0.3

### PHP Version

PHP 8.1

### Problem description

When using the tables search window the following error comes up.
Error message: 
`SQLSTATE[42883]: Undefined function: 7 ERROR: function lower(bigint) does not exist LINE 1: select count(*) as aggregate from "users" where (lower(myBigIntColumnName....`

### Expected behavior

Display search results

### Steps to reproduce

Install repo, 
use .env.sail as .env file
run vendor/bin/sail up 
Login with admin@admin.admin / password: admin 
http://localhost/admin/users
use search window in table

### Reproduction repository

https://github.com/edwink75/filament-issue-1

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by edwink75**
Fix issue reported in for postgresql queries on Integer and BigInteger columns

There is no new functionality and no visual changes
FIX: https://github.com/filamentphp/filament/issues/8487

- [x] Changes have been thoroughly tested to not break existing functionality.
- [ ] New functionality has been documented or existing documentation has been updated to reflect changes.
- [ ] Visual changes are explained in the PR description using a screenshot/recording of before and after.

### CODE REVIEW

**Comment by danharrin** [comment]
There are many other places where this needs fixing too, so one of us needs to fix those before I can merge

**Comment by edwink75** [comment]
> There are many other places where this needs fixing too, so one of us needs to fix those before I can merge

I can have a look on Thursday if I find other places and will fix it there, too. I'd be happy if you could point me in the right direction though :-)

**Comment by danharrin** [comment]
Try finding anywhere we use `lower(`

**Comment by edwink75** [comment]
> Try finding anywhere we use `lower(`

all fixed, I hope the way I fixed it is acceptable...

**Comment by edwink75** [comment]
Helle team, 
would you please merge this bugfix for the next release? Not sure why it hasn't been merged into yesterday's release.
If I need to make any changes, please advice, I need this to work.
Thank you

**Comment by danharrin** [comment]
This is a very complex part of the package that needs careful review, and I haven't had time to do that review yet. In the meantime, you can work around this in your own app by appending `::text` onto the column names.

**Comment by edwink75** [comment]
> This is a very complex part of the package that needs careful review, and I haven't had time to do that review yet. In the meantime, you can work around this in your own app by appending `::text` onto the column names.

For everybody else who might read this: This is how you would implement the workaround

`TextColumn::make("some_integer_column")->searchable("some_integer_column::text"),`

**Comment by edwink75** [comment]
Hello team,
it's been 3 weeks, I fixed everything as requested. Could someone please review and merge? Or do you exclude people using Postgres as DB?
Thank you!

**Comment by danharrin** [comment]
We aren't excluding Postgres users. I use Postgres myself. This issue has an easy userland workaround, and as I said above, I need to review this PR carefully, as it has the potential to break many apps if implemented wrong.

**Pull request merged**
