### PR TITLE
Add "kirschbaum-development/eloquent-power-joins": "^3.0" to composer…

### PR DESCRIPTION
**Pull request by vikijel**
….json

## Description

This should fix the [missing trait issue](https://github.com/filamentphp/filament/discussions/13885) that reveals when only filament/forms is required into project and ->relationship() method is called on Select, throws missing trait power joins.

I am not sure how you do the subpackages and how to test it properly, the composer line was copied from main filament composer.json to the one in filament/support

## Visual changes

no visual changes

## Functional changes

- [ ] Code style has been fixed by running the `composer cs` command.
- [ ] Changes have been tested to not break existing functionality.
- [ ] Documentation is up-to-date.

### CODE REVIEW

**Comment by danharrin** [comment]
Please remove the requirement from tables as that depends on this anyway

**Comment by vikijel** [comment]
> Please remove the requirement from tables as that depends on this anyway

I would prefer someone who has better knowledge of Filament and its subpackages and their dependencies to do a proper dependencies review.

I am just trying to fix this 1 obviously missing depndency of the support package.

I don't dare to remove/change existing dependencies in package i know for 3 days (and used just forms so far)

PS: Another dependency to eloquent-power-joins is in the root filament [composer.json](https://github.com/filamentphp/filament/blob/3.x/composer.json#L14) as well.

**Comment by danharrin** [comment]
Please do so, I know it will be fine because it requires the support package, just needs removing from tables

**Comment by vikijel** [comment]
ok, so remove from the root composer.json too? (as it requires filament/support)

**Comment by danharrin** [comment]
sure as long as the CI still passes

**Comment by vikijel** [comment]
Removed from root & tables composer.json, both do have dep. to filament/support

And looks like the support is the only package really using it:
powerjoinsusages

I am not sure how to correctly handle composer.lock and if it matters in this case (the dependency is the same, just defined elsewhere)

**Comment by danharrin** [comment]
Please run `composer update --lock` in the root of the project

**Comment by vikijel** [comment]
Didn't go well... something about 3.9999999.9999999.9999999-dev, while the root package has * and the tables have self.version so idk what that is about?

```shell
composer update --lock
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires filament/support == 3.9999999.9999999.9999999-dev (exact version match), it is satisfiable by filament/support[3.x-dev] from composer repo (https://repo.packagist.org) but 
filament/support[dev-3.x-fix-support-require-eloquent-power-joins] from path repo (packages/support) has higher repository priority. The packages from the higher priority repository do not match your constr
aint and are therefore not installable. That repository is canonical so the lower priority repo's packages are not installable. 
```

I am probably doing something wrong, these composer messages always confuse me, sorry.

**Comment by danharrin** [comment]
How about without --lock?

**Comment by vikijel** [comment]
```shell
composer update       
Loading composer repositories with package information
Updating dependencies
Lock file operations: 0 installs, 19 updates, 2 removals
  - Removing doctrine/cache (2.2.0)               
  - Removing doctrine/event-manager (2.0.1)       
  - Upgrading aws/aws-sdk-php (3.316.9 => 3.319.2)
  - Upgrading carbonphp/carbon-doctrine-types (2.1.0 => 3.2.0)
  - Upgrading doctrine/dbal (3.8.6 => 4.0.5)
  - Upgrading filament/support (3.x-dev => dev-3.x-fix-support-require-eloquent-power-joins)
  - Upgrading guzzlehttp/guzzle (7.8.2 => 7.9.2)
  - Upgrading guzzlehttp/psr7 (2.6.3 => 2.7.0)
  - Upgrading laravel/framework (v11.18.1 => v11.20.0)
  - Upgrading laravel/pint (v1.17.0 => v1.17.2)
  - Upgrading laravel/serializable-closure (v1.3.3 => v1.3.4)
  - Upgrading nette/utils (v4.0.4 => v4.0.5)
  - Upgrading nunomaduro/collision (v8.3.0 => v8.4.0)
  - Upgrading orchestra/canvas (v9.1.0 => v9.1.1)
  - Upgrading orchestra/testbench-core (v9.2.2 => v9.2.3)
  - Upgrading orchestra/workbench (v9.1.0 => v9.4.1)
  - Upgrading pestphp/pest (v2.34.9 => v2.35.0)
  - Upgrading sebastian/comparator (5.0.1 => 5.0.2)
  - Upgrading spatie/image (3.7.2 => 3.7.3)
  - Upgrading spatie/laravel-medialibrary (11.8.1 => 11.8.2)
  - Upgrading zbateson/mail-mime-parser (3.0.2 => 3.0.3)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 0 installs, 19 updates, 2 removals
  - Downloading sebastian/comparator (5.0.2)
  - Downloading aws/aws-sdk-php (3.319.2)
  - Downloading zbateson/mail-mime-parser (3.0.3)
  - Downloading orchestra/testbench-core (v9.2.3)
  - Downloading orchestra/canvas (v9.1.1)
  - Downloading orchestra/workbench (v9.4.1)
  - Downloading pestphp/pest (v2.35.0)
  - Downloading spatie/image (3.7.3)
  - Downloading spatie/laravel-medialibrary (11.8.2)
  - Removing doctrine/event-manager (2.0.1)
  - Removing doctrine/cache (2.2.0)
  - Upgrading carbonphp/carbon-doctrine-types (2.1.0 => 3.2.0): Extracting archive
  - Upgrading nette/utils (v4.0.4 => v4.0.5): Extracting archive
  - Upgrading laravel/serializable-closure (v1.3.3 => v1.3.4): Extracting archive
  - Upgrading laravel/framework (v11.18.1 => v11.20.0): Extracting archive
  - Upgrading guzzlehttp/psr7 (2.6.3 => 2.7.0): Extracting archive
  - Upgrading guzzlehttp/guzzle (7.8.2 => 7.9.2): Extracting archive
  - Upgrading sebastian/comparator (5.0.1 => 5.0.2): Extracting archive
  - Upgrading doctrine/dbal (3.8.6 => 4.0.5): Extracting archive
  - Upgrading filament/support (3.x-dev => dev-3.x-fix-support-require-eloquent-power-joins): Source already present
  - Upgrading laravel/pint (v1.17.0 => v1.17.2): Extracting archive
  - Upgrading aws/aws-sdk-php (3.316.9 => 3.319.2): Extracting archive
  - Upgrading zbateson/mail-mime-parser (3.0.2 => 3.0.3): Extracting archive
  - Upgrading orchestra/testbench-core (v9.2.2 => v9.2.3): Extracting archive
  - Upgrading orchestra/canvas (v9.1.0 => v9.1.1): Extracting archive
  - Upgrading nunomaduro/collision (v8.3.0 => v8.4.0): Extracting archive
  - Upgrading orchestra/workbench (v9.1.0 => v9.4.1): Extracting archive
  - Upgrading pestphp/pest (v2.34.9 => v2.35.0): Extracting archive
  - Upgrading spatie/image (3.7.2 => 3.7.3): Extracting archive
  - Upgrading spatie/laravel-medialibrary (11.8.1 => 11.8.2): Extracting archive
Generating autoload files
124 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
phpstan/extension-installer: Extensions installed
> larastan/larastan: installed
> nesbot/carbon: installed
> pestphp/pest: installed
No security vulnerability advisories found.
```

And subsequent composer update --lock did nothing

```shell
composer update --lock
Loading composer repositories with package information
Updating dependencies
Nothing to modify in lock file
Installing dependencies from lock file (including require-dev)
Nothing to install, update or remove
Generating autoload files
124 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
phpstan/extension-installer: Extensions installed
No security vulnerability advisories found.
```

**Comment by danharrin** [comment]
Thanks

**Pull request merged**
