### PR TITLE
Fix dark mode layout for sorting in table layout

### PR DESCRIPTION
**Pull request by StfnSl**
Fixed display bug for dark mode.
Missing German translation added for sorting

### CODE REVIEW

**Comment by danharrin** [comment]
Please send before / after screenshots of these changes

**Comment by StfnSl** [comment]
> Please send before / after screenshots of these changes

Sorry for the late reply, here are the screenshots

before:
Screenshot_20221025_194313

after:
Screenshot_20221025_194520

**Comment by pxlrbt** [comment]
> Fixed display bug for dark mode.

Why does this change light mode styling then?

**Comment by StfnSl** [comment]
I used the same css classes as when displaying the rows.

**Comment by danharrin** [comment]
How about the direction select?

**Comment by StfnSl** [comment]
> How about the direction select?

Yes, I had overlooked that, but it has now been made up and provided with the same css classes

**Pull request merged**
