### PR TITLE
Fix darkmode text color

### PR DESCRIPTION
**Pull request by Osknor**
The optional table heading did not look right in dark:mode so added tailwind classes to be in line with section heading.

Fieldset label also lacked text color classes, added the same ones there.

- [no] Changes have been thoroughly tested to not break existing functionality.
- [no] New functionality has been documented or existing documentation has been updated to reflect changes.
- [yes] Visual changes are explained in the PR description using a screenshot/recording of before and after.

table-before
table-after
field-before
field-after

### CODE REVIEW

**Comment by danharrin** [comment]
Isn't this fixed by having sensible default text colors set on the `<body>`?

**Comment by Osknor** [comment]
While that sounds totally valid and a solution, it was my naive experience that I flipped on dark mode found that the other filament components (that I had happen to use) translated over beautifully. So seemed in line to add this pattern of classes in the two places it seemed to have been overlooked.
I haven't looked closely enough to figure out if there was some reasoning why they were excluded here or if there were other components where they also logically could be added.

**Comment by danharrin** [comment]
This would be caused by any element that has text but no text color set, as in the panel builder we do have a default color. Anyway, I don't think this hurts too much.

**Comment by zepfietje** [comment]
This fix is fine indeed. I've added explicit text color to most elements, and probably just forgot these two.

**Pull request merged**
