### PR TITLE
Make entire repeater and builder item header collapsible

### PR DESCRIPTION
**Pull request by saade**
Repeaters and Builders currently only collapses when clicking on the collapse action or the label, which can be annoying if the item label is too short (the click area is too small)

This PR uses the same aproach as #9978 using `x-on:click.stop` on the other divs that shouldn't toggle the collapsed state of the component.

## Before
https://github.com/filamentphp/filament/assets/14329460/5aee9f19-5bc8-41cb-a1e7-998c0cad89a6

## After
https://github.com/filamentphp/filament/assets/14329460/40d72d9d-015e-4174-a7ae-b882127b1bb6

### CODE REVIEW

**Comment by saade** [comment]
Failing tests are not related to this PR.

**Review by zepfietje — CHANGES_REQUESTED** [review]
Could you make sure the `x-on:click.stop` is placed on the actual actions (or their direct wrapper element) and only rendered when the repeater item is collapsible?

Also, please apply the same treatment to builder items.

**Comment by saade** [comment]
Gonna finish this one tonight.

**Comment by saade** [comment]
@zepfietje its done, sorry for the delay on this one

**Comment by danharrin** [comment]
I don't think the conditional `x-on:click.stop` are that important as per Zep's comment, so happy to merge this as is. Thanks!

**Comment by saade** [comment]
Oops, i didn't paid attention on that part.

**Pull request merged**
