### PR TITLE
Adding alias for table filter method `column`

### PR DESCRIPTION
**Pull request by titantwentyone**
New method `field` added as alias to `column` in `SelectFilter` and `MultiSelectFilter` to better represent how the method can be used as per #3998. Docs also amended.

### CODE REVIEW

**Comment by zepfietje** [comment]
If we're going this direction, shouldn't `column()` call `field()` instead of the other way around? Also, we might want to mark `column()` as deprecated in that case.

Honestly, I'm not too sure about this change actually.

**Comment by zepfietje** [comment]
Yeah I just think, if we're going for it, we should go all the way. As long as it's not a breaking change of course (that's why we could just mark the old method as deprecated).

**Comment by danharrin** [comment]
Also we need a deprecated docblock with a replacement message on the old method

**Comment by zepfietje** [comment]
> Also we need a deprecated docblock with a replacement message on the old method

Yep, that's what I meant.

**Comment by titantwentyone** [comment]
Was also wondering if we should pull out `column()`, `getColumn()`, `attribute()`, `getAttribute()` into a trait?

**Comment by danharrin** [comment]
> Was also wondering if we should pull out `column()`, `getColumn()`, `attribute()`, `getAttribute()` into a trait?

Probably overkill atm, but thanks

**Pull request merged**
