### PR TITLE
Added red color to notifications number badge

### PR DESCRIPTION
**Pull request by jvitasek**
Hey, I'm thinking about something like this.

If we had some type of configuration so that users could customize the color of their badge when no notifications are present, and also when there are notifications.

- [ ] Changes have been thoroughly tested to not break existing functionality.
- [ ] New functionality has been documented or existing documentation has been updated to reflect changes.
- [ ] Visual changes are explained in the PR description using a screenshot/recording of before and after.

### CODE REVIEW

**Comment by danharrin** [comment]
I think we would only accept it if it is customisable, but I'm really not sure if it's useful enough?

**Comment by jvitasek** [comment]
> I think we would only accept it if it is customisable, but I'm really not sure if it's useful enough?

So the reason I'm thinking about this is that multiple clients reported they "miss" new notifications. I thought about doing this over JS but maybe someone would find the extra customization useful?

AFAIK right now you can only override the actual notification list, not the default trigger.

**Comment by danharrin** [comment]
How about publishing the `database-notifications-trigger.blade.php` view into your app, and then you can modify it? I think this is probably too far to introduce config values for since we haven't had this request before, but if I do get this request again then I will remember this PR and see if we should merge it. Thank you anyway

**Comment by danharrin** [comment]
Let me know if you have trouble publishing this view

**Pull request closed without merging**
