### PR TITLE
fix get tags with no types.

### PR DESCRIPTION
**Pull request by Saifallak**
trying to get tags with no type specified (means get all with type and without), expected to get all tags but with this, it searches with no-tags.

### CODE REVIEW

**Comment by Saifallak** [comment]
@danharrin can you help with those phpstan errors?

**Comment by danharrin** [comment]
The current behaviour is correct IMO and this would be a breaking change. Extend the SpatieTagsColumn in your own project and override this behaviour if you wish.

**Comment by Saifallak** [comment]
maybe add `'*'` to pass to `->type()` ? to do this behaviour ?
because i think the normal is to get all tags
`->type` is there for filtering.


anyway, thanks for your efforts, i will extend it in my project for now.

**Comment by Saifallak** [comment]
hi @danharrin i saw this PR #7374 and it applied to form, if it was accepted for v3, maybe this PR can be accepted for V3 too?

**Pull request merged**
