### PR TITLE
make global search case-insensitive, and allow the search to run on all locales

### PR DESCRIPTION
**Pull request by AbanoubNassem**
fixes https://github.com/filamentphp/filament/discussions/4828

### CODE REVIEW

**Comment by AbanoubNassem** [comment]
just noticed , it broke the local `Resource` search , working on fixing that

**Comment by AbanoubNassem** [comment]
just noticed that the local `Resource` search , has same issue, working on fixing that as well.

**FIXED.**

**Comment by danharrin** [comment]
I've reverted the fix for tables because they should have a LocaleSwitcher anyway

**Comment by AbanoubNassem** [comment]
@danharrin 
> I've reverted the fix for tables because they should have a LocaleSwitcher anyway

we still have the same issues as there : https://github.com/filamentphp/filament/discussions/4828 , it's case sensitive as well. 

I believe, if we have a website with like 6 different locales , to keep switching the table locale to search, is not user friendly. Imagine a team of a company working together.

for individual/single owner websites, I see that they can switch the locale easily, because they know what they are doing , but in the scale of a company , this will not be the required behaviour.

I know this has its impact on performance , therefore if you are interested , I can work on implementing `scout` search capabilities, so we get the benefits of the indexed search.

**Comment by danharrin** [comment]
Scout can be integrated like this - https://filamentphp.com/docs/2.x/tables/getting-started#searching-records-with-laravel-scout

**Comment by danharrin** [comment]
I kinda agree now with the multi-locale search... what is the performance impact for searching 100,000 records?

**Comment by AbanoubNassem** [comment]
> 

@danharrin 

with 110600 records,  app in debug mode with `debugbar` attached , not optimised app, on Macbook Pro 2016:

```
//current implementation 

1 character (a) : 709ms
2 character (se) : 822ms
5 character (volup) : 810ms
2 words (Amsterdam Padova) : 905ms

-----------------------------------
// with the one I provided

1 character (a) : 660μs
2 character (se) : 1.34s
5 character (volup) : 1.37s
2 words (Amsterdam Padova) : 1.61s
```

so form what I see , it's not a huge impact , it works fairly well actually. 

from a normal user perspective ,I can't notice the performance impact.

**Comment by danharrin** [comment]
@zepfietje wdyt about these performance stats

**Comment by zepfietje** [comment]
Hmm, 180% duration is not something we should ignore. What's causing the slowdown specifically? The multi-language search?

**Comment by danharrin** [comment]
Yeah

**Comment by zepfietje** [comment]
Hard one. How would you toggle between locales for the global search if it didn't search for all locales by default?

**Comment by AbanoubNassem** [comment]
> Hard one. How would you toggle between locales for the global search if it didn't search for all locales by default?

@danharrin  @zepfietje 

I noticed something weird tho, global search , has no impact , performance is

```
1 character (a) : 294ms
2 character (se) : 369ms
5 character (volup) : 340ms
```

while I'm searching multiple tables , not one table like with resource-table search .

not really sure , why is that!?

**NOTE:** the performance stats , is not on global search it's on the resource-table search. the global search seems fine.

**Comment by zepfietje** [comment]
Thanks for clarifying @AbanoubNassem!

Maybe @danharrin could explain, since I haven't looked too deep into this part.

As for my question, there's a toggle above the table then, right?

**Comment by AbanoubNassem** [comment]
> Thanks for clarifying @AbanoubNassem!
> 
> Maybe @danharrin could explain, since I haven't looked too deep into this part.
> 
> As for my question, there's a toggle above the table then, right?

@zepfietje 

no there is not , it searches on the `$activeLocale = app()->getLocale();` , so it forces the app locale , no way to toggle/change it.

**Comment by danharrin** [comment]
Thats only for global search as far as I remember? Tables search respects the LocaleSwitcher

**Comment by AbanoubNassem** [comment]
> Thats only for global search as far as I remember? Tables search respects the LocaleSwitcher

it does respect the `LocaleSwitcher` but currently it lowers the column , not the input.

and on refresh I loses the LocaleSwitcher state, moreover I have 4 locales , to keep switching the locale to find the right locale which has the input is a bit cumbersome.

**Comment by danharrin** [comment]
We could make a function to store the locale in the session?

**Comment by AbanoubNassem** [comment]
> We could make a function to store the locale in the session?

hummm how about , if we make searching all locales optional? 
so by default it's false , but if you need it you can toggle it.

` public function applySearchConstraint(Builder $query, string $search, bool &$isFirst, bool $isIndividual = false, bool $searchAllLocales = false){}`

I think this would be a better approach, what do you think @danharrin  @zepfietje ?

**Comment by danharrin** [comment]
You can do it already by just overriding that method on the Livewire class. Extract it into a trait in your project if you want?

**Comment by AbanoubNassem** [comment]
> You can do it already by just overriding that method on the Livewire class. Extract it into a trait in your project if you want?

I can't , this is done on the `Column` -> `InteractsWithTableQuery`, I think you still confusing the `Column` search with `Global Search` , global search is working perfectly fine , it's the `Column` search now which has the issue.

**Comment by danharrin** [comment]
Oh right, you can override it using `->searchable(query: fn (Builder $query) => ...)` then

**Comment by AbanoubNassem** [comment]
> Oh right, you can override it using `->searchable(query: fn (Builder $query) => ...)` then

okey will do , thank you

**Comment by zepfietje** [comment]
This thread needs no further action then?

**Comment by danharrin** [comment]
i think so

**Pull request merged**
