### PR TITLE
Fix issue to remove table filters.

### PR DESCRIPTION
**Pull request by sumardi**
Fix issue to remove all filters with multiple `SelectFilter`.

### CODE REVIEW

**Comment by danharrin** [comment]
Hi, this fix looks wrong, and all of the tests are failing. Whats the issue?

**Comment by sumardi** [comment]
`Tables\Filters\SelectFilter` with relationship and `Tables\Filters\TrashedFilter` both have the same name of "value". Only 1 can be removed.

**Comment by sumardi** [comment]
Should use `$field->getId()` maybe?

**Comment by danharrin** [comment]
I've pushed the correct fix

**Comment by sumardi** [comment]
> I've pushed the correct fix

Tested and it fixes the issue. Thanks.

**Pull request merged**
