### PR TITLE
Add HasFontFamily in TextColumn

### PR DESCRIPTION
**Pull request by moskoweb**
Allows you to change the column font to Sans, Serif and Mono.

### CODE REVIEW

**Comment by zepfietje** [comment]
You can already achieve this by [passing extra attributes to the column](https://filamentphp.com/docs/2.x/tables/columns/getting-started#custom-attributes).

I think we might close this PR. Thoughts, @danharrin?

**Comment by moskoweb** [comment]
Changing color, size, alignment and weight can also add extra attributes, and it still has a method.

**Comment by zepfietje** [comment]
Yeah I know. I'm discussing internally what's the best way forward.

**Comment by pxlrbt** [comment]
I think we should have an easier way to add classes and reduce the helpers.

**Pull request merged**
