### PR TITLE
Fix RTL support for sidebar and icon badge

### PR DESCRIPTION
**Pull request by AAbosham**
- [x] Changes have been thoroughly tested to not break existing functionality.
- [ ] New functionality has been documented or existing documentation has been updated to reflect changes.
- [x] Visual changes are explained in the PR description using a screenshot/recording of before and after.

Before
image

After
image

### CODE REVIEW

**Comment by zepfietje** [comment]
Sorry for breaking those, @AAbosham, and thanks for fixing!
I've added the fix to buttons and links too.

What's going on with that pagination by the way?
Looks pretty broken that height.

**Comment by AAbosham** [comment]
I saw this, that this is for padding, i don't know why, 
I am trying to find the cause of this

image

its working well when change content width, so that have more spacing

image

**Comment by AAbosham** [comment]
This issue is Mozilla browser related, as it works fine on Chrome and Safari.

image

**Comment by zepfietje** [comment]
Hmm, weird that the padding is wrapping to a new line.

**Comment by zepfietje** [comment]
I can't reproduce the issue on Firefox on my Mac, so let me know if you've found a fix.

**Pull request merged**
