### PR TITLE
Feat: `CanBeCopied` copyText

### PR DESCRIPTION
**Pull request by Z3d0X**
- [x] Changes have been thoroughly tested to not break existing functionality.
- [ ] New functionality has been documented or existing documentation has been updated to reflect changes.
- [ ] Visual changes are explained in the PR description using a screenshot/recording of before and after.

### CODE REVIEW

**Comment by danharrin** [comment]
How about calling this feature "copyable state" (`copyableState()`, `getCopyableState()`), and also refactoring so that if `$this->copyableState` is null, we return `$this->getState()` from that `getCopyableState()` method. Then we can get rid of the `??` in the views.

**Comment by Z3d0X** [comment]
Can return type on `getCopyableState(): ?string`? since we are now doing  `?? $this->getState()`. Do u think we should remove the return type?

**Comment by danharrin** [comment]
The state could be null so I think the return type is fine

**Comment by danharrin** [comment]
Thanks

**Pull request merged**
