### PR TITLE
Saving the Active Tab in the LocalStorage

### PR DESCRIPTION
**Pull request by AlexisSerneels**
It allows to persist the Active Tab in the session rather than the Query String.
By simply adding ```->persistTabInSession()``` on the ```Tabs```field configuration.

**Why doing so?**
There is a current bug where the active tab resets to the first tab when switching locales using the `LocaleSwitcher` action
It happens because the query string is not sent  along with the Livewire`update` request, causing the active tab to always revert back to the first tab. As we do not have access to `update` request from the Tabs Component to include the Query Strings, we rely on the session instead.

The session name is dynamically generated based on the Filament Page Type, the associated Model's database table, and the Model's Primary Key. This ensures uniqueness and prevents conflicts between different sessions.

There is no visual change.

- [X] Changes have been thoroughly tested to not break existing functionality.
- [X] New functionality has been documented or existing documentation has been updated to reflect changes.
- [X] Visual changes are explained in the PR description using a screenshot/recording of before and after.

### CODE REVIEW

**Review by danharrin — CHANGES_REQUESTED** [review]
Instead of using the backend session store, let's use the local storage and Alpine's `$persist()`, identically to #7392

Should be much simpler

**Comment by AlexisSerneels** [comment]
I agree. Thank you for the tip.
Changes have been pushed.

**Review by danharrin — CHANGES_REQUESTED** [review]
Please also apply this for the Infolists Tabs component

**Comment by danharrin** [comment]
Also worth copying the wording in the docs for the Section persistCollapsed()

**Comment by AlexisSerneels** [comment]
I've:
- Added support for Infolist.
- Enabled Closure resolution.
- Allowed customization of the local storage name.
- Updated the documentation to ensure consistent wording.

**Comment by AlexisSerneels** [comment]
I've:

Added support for Infolist.
Enabled Closure resolution.
Allowed customization of the local storage name.
Updated the documentation to ensure consistent wording.

**Review by AlexisSerneels — COMMENTED** [review]
As requested, I've:

- Added support for Infolist.
- Enabled Closure resolution.
- Allowed customization of the local storage name.
- Updated the documentation to ensure consistent wording.

**Comment by AlexisSerneels** [comment]
I've fixed the imports, thereby resolving the failing tests.

**Pull request merged**
