### PR TITLE
Allow TextInputColumn to expand full width of table column

### PR DESCRIPTION
**Pull request by tanthammar**
## Description

- This PR makes all text input columns, expand full with of the table cell, by default. Which in my opinion is the expected behaviour.
- Using `TextInput::make('foo')->inline()`, disables full width.

I think I've tried every possible option to make a `TextInputColumn` expand full width of its table column.

```php
TextInputColumn::make('foo')->searchable()
            ->grow(),
            ->extraInputAttributes(['class' => 'w-full min-w-fit'])
            ->extraInputAttributes(['style' => 'width: 100%'])
            // and more...
```

## Visual changes

Before, no matter how I tried to expand the column width
image

After, just added ->grow() to the column
image

## Functional changes

- [ x ] Code style has been fixed by running the `composer cs` command.
- [ x ] Changes have been tested to not break existing functionality.
- [ x ] Documentation is up-to-date.

## Additional css suggestion

```css
/* auto grow width of table cell inputs to fit its content */
td.fi-ta-cell :is(input.fi-input), td.fi-ta-cell :is(select.fi-select-input) {
    field-sizing: content;
}
```

### CODE REVIEW

**Comment by danharrin** [comment]
@zepfietje wdyt about the additional suggestion? I think it's pretty smart, the way the text input column overflows is weird ATM I think. Prob also needs similar treatment on Select?

**Comment by zepfietje** [comment]
The field-sizing CSS API is amazing, but browser support isn't there yet unfortunately...
Been wanting to use that for our autosizing textarea too. 🥺

**Comment by danharrin** [comment]
Well it would use the existing behaviour if that property is not available, right? And at the moment we have no autosizing on input columns. So I guess it doesn't hurt?

**Comment by zepfietje** [comment]
Inconsistent behavior across browsers could still be a concern as devs/users may not be aware that the feature isn't supported on Firefox and Safari yet.

Apart from that, what would the UX be like exactly? Would the field grow in width when typing?

**Comment by tanthammar** [comment]
It would be great if you could accept the PR to solve the main purpose, to allow textInputColumns to expand full width of the cell. 

The additional css stuff can easily be added to local proj css for those who wants it. 
It does no harm. The browser simply ignores it.
And yes, it grows when typing.

**Comment by tanthammar** [comment]
Please consider adding min-widht: 125px (or something)  td.fi-ta-cell :is(input.fi-input), td.fi-ta-cell :is(select.fi-select-input) to prevent them form completely hiding its content.

**Comment by danharrin** [comment]
@zepfietje I'm happy to handle all this, but can you please approve the direction?
- Add `w-full` to `SelectColumn` too
- Add `min-w-48` to `TextInputColumn` and `SelectColumn`
- If the individual search inputs above columns don't have these classes, also add there

**Comment by zepfietje** [comment]
- `w-full` on the input doesn't grow the column, right?
- Could you share a screenshot of both the text input and select columns with `min-w-48`?
- I guess making the search inputs grow for columns that contain inputs is okay.

**Comment by danharrin** [comment]
It consumes the space in the column and doesn't grow the column

**Comment by zepfietje** [comment]
> It consumes the space in the column and doesn't grow the column

Sounds good.

**Comment by danharrin** [comment]
@zepfietje 

https://github.com/user-attachments/assets/9ba09a08-ca07-47a7-82b8-b4420474a91f

https://github.com/user-attachments/assets/7e9a24df-f52c-4b9a-af4b-df763c465082

**Comment by zepfietje** [comment]
Thanks, @danharrin.
How does it compare to the current behavior?

I'm afraid the width may be too opinionated and a breaking change.

**Comment by danharrin** [comment]
The current behaviour is that the columns can shrink to be the size of the label, and if the label is very short this can create an uncomfortable experience.

And it also means that inputs do not expand to be the full width of the cell even if the space is there.

**Pull request merged**
