### PR TITLE
Conditionally hide summaries

### PR DESCRIPTION
**Pull request by D-Jordy**
## Description
Adds a `CanBeHidden` trait to the `Summarizer` so they can be conditionally hidden in the same way a `Column` can

## Visual changes
none

## Functional changes

- [x] Code style has been fixed by running the `composer cs` command.
- [x] Changes have been tested to not break existing functionality.
- [x] Documentation is up-to-date.

### CODE REVIEW

**Review by zepfietje — CHANGES_REQUESTED** [review]
Are you sure you have run `composer cs`?
Seems like the Blade views aren't properly formatted.

Also, please document this feature as per the pull request template.

**Comment by D-Jordy** [comment]
done. my bad, prettier did not run.

**Comment by danharrin** [comment]
Visibility checks should be moved out of the view and into the getter method that returns the summaries for a column, you can return the filtered array

**Comment by D-Jordy** [comment]
done ^^

**Pull request merged**
