### PR TITLE
Add missing `ar` translations

### PR DESCRIPTION
**Pull request by mohamedsabil83**
- [ ] Changes have been thoroughly tested to not break existing functionality.
- [ ] New functionality has been documented or existing documentation has been updated to reflect changes.
- [ ] Visual changes are explained in the PR description using a screenshot/recording of before and after.

### CODE REVIEW

**Review by zepfietje — CHANGES_REQUESTED** [review]
Please revert all the translations you removed.

**Comment by mohamedsabil83** [comment]
Sorry, my bad

**Comment by zepfietje** [comment]
Thanks

**Comment by mohamedsabil83** [comment]
My pleasure

**Pull request merged**
