### PR TITLE
Update date-time-picker.js to use advancedFormat plugin for more flexible date formatting

### PR DESCRIPTION
**Pull request by bnzo**
## Description

Day.js advancedFormat plugin adds the ability to display ordinal suffix in the DateTimePicker.

This PR is associated with: https://github.com/danharrin/date-format-converter/pull/4

## Visual changes

Using a date format like `l jS F Y` will display the following:

Screenshot 2024-06-13 at 10 46 12

## Functional changes

- [x] Code style has been fixed by running the `composer cs` command.
- [x] Changes have been tested to not break existing functionality.
- [x] Documentation is up-to-date.

### CODE REVIEW

**Comment by danharrin** [comment]
Please update Composer to pull in the new version of the date formatting package

**Comment by danharrin** [comment]
Please also respond here with the difference in compiled JS size with the new Day.js dependency

**Comment by bnzo** [comment]
Size of date-time-picker.js

- Before: 99 230 bytes
- After: 100 348 bytes

**Comment by danharrin** [comment]
Thanks

**Pull request merged**
