### PR TITLE
Save records with BelongsTo relations using the relation name without having to set fillable in the model

### PR DESCRIPTION
**Pull request by johanzandstra**
## Description

When using Select fields with BelongsTo relations, we had to set the relation field (mostly a foreign key) as $fillable in the Model or had to set the whole Model as Unguarded. To protect this foreign key fields in other parts of the application we don't want to set these fields as fillable normally. 

Example:

The model `Project.php` has the relation company and only the  attribute `name` is set as fillable
```php
class Project extends Model
{

    protected $fillable = [
        'name',
    ];

    public function company(): BelongsTo
    {
        return $this->belongsTo(Company::class);
    }
}
```

The `ProjectResource` has the following form with a Select Field `company`
```php
    public static function form(Form $form): Form
    {
        return $form
            ->schema([
            Select::make('company_id')
                ->relationship(name: 'company', titleAttribute: 'name')
                ->preload()
                ->searchable(),
            TextInput::make('name')
                ->required(),
        ]);
    }
```

The Select field is using the relation registered in the model. In the current situation, when creating a new record using this example form and Model, would throw an Exception: `Add fillable property [company_id] to allow mass assignment on [App\Models\Project].`.

With minor changes to the CreateRecord and EditRecord, we are now able to save the records using Filament without the need to set the relation fields as $fillable.

For now, this implementation is using forceFill() to keep the implementation more simple. This will also fix the issue https://github.com/filamentphp/filament/issues/11204 as intended.

## Code style

- [x] `composer cs` command has been run.

## Testing

- [x] Changes have been tested.

## Documentation

- [x] Documentation is up-to-date.

### CODE REVIEW

**Comment by danharrin** [comment]
To be honest, this does feel like an overly complex solution to me. I understand the problem - you don't want to add the foreign key as fillable. That's fine. But in that case, Filament should probably just switch to using `forceFill()`, which would solve the problem in all cases. I don't see any issues with this since all the data we pass to the model is validated anyway.

**Comment by johanzandstra** [comment]
@danharrin forceFill() is an option too, but then we can't name the Select field using the relation name.
```            
Select::make('company')
                ->relationship(name: 'company', titleAttribute: 'name')
                ->preload()
                ->searchable(),
```
But we are forced to use the field name:
```            
Select::make('company_id')
                ->relationship(name: 'company', titleAttribute: 'name')
                ->preload()
                ->searchable(),
```

Next to that we are not using the Eloquent associate() method to associate the related model but just force the mass assignment to the model directly (what is some how bad practice in my opinion) and  that can  potentially expose the application to vulnerabilities.

I'm happy to change this implementation to a forceFill() implementation for the time being If you think that is the way to go for now btw.

**Comment by danharrin** [comment]
Naming the select field after the relation name (for BelongsTo at least) is not the guidance of the documentation, the docs should use the foreign key for this reason

What vulnerabilities are there in mass assignment if we are passing validated data only?

**Comment by johanzandstra** [comment]
I have updated the implementation to use the forceFill() as suggested for now.

There are no vulnerabilities in mass assignment using Filament so i don't see problems using mass assignment in this part of the application with validated data only.

**Comment by johanzandstra** [comment]
@danharrin thanks for taking care of the Actions and documentation too! Looks promising!

**Comment by mddickens** [comment]
I updated to 3.2.30 and my $guarded arrays are now ignored. I suspect this change is the root problem. Reverted to prior release and all works now.

**Comment by danharrin** [comment]
It's deliberate, please read our discussion. We only use validated data when passing to models.

**Comment by danharrin** [comment]
If you want to prevent a field from being saved, this option has been available since September 2021 as a feature of Filament - https://filamentphp.com/docs/3.x/forms/advanced#preventing-a-field-from-being-dehydrated

**Comment by danharrin** [comment]
To be honest, I think I'm going to revert this in the next release, it feels a little too risky for my liking if people were relying on guarded when they should have been using `dehydrated(false)`. It's user error, but I think we need to protect them in this case

**Comment by danharrin** [comment]
@johanzandstra you can override any of the methods we added in this PR / abstract to traits if you want to preserve that behaviour. Or make your foreign key fillable

**Comment by mddickens** [comment]
> It's deliberate, please read our discussion. We only use validated data when passing to models.
I saw that before, but in my case, I have a number of fields in my form that have no corresponding db column and need to be present in the data array, so I used the guarded array to block them from the generated SQL. Things like toggles whose values are used when creating or editing records.  If my problem is so unusual, I must not be using Filament correctly. Wouldn't be the first time, I think

**Comment by danharrin** [comment]
The idea is that everything in the resulting data array is saveable. But I think we will have to wait until v4 for this change.

**Comment by mddickens** [comment]
> The idea is that everything in the resulting data array is saveable. But I think we will have to wait until v4 for this change.

I get it now, but where I got confused and perhaps others have as well is that there are more than one "data" array.  There's the one in the parameter passed into mutateFormDataBeforeCreate/Edit, etc functions and there's the data object array at the component level. The data array you send to the function has apparently been copied from the component and stripped of the fields marked with dehydrated(false) so it can be saved as is, but if you use any of the field types for options that don't correspond with a database column, you have to refer to them with $this->data([]). A fine distinction which escaped my 67 year old brain back when I programmed the form in question.

**Comment by wychoong** [comment]
> Or make your foreign key fillable

This should be documented instead of applying `forceFill` for every v2~3 forms out there, it will make upgrading to v4 a difficult process (yes I know we should have tests)

Since Filament internal process of record creation and linking requires foreign key fillable, and only **validated foreign key** are filled by Filament 😉, it should be safe to just add that to $fillable. Userland code should validate the data anyhow or use the attach/associate.

**Comment by johanzandstra** [comment]
> The idea is that everything in the resulting data array is saveable. But I think we will have to wait until v4 for this change.

@danharrin I understand that the change has maybe more impact then initially thought. For now we will work around this in projects with the unguarded solution.
 
The forceFill() was not my initial idea but I wanted to go for the more complex attach/associate concept as @wychoong mentioned without breaking the existing fillable logics in models as I first proposed in https://github.com/filamentphp/filament/pull/11329/commits/89536107a332f99132b5e33b6996a118a71a5afe

**Comment by danharrin** [comment]
One option you can use in your panel provider is `->bootUsing(fn () => Model::unguard())` which only unguards models when the panel is being used

**Comment by skills-up** [comment]
@danharrin I was looking for the _right_ place to unguard the models instead of `app::boot()`, as my app has an admin panel interface using filament, as well as a regular mobile app where `Model::unguard()` is risky. Your comment finally answered it for me.

**Comment by CosmicodeStudio** [comment]
> One option you can use in your panel provider is `->bootUsing(fn () => Model::unguard())` which only unguards models when the panel is being used

This should be in the documentation, and not making developers add Model::unguard() everywhere. Some might not know the risk of doing that.

**Pull request merged**
