### PR TITLE
Add Progress Column

### PR DESCRIPTION
**Pull request by moskoweb**
I adapted the plugin created by @ryangjchandler to add the Progress column next to the Filament, I believe the column can be a standard feature of the Filament.

Credits: @ryangjchandler 
Plugin: https://github.com/ryangjchandler/filament-progress-column

### CODE REVIEW

**Comment by zepfietje** [comment]
What is the benefit of having this in core instead of as a plugin, @moskoweb?
I feel like it's perfect as a plugin, but not necessarily a core feature.

Thoughts, @danharrin @ryangjchandler?

**Comment by danharrin** [comment]
I agree with Zep 👍

**Comment by moskoweb** [comment]
Just as there are other columns in the Filament, I see it as being advantageous to make the Filament more and more complete, without depending on plugins that may be without updates in the future.

**Comment by danharrin** [comment]
The more features Filament has that not everyone uses, the larger the bundle and source size which is frankly uneconomical from a maintenance perspective or an efficiency perspective

**Comment by ryangjchandler** [comment]
@moskoweb You can make pull requests to plugins too, not everything _has_ to be in core. If you think something is missing from my package, open a pull request.

**Comment by zepfietje** [comment]
Oh and @ryangjchandler is a Filament core team member, so we'll make sure the package is updated. 😉

**Pull request closed without merging**
