### PR TITLE
Allow add header & footer for custom content modal

### PR DESCRIPTION
**Pull request by AAbosham**
Sometime you may need to add custom content on footer of modal.

image

### CODE REVIEW

**Comment by danharrin** [comment]
I think this should be simplified. Instead of using `modalContent()` again, we can introduce a new `modalFooter()` which is completely separate.

**Comment by AAbosham** [comment]
What about modalContent? Will rename to modalHeader?

If modal have footer, user think its have header

**Comment by danharrin** [comment]
`modalContent()` can stay as it is

**Comment by danharrin** [comment]
Thanks

**Pull request merged**
