### PR TITLE
tweak sidebar and breadcrumbs

### PR DESCRIPTION
**Pull request by awcodes**
Screen Shot 2022-12-28 at 9 05 11 AM
Screen Shot 2022-12-28 at 9 05 19 AM

### CODE REVIEW

**Comment by danharrin** [comment]
Thanks! looks great

**Comment by zepfietje** [comment]
Nice work, @awcodes!
What's the sidebar like when it's collapsed?

**Comment by awcodes** [comment]
Collapsed is the same as it was before. There was no reason to change any of that.

**Comment by zepfietje** [comment]
So it still has the white background?

**Comment by danharrin** [comment]
Yes

**Comment by awcodes** [comment]
it has to have the background on mobile since it's a slide out panel. :)

**Comment by zepfietje** [comment]
Yeah, just checking if it still has the background, since it should. Thanks guys! :)

**Pull request merged**
