### PR TITLE
Simple repeater [Object Object] fix

### PR DESCRIPTION
**Pull request by valpuia**
- [x] Changes have been thoroughly tested to not break existing functionality.
- [ ] New functionality has been documented or existing documentation has been updated to reflect changes.
- [x] Visual changes are explained in the PR description using a screenshot/recording of before and after.

Before:
Screenshot from 2023-10-03 16-54-56

After:
Screenshot from 2023-10-03 16-55-26

I have check a lot the use case of what I changed. I think this docs https://github.com/filamentphp/filament/blob/3.x/packages/forms/docs/03-fields/12-repeater.md?plain=1#L424 is the reason, but I never get like below data (from docs) in my database if I use simple repeater
```php
[
    'invitations' => [
        'dan@filamentphp.com',
        'ryan@filamentphp.com',
    ],
],
```
All I got is below, I stored in json column and casts as array
```php
[
    'dan@filamentphp.com',
    'ryan@filamentphp.com',
]
```
I think how it display in this docs is not actually how it store, suggest to remove if I am correct.

I may have missed others, if yes please tell me and I'll look more

### CODE REVIEW

**Comment by danharrin** [comment]
I don't think this is correct. In our example, `invitations` in the object represents the column in the database which stores the array - or the result of `getState()` on the form.

**Comment by danharrin** [comment]
Received more info - this is only caused by defaultItems()

**Comment by valpuia** [comment]
Yes, my changes cause error on edit, don't know why it's working (in my system) on yesterday :roll_eyes: 
I've check more and more, but cannot figure out how to solve this.. I'll just submit an issue (if none is report) for ref and close this.

**Comment by jdion84** [comment]
the reason your fix didn't work properly is because there are 2 places you need to fix inside the Repeater class, and you only did it in 1 place.

line 102 and line 543

**Pull request closed without merging**
