### PR TITLE
Added class to identify tables filters after/above content

### PR DESCRIPTION
**Pull request by howdu**

### CODE REVIEW

**Comment by zepfietje** [comment]
Hey, @howdu! Could you share some of the thinking behind this PR?
What would you need those hook classes for?

**Comment by howdu** [comment]
@zepfietje no worries. When the table filters are displayed above the table I wanted the 'Reset filters' to sit beside them. But do not want this behaviour in the standard dropdown. Currently no way of targeting this. 

Screenshot 2023-07-15 at 11 52 02
Screenshot 2023-07-15 at 11 52 30

Custom CSS added to achieve this:
```css
.filament-tables-filters-form {
    display: flex;
    justify-content: space-between;
    gap: 1rem;
}

.filament-tables-filters-form > .filament-forms-component-container {
    flex-grow: 1;
}

.filament-tables-filters-form > .filament-forms-component-container + div {
    flex-shrink: 0;
}
```

**Comment by zepfietje** [comment]
Thanks for clarifying, Ben.

There already exist classes on the filters form and dropdown:

- https://github.com/filamentphp/filament/blob/2.x/packages/tables/resources/views/components/filters/popover.blade.php
- https://github.com/filamentphp/filament/blob/2.x/packages/tables/resources/views/components/filters/index.blade.php

`filament-tables-filters` for dropdown, `filament-tables-filters-form` for the form.
Wouldn't it be possible to make it work using those classes?
Probably tricky without using CSS `has()`.

**Comment by howdu** [comment]
Cheers yeah this selector works. Happy for you to close if it's not needed. 
```:not(.filament-dropdown-panel) > .filament-tables-filters-form```

**Comment by zepfietje** [comment]
I came back to this issue to comment the exact selector you just commented, perfect! 😄

**Pull request closed without merging**
