### PR TITLE
Fix the next button not showing correctly in wizard form

### PR DESCRIPTION
**Pull request by Xoshbin**
- [ ] Changes have been thoroughly tested to not break existing functionality.
- [ ] New functionality has been documented or existing documentation has been updated to reflect changes.
- [ ] Visual changes are explained in the PR description using a screenshot/recording of before and after.

### CODE REVIEW

**Comment by danharrin** [comment]
What is this fixing? You haven't provided any description or screenshots.

**Comment by Xoshbin** [comment]
The PR title is very clear, and the code change is not big, I just added a missing color for a button.
Before:
Screenshot 2023-11-20 at 1 26 25 PM

After:
Screenshot 2023-11-20 at 1 26 01 PM

**Comment by danharrin** [comment]
"not showing correctly" is not clear in my opinion. The PR description even asks you for screenshots.

**Comment by danharrin** [comment]
As for the change itself, I don't think it's correct - the button should be primary.

I have tested 3.x myself and it works fine without this change:

Screenshot 2023-11-20 at 10 33 58

Please create a reproduction repository to I can investigate why it doesn't currently work for you. Otherwise, I will need to close this PR.

**Comment by Xoshbin** [comment]
I'm not using it in the admin panel, I use it in a Livewire component

**Comment by danharrin** [comment]
Something in your Tailwind setup is probably incorrect then

**Comment by Xoshbin** [comment]
hmm, it's a clean project i just installed breeze and Filamment, I will check it out.

**Comment by danharrin** [comment]
Make sure you are using the Filament Tailwind preset, and make sure you are using `@filamentStyles` in the layout.

**Comment by Xoshbin** [comment]
> Make sure you are using the Filament Tailwind preset, and make sure you are using `@filamentStyles` in the layout.

I'm very sure about these, but i need to investigate more.

**Comment by danharrin** [comment]
If you upload the repository I can take a look

**Comment by Xoshbin** [comment]
As i said it's very new project, I didn't upload it yet. If I couldn't find what is wrong i will create a new project installing Filament first then Breeze.

**Comment by Xoshbin** [comment]
I couldn't find the issue, so I uploaded it, you may check the repo.
https://github.com/Xoshbin/ftest

**Comment by danharrin** [comment]
You are missing the Tailwind Config preset https://filamentphp.com/docs/3.x/forms/installation#installing-tailwind-css

**Pull request closed without merging**
