### PR TITLE
Add to documentation: Move File to panel directory

### PR DESCRIPTION
**Pull request by mstfkhazaal**
https://github.com/filamentphp/filament/issues/7377

### CODE REVIEW

**Comment by danharrin** [comment]
I feel like this is not the right place, and really quite basic information that you should be able to understand if you're using multiple panels. The multi-panel docs explain that pages have their own directory and namespace, and the tenancy docs explain that this file can be put anywhere as long as it is registered correctly.

**Comment by bilogic** [comment]
I registered it as `->discoverPages(in: app_path('Filament/A/B/C/Pages'), for: 'App\\Filament\\A\\B\\C\\Pages')`, the page was able to load.

BUT I still faced `Unable to find component: [app.filament.a.b.c.pages.example]` only when `/livewire/update` was called to see if there are notifications.

**Comment by mstfkhazaal** [comment]
> I registered it as `->discoverPages(in: app_path('Filament/A/B/C/Pages'), for: 'App\\Filament\\A\\B\\C\\Pages')`, the page was able to load.
> 
> BUT I still faced `Unable to find component: [app.filament.a.b.c.pages.example]` only when `/livewire/update` was called to see if there are notifications.

Try `php artisan optimize`
Or `php artisan filament:optimize`
Or `composer dump-autoload`

**Comment by bilogic** [comment]
Already did that, however, the problem behaves a bit differently with and without `optimize`. 

Before I go further, my page has a `canAccess` method to check on the user's role and team using spatie/permission. (I'm also using the Teams feature)

So, if I optimize it, my page is able to load, however, it quickly shows a notification `You do not have permission to access` followed by redirecting to `/`

I added a log in my `canAccess` to dump out values. During calls to my page, `getPermissionsTeamId()` returns a numeric value, however during calls to `/livewire/update`, `getPermissionsTeamId()` returns `false`.

Maybe I should check with spatie.

**Pull request closed without merging**
