### PR TITLE
fix: Disable file replace

### LINKED ISSUE #6775: Replacing an image via drag-and-drop not working correctly
### Package

filament/filament

### Package Version

v2.17.48

### Laravel Version

v10.13.5

### Livewire Version

_No response_

### PHP Version

PHP 8.2.7

### Problem description

When dragging an image into an image field with an existing image, the image gets replaced and afterwards the fields get emptied.

https://github.com/filamentphp/filament/assets/10572554/0440c885-a038-4021-b532-8f6b820d2c30

### Expected behavior

The image should be correctly replaced.

### Steps to reproduce

1. Create a post in the Post resource, with an image inserted in the thumbnail field.
2. Drag another image in the thumbnail field.

### Reproduction repository

https://github.com/arjendejong12/filament-repo

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by danharrin**
- [x] Changes have been thoroughly tested to not break existing functionality.
- [x] New functionality has been documented or existing documentation has been updated to reflect changes.
- [x] Visual changes are explained in the PR description using a screenshot/recording of before and after.

Closes #6775.

### CODE REVIEW

**Comment by gursoykoc** [comment]
@danharrin  I think this update breaks ->imageEditor() functionality. When I upgrade filament to  >=3.1.10 versions, image editor stopped working after save edited image. When I downgrade filament to 3.1.9 it starts again. 
Also I tried to use file-upload.js?v=3.1.9 version on filament 3.1.12 imageEditor functionality works again.

**Comment by danharrin** [comment]
Can you please check if it works with multiple()?

**Comment by gursoykoc** [comment]
Yes it is working with ->multiple()

**Comment by danharrin** [comment]
Reverted this

**Pull request merged**
