### PR TITLE
Fixed the tippy console warning

### PR DESCRIPTION
**Pull request by TheDeadCode**
Tippy was showing this really annoying error, and the `$getCopyMessageDuration` variable was not working.

the bug

I fixed the bug and added edits to the library to properly calculate the timeout of the tooltip.

### CODE REVIEW

**Comment by zepfietje** [comment]
@TheDeadCode, why not fix this upstream in the package?

**Comment by TheDeadCode** [comment]
> @TheDeadCode, why not fix this upstream in the package?

That's what I was doing right now! I'll amend my commit if/when it's approved by upstream

**Comment by TheDeadCode** [comment]
[PR created](https://github.com/ryangjchandler/alpine-tooltip/pull/30)

**Comment by zepfietje** [comment]
@TheDeadCode, what's still to be done for this PR then?

**Comment by danharrin** [comment]
Nothing to do here really, the PR will fix

**Pull request closed without merging**
