### PR TITLE
Update indicator.blade.php - format $allSelectableRecordsCount

### PR DESCRIPTION
**Pull request by ericmp33**
## Description

With tables containing more than 999 records, the Number facade can be used to enhance the user experience by formatting the numbers.

## Visual changes

| Before                                                                                   | After                                                                                   |
|------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------|
| image | image |

## Functional changes

- [x] Code style has been fixed by running the `composer cs` command.
- [x] Changes have been tested to not break existing functionality.
- [x] Documentation is up-to-date.

### CODE REVIEW

**Comment by donatiss** [comment]
@danharrin 

Doesn't work with 119214 records. Locale is Lithuania.

**A non-numeric value encountered**

\Illuminate\Support\Number::format
```php
@return string|false
```

Helper function trans_choice:
```php
* @param  \Countable|int|float|array  $number
```

```php
if (! function_exists('trans_choice')) {
    /**
     * Translates the given message based on a count.
     *
     * @param  string  $key
     * @param  \Countable|int|float|array  $number
     * @param  array  $replace
     * @param  string|null  $locale
     * @return string
     */
    function trans_choice($key, $number, array $replace = [], $locale = null)
    {
        return app('translator')->choice($key, $number, $replace, $locale);
    }
}
```

**Comment by danharrin** [comment]
Does that locale use periods as a thousands separator?

**Comment by Saifallak** [comment]
Same error occurs with Arabic language formatting.  

You can see how to write thousands in Arabic from here: [https://chatgpt.com/share/6749f301-6564-8001-954a-373b6dc169b2](https://chatgpt.com/share/6749f301-6564-8001-954a-373b6dc169b2).  

Here are the screenshots for reference:

| Screenshot 1                                                                 | Screenshot 2                                                                 |
|------------------------------------------------------------------------------|------------------------------------------------------------------------------|
| Screenshot_20241129_185942_ChatGPT | Screenshot_20241129_190541_ChatGPT |

**Comment by danharrin** [comment]
#14924

**Pull request merged**
