### PR TITLE
Feature: XLSX format header row styling

### PR DESCRIPTION
**Pull request by shepard153**
## Description

This PR adds `CellStyle` class that allows users to style header row of the exported XLSX document by overriding the `getHeadingStyle()` method on the exporter class.

I'm not 100% sure about naming and implementation method so any suggestions are welcome.

- [X] Visual changes (if any) are shown using screenshots/recordings of before and after.
Example styling of headers:
image

## Code style

- [X] `composer cs` command has been run.

## Testing

- [X] Changes have been tested.

## Documentation

- [X] Documentation is up-to-date.

### CODE REVIEW

**Comment by danharrin** [comment]
Can you refactor this to remove the new CellStyle object, then people can just use the raw object from the original package, which should be much easier for us to maintain

**Comment by shepard153** [comment]
> Can you refactor this to remove the new CellStyle object, then people can just use the raw object from the original package, which should be much easier for us to maintain

Yes, of course. That was my original idea but I wasn't sure if you're ok with it. I'll add it in my next commit

**Comment by shepard153** [comment]
Should we add URL to the package docs? There is more about styling and `Style` object allows to add borders too.

[https://github.com/openspout/openspout/blob/4.x/docs/documentation.md#styling](https://github.com/openspout/openspout/blob/4.x/docs/documentation.md#styling)

**Comment by danharrin** [comment]
Thanks!

**Pull request merged**
