### PR TITLE
Feature: Async Alpine v2

### LINKED ISSUE #14353: Upgrade Async Alpine to v2
https://async-alpine.dev/docs/upgrade/

### PR DESCRIPTION
**Pull request by thethunderturner**
## Description

Closes #14353. This PR aims to upgrade async alpine to v2. This version of async alpine brings some breaking changes, and this PR of course aims to fix them as well ([upgrade guide](https://async-alpine.dev/docs/upgrade/#top)). 

At the moment I have refactored `ax-*` attributes. `x-ignore` is redundant in v2, so it should be removed as well. However, there is a critical issue. When opening a page with a table, the data loads fine, but when you paginate the cells are empty

https://github.com/user-attachments/assets/95936de4-61c0-4abf-af3e-7bd7a2ea6e04

The console errors exist on 4.x, so I doubt they are they issue
Im confident the errors appear only interactable cells. I spent a few hours trying to find the source of this error, but I couldnt. Maybe the core members know a bit more, and can help?

## Functional changes

- [ ] Code style has been fixed by running the `composer cs` command.
- [ ] Changes have been tested to not break existing functionality.
- [ ] Documentation is up-to-date.

### CODE REVIEW

**Comment by danharrin** [comment]
Some of the later versions of Async Alpine v1 also broke things, which is why it was locked to a specific version in `package.json`. I also have issues if I open a modal with async form components, close it, and then open a modal on a different table row.

**Comment by andrewdwallo** [comment]
@thethunderturner @danharrin Do you think the same issue that was fixed in #10982 could be relevant here? Have we tried using `x-load="visible"` instead here to see if it fixes it? It does look similar.

**Comment by thethunderturner** [comment]
> @thethunderturner @danharrin Do you think the same issue that was fixed in #10982 could be relevant here? Have we tried using `x-load="visible"` instead here to see if it fixes it?

Do you mean `x-load=visible` instead of just `x-load`?

**Comment by andrewdwallo** [comment]
> > @thethunderturner @danharrin Do you think the same issue that was fixed in #10982 could be relevant here? Have we tried using `x-load="visible"` instead here to see if it fixes it?
> 
> Do you mean `x-load=visible` instead of just `x-load`?

Yes, precisely. It's worth a try.

**Comment by thethunderturner** [comment]
> > > @thethunderturner @danharrin Do you think the same issue that was fixed in #10982 could be relevant here? Have we tried using `x-load="visible"` instead here to see if it fixes it?
> > 
> > 
> > Do you mean `x-load=visible` instead of just `x-load`?
> 
> Yes, precisely. It's worth a try.

Great idea! Unfortunately, it didnt help :/. So its something else...

**Comment by tareq-alqadi** [comment]
@thethunderturner Try locking Livewire to v3.5.11, which is before the Alpine.js x-ignore changes.

**Comment by thethunderturner** [comment]
> @thethunderturner Try locking Livewire to v3.5.11, which is before the Alpine.js x-ignore changes.

I thought about this too. I just don't have the time yet 😅. Thanks for letting me know

**Comment by danharrin** [comment]
I have pushed up a branch - `async-alpine`. It is based off of some of the commits in your branch. It appears to work well for me. I also unlocked Livewire. If you update Composer and use that branch, can you find any bugs? I don't think I can @thethunderturner @andrewdwallo

**Comment by thethunderturner** [comment]
> I have pushed up a branch - `async-alpine`. It is based off of some of the commits in your branch. It appears to work well for me. I also unlocked Livewire. If you update Composer and use that branch, can you find any bugs? I don't think I can @thethunderturner @andrewdwallo 

Nice, I was planning on unlocking livewire as well but I've been pretty busy. I will have a look when I get home this evening.

**Comment by thethunderturner** [comment]
@danharrin  Okay I had 10m, I checked it out and everything seems to be working for me. I checked forms, tables and modal actions. Im also pretty sure I have updated the documentation correctly, but feel free to have a second look yourself \:)

**Comment by thethunderturner** [comment]
Also, should we update to latest version of `async-alpine`? They pushed a fix regarding `x-ignore` [here](https://github.com/Accudio/async-alpine/releases/tag/2.0.1), and maybe latest of alpinejs? I tested them and I have no issues.

**Comment by danharrin** [comment]
Awesome, the branch did contain the latest version which I think was what fixed the issues. Thanks for your help!

**Comment by danharrin** [comment]
My branch was based half way off yours which is why I couldn't merge this PR, as it didn't include your WIP commit at the end

The only change I made was updating Async Alpine

**Comment by thethunderturner** [comment]
> My branch was based half way off yours which is why I couldn't merge this PR, as it didn't include your WIP commit at the end
> 
> The only change I made was updating Async Alpine

@danharrin Nice, but why werent my commits in the tree? I just checked the 4.x branch

**Comment by danharrin** [comment]
Hmm they are in the tree if you look back far enough

**Pull request closed without merging**
