### PR TITLE
Add decimal separator parameter for money mask

### PR DESCRIPTION
**Pull request by margarizaldi**

### CODE REVIEW

**Comment by danharrin** [comment]
Breaking change, but thank you

**Comment by margarizaldi** [comment]
Really? Hmmm... Never mind...

**Comment by danharrin** [comment]
Yes, what if people are already using that method and expect the parameters in that old order?

**Comment by margarizaldi** [comment]
OMG how can I forgot the order... Just because the docs give example with named params 🤣 Sorry...

**Pull request closed without merging**
