### PR TITLE
Support section footer actions

### PR DESCRIPTION
**Pull request by zepfietje**
## Description

Sections currently support header actions (https://github.com/filamentphp/filament/pull/9161), but don't support footer actions yet. This PR adds support for footer actions to the forms and infolists `Section` component as well as the section Blade component.

Replaces https://github.com/filamentphp/filament/pull/11457.

- [x] Visual changes (if any) are shown using screenshots/recordings of before and after.

## Code style

- [x] `composer cs` command has been run.

## Testing

- [x] Changes have been tested.

## Documentation

- [x] Documentation is up-to-date.

### CODE REVIEW

**Comment by devhoussam1998** [comment]
missing in blade components https://filamentphp.com/docs/3.x/support/blade-components/section

**Comment by zepfietje** [comment]
It's supported in fact, @devhoussam1998.
Section header and footer actions just haven't been documented there yet.

Feel free to create a PR already. 🙂

**Comment by reyespinosa1996** [comment]
Has this being released as part of v3.2 feature set? 
I'm being trying to use it in my current project as it appears to be already documented in the documentation website, but I'm getting the following error: Method Filament\Forms\Components\Section::footerActions does not exist.
Should I create a new issue with the bug report, or I'm missing something here (it's probably my fault btw)?

**Comment by zepfietje** [comment]
Please check your Filament version and create a bug report if you're still experiencing issues on the latest Filament version, @reyespinosa1996.

**Comment by reyespinosa1996** [comment]
It was a versioning issue, thank you for this awesome feature @zepfietje and everyone else who collaborate.

**Pull request merged**
