### PR TITLE
Support radio buttons and button group

### PR DESCRIPTION
**Pull request by zepfietje**
- [x] Changes have been thoroughly tested to not break existing functionality.
- [x] New functionality has been documented or existing documentation has been updated to reflect changes.
- [x] Visual changes are explained in the PR description using a screenshot/recording of before and after.

### Buttons (with `inline()`)

https://github.com/filamentphp/filament/assets/44533235/0413855e-5d17-4244-a045-42b1d752b488

### Button group

https://github.com/filamentphp/filament/assets/44533235/211ca6ae-acdc-458f-b2c5-b98a056987f7

### CODE REVIEW

**Comment by faizananwerali** [comment]
is it released or is it going to be released?

**Comment by zepfietje** [comment]
https://filamentphp.com/docs/3.x/forms/fields/toggle-buttons

**Comment by faizananwerali** [comment]
@zepfietje but in commits, this is mention in Readme.md file.

```php
Radio::make('status')
    ->buttonGroup()
    ->options([
        'draft' => 'Draft',
        'scheduled' => 'Scheduled',
        'published' => 'Published'
    ])
    ->colors([
        'draft' => 'warning',
        'scheduled' => 'info',
        'published' => 'success',
    ])
```

I like this because it also supports enum and I've so many Radio buttons in my project that I would have to replace it now wherever I need it. So I'm wondering if there is any reason this was not added or removed after adding because this commit has the code to make this work.

**Comment by danharrin** [comment]
The implementation was changed after. It still supports enums

**Pull request merged**
