### PR TITLE
Support groups in form select field

### PR DESCRIPTION
**Pull request by lukas-frey**
- [x] Changes have been thoroughly tested to not break existing functionality.
- [x] New functionality has been documented or existing documentation has been updated to reflect changes.
- [x] Visual changes are explained in the PR description using a screenshot/recording of before and after.

This PR adds the ability to group options in selects using optgroups.

The syntax is simple:
```php
Select::make('status')
    ->options([
        'In Process' => [
            'draft' => 'Draft',
            'reviewing' => 'Reviewing',
        ],
        'published' => 'Published',
    ])
```

Which will render the following:

image

or with searchable / multiple:

image

Known issues:
- When the Select is set as searchable() and you search something, the groups are not persisted until the search string is empty again. This is a limitation of choices.js (see https://github.com/Choices-js/Choices/issues/926)

### CODE REVIEW

**Comment by lukas-frey** [comment]
Resubmitted, merging from an organisation's fork doesn't allow granting maintainers edit rights.

**Comment by danharrin** [comment]
Thanks! This is pretty awesome, didn't know it could be this easy

**Comment by JonoB** [comment]
@lukas-frey  - this is great, thank you! Any reason why you didn't target `SelectColumn` as well?

**Comment by lukas-frey** [comment]
> @lukas-frey  - this is great, thank you! Any reason why you didn't target `SelectColumn` as well?

Thanks! No reason, I just never used `SelectColumn` so it didn't even come to mind :)

**Comment by andrewdwallo** [comment]
It would be beneficial if both grouped and ungrouped options could function within the same select element as well.

**Pull request merged**
