### PR TITLE
fix: Layout overflow on extra small screen size

### PR DESCRIPTION
**Pull request by lam0819**
Fix Layout overflow issue
image

### CODE REVIEW

**Comment by zepfietje** [comment]
Hey @lam0819! Coul you share a screenshot of how this PR fixes the issue? 🙂

**Comment by lam0819** [comment]
after fix 
image

an unusual case, but figure it out on the Samsung Fold phone

**Comment by danharrin** [comment]
This isnt a fix, it destroys grid columns in < md

**Comment by lam0819** [comment]
But it handles all small to iPad mini size , or what is better approach?
image
image

**Comment by danharrin** [comment]
Now try adding a second column to sm screen sizes and see how there is absolutely no spacing any more...

I dont know what the solution is

**Pull request closed without merging**
