### PR TITLE
Adding the option to set modal width on the Select components createOption and editOption functionality

### PR DESCRIPTION
**Pull request by abishekrsrikaanth**
Modal width option for `createOption` and `editOption` on the Select Component

### CODE REVIEW

**Comment by zepfietje** [comment]
You can customize the action with `createOptionAction(function ($action) => $action)`.
Since we're not planning to add proxies for all action modal methods, I'm closing this PR.

**Comment by abishekrsrikaanth** [comment]
> You can customize the action with `createOptionAction(function ($action) => $action)`. Since we're not planning to add proxies for all action modal methods, I'm closing this PR.

Can you please clarify how this method works? I don't see an example, may be I can document it and send a PR for that.

**Comment by zepfietje** [comment]
You simply get full control over the actual action object.
Use it like any other action in the actions package: https://beta.filamentphp.com/docs/3.x/actions/overview.

**Comment by danharrin** [comment]
I've just documented that

**Comment by oybek-daniyarov** [comment]
I will add there in case if anyone search for it

```php
Forms\Components\Select::make('customer_id')
                                    ->relationship('customer', 'name')
                                    ->createOptionForm(UserFormFields::getFields())
                                    ->createOptionAction(function (Forms\Components\Actions\Action $action) {
                                        $action->action(fn (array $data, CreateUserAction $createUserAction) => $createUserAction->handle($data));
                                    })
                                    ->required()
                                    ->placeholder('Select a customer'),
                                Forms\Components\Textarea::make('meta.comments')
                                    ->rows(3)
                                    ->placeholder('Add any comments here')
                                    ->nullable()
```

**Pull request closed without merging**
