### PR TITLE
Queue auth email notifications

### PR DESCRIPTION
**Pull request by bensherred**
- [x] Changes have been thoroughly tested to not break existing functionality.
- [x] New functionality has been documented or existing documentation has been updated to reflect changes.
- [ ] ~Visual changes are explained in the PR description using a screenshot/recording of before and after.~ - No visual changes

---

This PR updates the auth email notifications to queue by default.

### CODE REVIEW

**Comment by danharrin** [comment]
@bensherred I think we should just queue by default, probably. Adding a configuration option for this might be a little overkill. People can always override this and use their own class by binding it to the container if they want.

**Comment by zepfietje** [comment]
Totally agree.

**Comment by bensherred** [comment]
Okay perfect, that sounds like a good plan to me. I’ll update this PR to set the default notifications to queue.

**Comment by zepfietje** [comment]
Perfect,  @bensherred.
Please let us know when you're done by marking this PR as ready for review. 🙂

**Comment by bensherred** [comment]
@danharrin @zepfietje this has been updated to now queue the emails by default

**Comment by danharrin** [comment]
Thanks

**Pull request merged**
