### PR TITLE
Add support for underline in RichEditor

### PR DESCRIPTION
**Pull request by arjendejong12**
This PR adds underline functionality to the RichEditor form field.

### CODE REVIEW

**Comment by danharrin** [comment]
Please send a screenshot of what this new button looks like next to the others

**Comment by arjendejong12** [comment]
Like the other icons in the Rich Editor, this one is also from the Font Awesome Solid icon library.

image

**Comment by danharrin** [comment]
Thanks

**Comment by arjendejong12** [comment]
Thank you for merging this PR and adding in pieces of code I missed.

**Pull request merged**
