### PR TITLE
Auth classes rate limit notification method

### PR DESCRIPTION
**Pull request by olehasoft**
## Description

Move the rate limit notification code into a separate method to make it easier to extend the authentication method of the Login class.

## Functional changes

- [ ] Code style has been fixed by running the `composer cs` command.
- [x] Changes have been tested to not break existing functionality.
- [ ] Documentation is up-to-date.

### CODE REVIEW

**Review by danharrin — CHANGES_REQUESTED** [review]
Please copy the implementation of `getCreatedNotification()` on CreateRecord, where the notification is still sent by the parent class if null is not returned. This allows easier fluent customisation of the notification without needing to redefine the entire method.

It should be `getRateLimitedNotification()`

Also please check other instances of rate limited notifications to implement this on consistently.

**Comment by olehasoft** [comment]
@danharrin thank you for your attention!

Implemented `getRateLimitedNotification()` method, also added `getRateLimitedNotificationTitle()` and `getRateLimitedNotificationBody()` methods.

I decided that it would be better to pass `TooManyRequestsException` from now on, because its other properties might be useful.

Also `TooManyRequestsException` already has public `$this->minutesUntilAvailable = ceil($this->secondsUntilAvailable / 60)` so I used that instead of repeating.

**Comment by olehasoft** [comment]
If I implemented correctly, should I add similar changes to this PR for the other `Filament\Pages\Auth` classes: `Register`, `PasswordReset`, `RequestPasswordReset`, `EmailVerificationPrompt`?

In this case, I additionally suggest transferring everything to the `HasRateLimitedNotification` trait with property like this:
```php
protected string $rateLimitedNotificationTranslateBaseKey = 'filament-panels::pages/auth/login.notifications.throttled';
```

**Comment by danharrin** [comment]
Thank you @olehasoft. `getRateLimitedNotificationTitle()` and `getRateLimitedNotificationBody()` can probably be merged into the main function, they are there for backwards compatibility on the other components. That should make it easier to apply to the other pages :)

**Comment by olehasoft** [comment]
@danharrin merged into one `getRateLimitedNotification()` method with code as close as possible to the original.

Although it always returns `Notification`, because `__('filament-panels::pages/auth/login.notifications.throttled.title')` will never return `null`, I left the `?Notification` return declaration for use in extending.

If this meets your requirements, I suggest applying the solution to all the `Filament\Pages\Auth` classes I mentioned above.

**Comment by danharrin** [comment]
Looks perfect, so its ready to be copied to the other classes. Thanks!

**Comment by olehasoft** [comment]
@danharrin all done, thanks!

**Review by danharrin — APPROVED** [review]

**Comment by danharrin** [comment]
Thank you for your patience with this review

**Pull request merged**
