### PR TITLE
Document text and badge column `enum()` deprecation 

### PR DESCRIPTION
**Pull request by MORA99**
BadgeColumn deprecation

- [x] Changes have been thoroughly tested to not break existing functionality.
- [x] New functionality has been documented or existing documentation has been updated to reflect changes.
- [x] Visual changes are explained in the PR description using a screenshot/recording of before and after.

### CODE REVIEW

**Comment by zepfietje** [comment]
We don't document APIs that have been marked deprecated but are still available as it's not a breaking change.

**Comment by MORA99** [comment]
Well if you are using the enum badge from v2 documentation it is a breaking change,
I had to track down the source file to find the deprecation comment "@deprecated Use `TextColumn` with the `badge()` method instead."

https://filamentphp.com/docs/2.x/tables/columns/badge
`use Filament\Tables\Columns\BadgeColumn;
 
BadgeColumn::make('status')
    ->enum([
        'draft' => 'Draft',
        'reviewing' => 'Reviewing',
        'published' => 'Published',
    ])`

After upgrade

`
Method Filament\Tables\Columns\BadgeColumn::enum does not exist.
`

**Comment by danharrin** [comment]
Please clarify that the `enum()` method has been removed then in the docs. There is a replacement by the way, but I haven't documented it yet.

**Comment by zepfietje** [comment]
If you mark the PR as ready for review when done, we'll be notified to merge, @MORA99. 🙂

**Comment by MORA99** [comment]
I have clarified that the enum function was removed, and added one possible workaround, since I dont know if theres a more elegant way planned :)

**Comment by zepfietje** [comment]
Probably want to document this here too https://github.com/filamentphp/filament/issues/7122.

Handing this over to you, @danharrin.

**Pull request merged**
