### PR TITLE
add pagination overview to mobile

### PR DESCRIPTION
**Pull request by cobraprojects**
add pagination overview on top of pagination

image

### CODE REVIEW

**Comment by zepfietje** [comment]
From a design perspective I think we shouldn't try to fit in the count. Feels really crowded. Also, look at how Tailwind UI handles it on mobile (they hide the count): https://tailwindui.com/components/application-ui/navigation/pagination.

I do sometimes find myself wanting to view the count on mobile though. Any other ideas?

**Comment by cobraprojects** [comment]
Can we make it optional?
like we have
```php
protected function isTablePaginationEnabled(): bool 
{
    return false;
} 
```


we could do somthing like

```php
protected function showCountOnMobile(): bool 
{
    return true;
} 
```

we can make the default value `false`

or may be an option in the config file

**Comment by zepfietje** [comment]
We could potentially make it opt-in yeah, but then we'd still need to find a proper design.

**Comment by zepfietje** [comment]
@danharrin @awcodes, what do you think? There's no matching Tailwind UI design for this and I feel like it gets too crowded on mobile.

**Comment by danharrin** [comment]
Yeah honestly I don't like it but I feel bad closing PRs lol

**Comment by zepfietje** [comment]
There's no sense in keeping it open then. I can close it for you. 😅

No but seriously, I feel like it's probably better to hold off on this for now.

**Comment by danharrin** [comment]
Thanks for making the decision for me. And thanks for the PR @cobraprojects

**Comment by cobraprojects** [comment]
No worries, we all looking for the best

**Pull request closed without merging**
