### PR TITLE
Add tenant menu to top nav if activated

### PR DESCRIPTION
**Pull request by chrisbaswell**

### CODE REVIEW

**Comment by chrisbaswell** [comment]
Screenshot 2023-07-26 at 10 21 30 AM

**Comment by zepfietje** [comment]
The tenant menu not showing when using top navigation is a known limitation.
I don't think we should just put it next to the user menu though.

Probably we should refactor the tenant and user menus to take action objects instead of menu items. We could then make the tenant menu an item in the user menu dropdown.

**Comment by chrisbaswell** [comment]
The tenant menu being displayed beside the user menu makes it clear what tenant you're using without having to click anything.  This is consistent with how the tenant menu is displayed in the sidebar nav.

**Comment by zepfietje** [comment]
The sidebar has a lot of available space vertically, hence the tenant menu is shown by default. The top bar however, doesn't have the space to show the tenant menu on smaller screens. This PR would make it impossible for users to access the tenant menu on those devices.

**Comment by chrisbaswell** [comment]
Currently, when top navigation is enabled, all the navigation including the tenant menu is contained in the collapsible sidebar on smaller screens.  This PR only shows the tenant menu on desktop screens.  It hides the tenant menu on smaller screens since it's already contained in the collapsible sidebar nav.

**Comment by chrisbaswell** [comment]
This is the current behavior.  The PR just adds the tenant menu to the top bar on larger screens.

Screenshot 2023-07-26 at 2 00 57 PM

Screenshot 2023-07-26 at 2 01 38 PM

**Comment by zepfietje** [comment]
> Currently, when top navigation is enabled, all the navigation including the tenant menu is contained in the collapsible sidebar on smaller screens. This PR only shows the tenant menu on desktop screens. It hides the tenant menu on smaller screens since it's already contained in the collapsible sidebar nav.

Good point. Sorry I missed that. I guess my mind is just too busy finishing v3 at the moment. 😅

**Comment by chrisbaswell** [comment]
No worries.  I'll try to help with some issues as I have time.

**Comment by dbpolito** [comment]
Hah, just faced this issue... i was about to create a PR with this exact code and came in my mind to search on issues before i open it... hah...

For now i just published `resources/views/vendor/filament-panels/components/topbar/index.blade.php` and added this... so not a blocker to anyone, just some investigation needed to workaround it.

I think having it in there, even if it doesn't look ideal is better than just not having at all...

**Comment by aeq-dev** [comment]
Also if it's possible to make it searchable :)
Thanks

**Comment by zepfietje** [comment]
Implemented in https://github.com/filamentphp/filament/commit/17f241e29e6d841631c782edcb3cde69e7da27b9.
Thanks for your patience, folks!

**Comment by dbpolito** [comment]
@zepfietje you didn't add the `filament()->hasTopNavigation()` check, won't it show twice when using the sidebar nav?

**Comment by zepfietje** [comment]
No, because the parent is wrapped in that conditional.

**Pull request closed without merging**
