### PR TITLE
remove multiple dropdown arrows

### LINKED ISSUE #11521: Improve Choices.js select field appearance while script is loading
### Package

filament/filament

### Package Version

3.2.35

### Laravel Version

10.3.3

### Livewire Version

3.4.6

### PHP Version

8.3

### Problem description

There's a pretty jarring visual glitch when using non-native select fields. This is what is shown while the field is loading:

image

It's very noticable for people on slow connections. See this video: https://www.youtube.com/watch?v=Ruax9OpgDmU

I understand that the js is lazy loaded (and that's great) but I think there should be a better placeholder while the field is still loading. Currently UI looks broken for several seconds for people on slow connections. It's also an issue when the server is far away from the user (eg. Australia -> Germany) regardless of connection speed. 

The large white box with the dropdown arrow that shows while the field is loading isn't clickable either, which is even more confusing for users.

### Expected behavior

Non-native select fields should have some kind of placeholder while Choices.js is loading to prevent them from looking broken.

### Steps to reproduce

1. Launch the reproduction repository
2. Open the browser and throttle the connection to 2G
3. Clear the browser cache, then open the create product page

The select will look broken for a few seconds.

### Reproduction repository

https://github.com/binaryfire/filament-reproduction-repo

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by valentin-morice**
## Description

Remove the multiple dropdown arrows from placeholder select, as mentioned in  #11521

## Visual changes

Screenshot from 2024-03-28 18-30-44
*Before*

Screenshot from 2024-03-28 18-30-49
*After*

## Functional changes

- [X] Code style has been fixed by running the `composer cs` command.
- [X] Changes have been tested to not break existing functionality.
- [X] Documentation is up-to-date.

### CODE REVIEW

**Comment by danharrin** [comment]
Thanks

**Comment by zepfietje** [comment]
Why is there both `bg-transparent` and `!bg-none` now?

**Comment by valentin-morice** [comment]
@zepfietje `bg-transparent` is compiled down to `background-color: transparent`, while `!bg-none` is `background-image: none`. 
The transparent background is meant to respect the dark/light theme preference, while `bg-none` removes the dropdown arrow, which is generated as a css background image.

image

[bg-none](https://tailwindcss.com/docs/background-image)
[bg-transparent](https://tailwindcss.com/docs/background-color)

**Comment by zepfietje** [comment]
Thanks for confirming my assumption, @valentin-morice!

**Pull request merged**
