### PR TITLE
fix: tabs not updating in Builder #5639

### PR DESCRIPTION
**Pull request by alex552**

### CODE REVIEW

**Comment by danharrin** [comment]
Hey, so how does this fix work? Why do we need an ID?

**Comment by alex552** [comment]
Hi Dan,  forms::components.tabs doesn't have an id by default or a wire:key, that's why this bug was happening on refresh.

**Comment by danharrin** [comment]
I don't think it should have an ID then, let's add a wire:key in the view

**Comment by danharrin** [comment]
Thanks

**Pull request merged**
