### PR TITLE
Fix #13531

### LINKED ISSUE #13531: Gray toggle button
https://github.com/filamentphp/filament/assets/41773797/6dbf92e2-ba16-49a7-b1e1-21b75438278d

### PR DESCRIPTION
**Pull request by vienman1990**
## Description

Add css for Gray toggle button

## Visual changes

Screen Shot 2024-07-14 at 0 28 57

## Functional changes

- [x] Code style has been fixed by running the `composer cs` command.
- [x] Changes have been tested to not break existing functionality.
- [ ] Documentation is up-to-date.

### CODE REVIEW

**Comment by danharrin** [comment]
Thanks! Can you please post a dark mode screenshot?

**Comment by vienman1990** [comment]
@danharrin 

Sorry for late reply.

Screen Shot 2024-07-16 at 22 17 15

**Comment by danharrin** [comment]
Do you think this should be a little darker in dark mode? Otherwise I think it sticks out quite a bit

**Comment by danharrin** [comment]
Maybe have a look for other elements with the same background and text color and see what they use in dark mode

**Comment by vienman1990** [comment]
fix color in dark mode.

Screen Shot 2024-07-17 at 23 43 46

**Comment by danharrin** [comment]
Perfect, thank you!

**Pull request merged**
