### PR TITLE
Prioritize custom routes over the defaults

### PR DESCRIPTION
**Pull request by margarizaldi**
- [x] Changes have been thoroughly tested to not break existing functionality.
- [ ] New functionality has been documented or existing documentation has been updated to reflect changes.
- [ ] Visual changes are explained in the PR description using a screenshot/recording of before and after.

Move down all custom routes after the default routes to enable route overriding.

### CODE REVIEW

**Comment by danharrin** [comment]
Isn't this the reverse of #7810 which fixed an issue?

**Comment by danharrin** [comment]
Please investigate that issue and provide more information if you would like me to merge this

**Comment by margarizaldi** [comment]
> Please investigate that issue and provide more information if you would like me to merge this

I've checked and tested the problem of #7809 and now I can see the dilemmatic situations since the "global" routes (login, logout, register, etc.) are placed at the same level with the tenant slug[^1].

However, the fix #7810 came with a drawback that avoided us to override any default routes. The best option I can think so far is stick to the current version, close this PR, and enable customizations for all global routes.

[^1]: To be honest, I'm not the fan of this route structure, it requires us to list some "reserved words" if the tenant slug is a meaningful string (yeah, we're building a SaaS for customers, so we would never expose the tenant id in the url). If possible I will move my tenant routes to a sub path like `/u/{tenant}/path`.

**Comment by danharrin** [comment]
Please suggest how you want to achieve customisation of global routes, as you mention

**Comment by margarizaldi** [comment]
> Please suggest how you want to achieve customisation of global routes, as you mention

Basically I want to be able to override the default routes so we need to put the custom routes at the end. But then it creates another issue making tenant routes being inaccessible. So since this is not critical to my current projects, I won't think too much for that currently.

**Pull request closed without merging**
