### PR TITLE
Add A image lightbox in imageColumn

### PR DESCRIPTION
**Pull request by lam0819**
- [x] Changes have been thoroughly tested to not break existing functionality.
- [x] New functionality has been documented or existing documentation has been updated to reflect changes.
- [x] Visual changes are explained in the PR description using a screenshot/recording of before and after.

In this pull request,
Our goal is to introduce a basic image lightbox functionality without incorporating any extra libraries.
For a more sophisticated image lightbox effect or if additional libraries are desired, the use of an additional filament plugin is recommended.
Upon clicking an image within the imageColumn, a lightbox popup will be displayed.
image

### CODE REVIEW

**Comment by zepfietje** [comment]
Honestly, I think this would be better suited as a plugin.
Also, you could simply attach an action to the column already and have it open a modal that shows the image.

Going to close this, but will notify @danharrin for a final decision.

**Comment by wychoong** [comment]
> could simply attach an action to the column already and have it open a modal

would like to see this lightbox implementation in the core, a modal with static content (eg: an image or announcement) without a server request

**Comment by lam0819** [comment]
ya, my target is simple lightbox in image. for other attachments, eg pdf , i think need additional plugin.

**Comment by lam0819** [comment]
@wychoong 

Since it will not merge into core function, i make a package to do this now. 
Keep base on ImageColumn and TextColumn.
Support Image , PDF, Word, PPTX too.

Enjoy 

https://github.com/solutionforest/Filament-SimpleLightBox

**Pull request closed without merging**
