### PR TITLE
Restore v2 docs

### PR DESCRIPTION
**Pull request by assertchris**
Folks still using Filament v2 will run into issues if they follow the v3 instructions, so this serves as a resource for them. It should be introduced alongside the new website docs versioning work.

- [x] Changes have been thoroughly tested to not break existing functionality.
- [x] New functionality has been documented or existing documentation has been updated to reflect changes.
- [x] Visual changes are explained in the PR description using a screenshot/recording of before and after.

### CODE REVIEW

**Comment by assertchris** [comment]
@danharrin Not super familiar with the API changes to this package. Just going off the changes I had to make to get it to work in a v2 app.

**Comment by danharrin** [comment]
@assertchris we can probably just get links to the docs from the 2.x branch of this repo, instead of duplicating them

**Comment by danharrin** [comment]
oh, just remembered they are split over multiple files. on the 2.x branch, we should combine them all in to one README

**Comment by assertchris** [comment]
Ah, yes of course! I feel so stupid.

**Comment by danharrin** [comment]
oh, just remembered they are split over multiple files. on the 2.x branch, we should combine them all in to one README

**Pull request closed without merging**
