### PR TITLE
Fix table grouping headers

### PR DESCRIPTION
**Pull request by sumardi**
- [x] Changes have been thoroughly tested to not break existing functionality.
- [x] New functionality has been documented or existing documentation has been updated to reflect changes.
- [x] Visual changes are explained in the PR description using a screenshot/recording of before and after.

Before:
Screenshot 2023-07-21 at 7 53 04 PM

After:
Screenshot 2023-07-21 at 7 52 24 PM

### CODE REVIEW

**Comment by zepfietje** [comment]
I'm failing to see how this change fixes the issue.
Could you elaborate?

**Comment by sumardi** [comment]
> I'm failing to see how this change fixes the issue. Could you elaborate?

I can't think a better explanation. Maybe there is better approach. But this approach avoiding livewire v3 injecting morph markers, maybe because it is variable not public method.

**Comment by sumardi** [comment]
https://github.com/livewire/livewire/discussions/5844

**Comment by zepfietje** [comment]
Thanks for clarifying, @sumardi!

Ugh, seems like the Livewire regex doesn't match the method calls while it does match variables..?

@danharrin, what should we do here?

**Comment by danharrin** [comment]
We need to make a failing test for Livewire otherwise it wont be fixed

**Comment by zepfietje** [comment]
Agree, can you take that on, since you've done it before, @danharrin?

**Comment by danharrin** [comment]
livewire/livewire#5972

**Pull request closed without merging**
