### PR TITLE
Feature: Add expand/collapse all events to collapsible rows

### PR DESCRIPTION
**Pull request by oddvalue**
This PR adds some events to the collapsible table rows to allow implementing an expand/collapse
 all button via an action.

### CODE REVIEW

**Comment by danharrin** [comment]
Thank you for the work, but I don't think this feature is going to be used by enough people to warrant the extra code complexity, and it doesn't really fit within our existing table layout, especially on mobile.

**Comment by oddvalue** [comment]
> Thank you for the work, but I don't think this feature is going to be used by enough people to warrant the extra code complexity, and it doesn't really fit within our existing table layout, especially on mobile.

Completely understand that. Could I persuade you to at least include the events on the collapsible rows so that it could be implemented with an action?

**Comment by danharrin** [comment]
Yeah sure, you can add event listeners if you wish

Edit this PR to remove everything else then mark it as ready for review

**Comment by danharrin** [comment]
Thanks

**Pull request merged**
