### PR TITLE
New field: Slider from nouislider

### PR DESCRIPTION
**Pull request by thethunderturner**
## Description

As requested in #12728, this feature was targeted for a 4.1 release. I decided to get a jumpstart on it.
Using the nouislider JS plugin, I have added it to core. This PR contains most important features of the plugin, made for filament.

However there is one plugin issue, and that's the `noui-tips` div overlapping with the footer actions. This is probably something the team has to decide how to fix though :sweat_smile: 

Furthermore, as shown in the docs: [here](https://refreshless.com/nouislider/slider-values/#section-step), you can have an extra div where you can pass the value of the slider. Do we want to add that or use hint/helperText?

I have created a "short" video demonstrating the plugin in action :)

I know that the team is very busy with developing v4 atm, and since I dont want my work to go to "waste". Should I rewrite it for v4, or wait until its out?

P.S.: I'm going to write the documentation for it after the code has been finalized an approved by core team members

## Visual changes
https://youtu.be/PYVtQ7KwDuc

## Functional changes

- [ ] Code style has been fixed by running the `composer cs` command.
- [x] Changes have been tested to not break existing functionality.
- [ ] Documentation is up-to-date.

### CODE REVIEW

**Comment by zepfietje** [comment]
Thanks for working on this, @thethunderturner!
Next time, please ask us before working on this, because [we're no longer accepting new features for v3](https://github.com/filamentphp/filament/discussions/13744).

The slider field is planned for Filament v4.1, so we're not planning to review or build it before that time as other v4.0 features need our time first. Hopefully you understand. 🙂

**Comment by thethunderturner** [comment]
> Thanks for working on this, @thethunderturner!
> Next time, please ask us before working on this, because [we're no longer accepting new features for v3](https://github.com/filamentphp/filament/discussions/13744).
> 
> The slider field is planned for Filament v4.1, so we're not planning to review or build it before that time as other v4.0 features need our time first. Hopefully you understand. 🙂

Hey! As I mentioned in the PR, I know that the team is busy with v4 at the moment. Should I remake the PR for v4, such that it's reconsidered then? Should I wait until it out?

Thanks :)

**Comment by zepfietje** [comment]
Since the slider feature is planned for v4.1 (not v4.0) we won't get to it before v4.1.
I'd rather you create a PR after v4.0 is out because it'll only be work to keep the PR updated until v4.1. Does that make sense to you? :)

**Comment by thethunderturner** [comment]
> Since the slider feature is planned for v4.1 (not v4.0) we won't get to it before v4.1. I'd rather you create a PR after v4.0 is out because it'll only be work to keep the PR updated until v4.1. Does that make sense to you? :)

Yess, Thank you

**Comment by ziming** [comment]
@thethunderturner thank you for this PR, would you be open to make this into a package? Thank you

Since 4.1 might be weeks away

**Comment by thethunderturner** [comment]
> @thethunderturner thank you for this PR, would you be open to make this into a package? Thank you

This is targeted for 4.1 actually. So I will make a PR for it when 4.x stable is released. In other words it will be added to core filament :)

**Pull request closed without merging**
