### PR TITLE
Support circular cropping

### PR DESCRIPTION
**Pull request by jason-beach**
This pull request extends the edit image cropping feature allowing for circle cropping by adding a ->circleCropper() method on the FileUpload component. For example,

```php
use Filament\Forms\Components\FileUpload;
 
FileUpload::make('image')
    ->image()
    ->imageEditor()
    ->circleCropper()  // new proposed method
```

Updates have been made in the file-upload.js to handle the circle cropping, for example, when cropping a .jpg the conversion to a .png happens to handle the alpha transparency needed for a resulting circle image.

Screenshot 2023-09-27 at 3 49 35 PM

Additional updates have been made to the CSS to create a circle bounding box for visual purposes when circleCropper() is enabled.

Screenshot 2023-09-27 at 3 49 27 PM

- [x] Changes have been thoroughly tested to not break existing functionality.
- [x] New functionality has been documented or existing documentation has been updated to reflect changes.
- [x] Visual changes are explained in the PR description using a screenshot/recording of before and after.

### CODE REVIEW

**Comment by danharrin** [comment]
Please fix the assets, `npm run build`

**Comment by jason-beach** [comment]
@danharrin , 

I wanted to manage my expectations for this to be merged in to the next release as I have a project that I desperately need this feature in by the 12th of Oct. which is my deadline. I'm not too familiar with your release process so I was curious if I need to work off a fork for this or do you have plans on merging this in by then? Thanks!

**Comment by danharrin** [comment]
Have you seen the existing `avatar()` method? I don't know if this is worth the complexity, when this is all possible with CSS rounding too

**Comment by jason-beach** [comment]
@danharrin , 

Of course, I took a closer look at the Avatar feature, even though it's not officially documented. I gave it a shot anyway and found that there does seem to be an "avatar" method available. However, it's a bit limited because it only crops images into a square shape. The circular appearance you mentioned is limited to the canvas itself - and makes sense if I wanted to show a circle avatar in an application digitally.

My specific requirement is to be able to crop images into both **circular** and **oval** shapes, which is crucial for my client's printing needs. They want images that can fit nicely onto circular and oval canvases.

So, while Avatar does have some related functionality, it doesn't fully meet my needs as it doesn't directly support the cropping of images into circular or oval shapes for final printing.

**Comment by saade** [comment]
> @danharrin ,
> 
> Of course, I took a closer look at the Avatar feature, even though it's not officially documented. I gave it a shot anyway and found that there does seem to be an "avatar" method available. However, it's a bit limited because it only crops images into a square shape. The circular appearance you mentioned is limited to the canvas itself - and makes sense if I wanted to show a circle avatar in an application digitally.
> 
> My specific requirement is to be able to crop images into both **circular** and **oval** shapes, which is crucial for my client's printing needs. They want images that can fit nicely onto circular and oval canvases.
> 
> So, while Avatar does have some related functionality, it doesn't fully meet my needs as it doesn't directly support the cropping of images into circular or oval shapes for final printing.

But if you have a square shaped image, can't you clip it into a circle before printing?
idk if you're printing from `cmd+p` from the browser or generating a PDF, but either way you can achive a circular avatar using css/ image manipulation. IMO its weird cropping images round since not cropping it, fits multiple use cases instead of a circular one.


Take Github (and many other social medias) for example, you don't see your avatar showing as a square anywere, most of them shows your avatar as a circle, but the underlaying image is always a square

**Comment by jason-beach** [comment]
>But if you have a square shaped image, can't you clip it into a circle before printing?

We did consider that but it wasn't well received.

I think it would be best user experience practice to show the actual shape of the circle or oval they are cropping with to achieve the precision they need for print b/c if you don't the cropping experience itself can be confusing when attempting to create a circular or oval crop while seeing a square or rectangular bounding box, which adversely impacts the user experience. This was well received during initial prototyping...

In our specific use case, we are tasked with printing a variety of shapes, including ovals, circles, squares, and rectangles, onto a 4x6 card. Users then need to be able to print and cut these shapes accurately to fit specific canvas sizes.

Introducing a feature that enables users to visualize and select the appropriate bounding box for circles and ovals during the cropping process would likely be well-received. Additionally, allowing users the flexibility to clip an image as a circle or oval for printing, even though it's a departure from typical web usage like Github or social media, aligns with our unique use case and the specific needs of our users.

It doesn't seem like there would be significant technical complexity in implementing this feature, and it could indeed enhance the usability of your application for your target audience or at least provide them an option to do so. In general, we are allowing to see the circle/oval bounding box and allowing the ability to crop as a circle/oval using what's already there with the file-upload component.

I'd like to reiterate that our use case is exclusively focused on printing and does not involve the typical usage of **avatars** for web applications which is already available but not documented for v3.

**Comment by danharrin** [comment]
Does this work when FileUpload multiple() is enabled

**Comment by jason-beach** [comment]
@danharrin , 

Here's a screenshot with it working with multiple() enabled:

image

**Comment by danharrin** [comment]
I just don't know, it feels like we are straying away from Filepond and Cropper.js quite alot, and it's not something I feel comfortable in maintaining, as I really couldn't tell you how it works.

**Comment by upwebdesign** [comment]
@danharrin, although somewhat disappointed, we respect your decision not to include this update in your core package at this time. Because we are in a time crunch, we will use our fork until a final decision is made.

We need help integrating our fork with our changes into our project. You have excellent instructions on how to do this locally to make changes, but there are errors when using our `dev-feature/circle-cropper` branch. The errors stem from using a VCS repository and dev dependencies. Below are segments of our `composer.json` file and the error we are receiving.

Any guidance would be greatly appreciated!

```json
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/codegreencreative/filament"
        }
    ],
    "require": {
        "php": "^8.1",
        "filament/filament": "dev-feature/circle-cropper"
    }
}
```

The error that occurs is as follows.

```
  - Upgrading filament/filament (3.x-dev 8c16d22 => dev-feature/circle-cropper 79d785b): Extracting archive
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

   Error 

  Class "Livewire\Component" not found
```

**Comment by upwebdesign** [comment]
@danharrin, we were able to figure this out on our own. Thanks again for your consideration of this PR.

**Comment by danharrin** [comment]
Hi, thanks for the PR. I think it's important to give you a bit of information as to why this PR has been tagged as "low priority". We really appreciate all contributions, and intend to visit this in the future, and hopefully merge it if it is a suitable feature for the framework.

However, reviewing PRs, and often rewriting them on behalf of the author to ensure they are consistent with the rest of the framework, consumes a lot of my time. At the moment we have a large backlog of bug reports that I am prioritising, since most of these affect functionality that worked in a previous version and are now impacting real projects. Hopefully you can see how that work comes first before introducing new features that people aren't using in projects yet.

Again, thank you for contributing and I'm looking forward to reviewing this PR when our backlog of bug reports has reduced.

**Comment by danharrin** [comment]
Thanks

**Comment by zepfietje** [comment]
I just pushed a couple improvements to 3.1:
https://github.com/filamentphp/filament/commit/1dcf2413562d914bebdf8727139d28ff4349e2c8
https://github.com/filamentphp/filament/commit/8974280fbd40c6f92ffc18563995da7a31c00700

Generally prefer using Tailwind classes with `@apply`, and `outline-none` should improve accessibility.

One final thing. Could you tell me where you got the hardcoded color value from for the box-shadow, @jason-beach @danharrin?

**Comment by jason-beach** [comment]
@zepfietje , I believe the hardcoded color was the default blue color from [cropper.js](https://fengyuanchen.github.io/cropperjs/)

**Comment by zepfietje** [comment]
So non-circular cropping uses the exact same CSS?
Sorry if I'm missing info, as I haven't really touched this feature yet.

**Comment by jason-beach** [comment]
@zepfietje , if you're referring to the color for the bounding box - originally the cropper already has a color. So it may be that you don't need to define it again for the circle cropper.

**Comment by zepfietje** [comment]
Just pushed removal of that line to 3.1.
Could you pull it in and test if everything still works as expected, @jason-beach @danharrin?

**Comment by jason-beach** [comment]
@zepfietje ,

I've noticed a small issue with this feature involving the CSS.

When using the circle cropper and applying an aspect ratio, for example, 18:25 for the cropper, the circle/oval doesn't make a complete circle/oval due to the fact that the css is using `@apply rounded-full;` which is essentially: `border-radius: 9999px;`. This doesn't complete the full "Oval" in this case as shown below:
image

If you update the CSS to use `border-radius: 50%;` it works as expected with using cropping ratios as show below:
image

Here's the full updated CSS for `file-upload.css`:
`.fi-fo-file-upload-circle-cropper .cropper-view-box,
.fi-fo-file-upload-circle-cropper .cropper-face {
    border-radius: 50%;
}`

`border-radius: 9999px;` is great when working with inputs and buttons but we'll need to use `border-radius: 50%` as we are dealing with circles.

If you could make an update for that, everything else seems to test and work as expected.

Cheers!

**Comment by danharrin** [comment]
Please open a PR

**Comment by jason-beach** [comment]
#10706 created.

**Pull request merged**
