### PR TITLE
Support navigation group URL

### PR DESCRIPTION
**Pull request by saade**
[Retargeted] https://github.com/filamentphp/filament/pull/9395

- [x] Changes have been thoroughly tested to not break existing functionality.
- [x] New functionality has been documented or existing documentation has been updated to reflect changes.
- [x] Visual changes are explained in the PR description using a screenshot/recording of before and after.

This PR adds support for using `->url()` in navigation groups. Using settings as example, using `->url()` in navigation group can redirect me to a page showing all settings available, whereas each navigation item can redirect me to a specific setting.

- If no `->url()` is used, the current collapsible behavior is preserved.
- If `->url()` is used, only the chevron can toggle the group collapsed state.

https://github.com/filamentphp/filament/assets/14329460/3339d08b-3f80-4a6f-b672-be130daadbb1

### CODE REVIEW

**Comment by danharrin** [comment]
Hi, thanks for the PR. I think it's important to give you a bit of information as to why this PR has been tagged as "low priority". We really appreciate all contributions, and intend to visit this in the future, and hopefully merge it if it is a suitable feature for the framework.

However, reviewing PRs, and often rewriting them on behalf of the author to ensure they are consistent with the rest of the framework, consumes a lot of my time. At the moment we have a large backlog of bug reports that I am prioritising, since most of these affect functionality that worked in a previous version and are now impacting real projects. Hopefully you can see how that work comes first before introducing new features that people aren't using in projects yet.

Again, thank you for contributing and I'm looking forward to reviewing this PR when our backlog of bug reports has reduced.

**Comment by danharrin** [comment]
@saade I'm interested in adding this to the 3.1 release, are you planning to reopen?

**Comment by saade** [comment]
@danharrin f..k, i've re-forked the filament repo and forgot about this PR, yes, i can reopen it. Should i target the 3.x branch again?

**Comment by danharrin** [comment]
Please target 3.1 :)

**Comment by saade** [comment]
@danharrin https://github.com/filamentphp/filament/pull/9395

**Pull request closed without merging**
