### PR TITLE
allow absolute URL as avatar

### LINKED ISSUE #242: Avatar component does not accept a full image URL
**Describe the bug**
If `\App\Models\User::getFilamentAvatar()` return s a full URL - for example a Gravatar, Unavatar or similar service URL - the avatar blade component prepends the already absolute URL with the app URL.

**Expected behavior**
It should render the `` tag with the given full URL.

**Screenshots**
Bildschirmfoto 2021-03-18 um 17 50 33

**Fix**

Add another condition to the `\Filament\View\Components\Avatar::src()` method.

```php
if (Str::startsWith($avatar, ['http://', 'https://'])) {
    return $avatar;
}
```

### PR DESCRIPTION
**Pull request by Gummibeer**
fixes #242

### CODE REVIEW

**Comment by danharrin** [comment]
Hey, should we try `filter_var($avatar, FILTER_VALIDATE_URL)` here instead?

**Comment by danharrin** [comment]
Also, I feel like this fix should be dealt with in `get_image_url()`?

**Comment by Gummibeer** [comment]
It has to be a combination as `ftp://ftp.example.com/image.jpg` is a valid URL.

**Comment by danharrin** [comment]
Thank you!

**Pull request merged**
