### PR TITLE
Fix Octane

### LINKED ISSUE #7922: User registration does not work with Email verification + Octane Server
### Package

filament/filament

### Package Version

v3.0.27

### Laravel Version

10.19.0

### Livewire Version

v3.0.0-beta.9

### PHP Version

PHP 8.2.9

### Problem description

An exception occurs when registering an account using the Filament register page + `MustVerifyEmail` + octane server.

### Expected behavior

The registration works normally with the verification email sent and redirected to the verify email page.

### Steps to reproduce

- Clone example repository
- Setup .env variables
- php artisan migrate
- php artisan octane:start (Important! Bug only happens with octane server)
- Try to register an account using the register page `admin/register`

### Reproduction repository

https://github.com/miguilimzero/filament-email-verification-bug-example

### Relevant log output

image

### LINKED ISSUE #7969: Filament Sidebar not working correctly with Multi-tenancy + Octane server
### Package

filament/filament

### Package Version

v3.0.30

### Laravel Version

v10.19.0

### Livewire Version

v3.0.0-beta.10

### PHP Version

PHP 8.2.9

### Problem description

There are currently two different problems depending on which Octane adapter you're now using:

### Swoole
If you have more than one tenancy and switch between them, the sidebar link will not update accordingly. Example:

- I'm on team ID 1
- Now I switched to team ID 2
- The post resource sidebar link will still point to team ID 1

This happens randomly. Sometimes it updates the links correctly, sometimes not. Most of time the bug will appear.

### Roadrunner
If you keep refreshing the page, the sidebar resources will appear and disappear randomly.

**I could only reproduce at the beginning. I don't know if it was a fault on my side. However, the Swoole issue is easily reproducible.**

### Expected behavior

Everything works seamlessly.

### Steps to reproduce

- Download the example repository
- php artisan migrate
- Set the octane runner you want to test using `OCTANE_SERVER` (Swoole)
- Start the local server with `php artisan octane:start`
- Register your user
- Create team 1 and then create team 2

### Reproduction repository

https://github.com/miguilimzero/filament-tenant-octane-bug-example

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by danharrin**
Fixes #7922. The only option was to make a breaking change, avoiding the Registered event and sending our notification without a listener.

Fixes #7969. Panel objects were being shared between requests as they were being instantiated from register(). A closure is now used to instantiate a new panel each time FilamentManager is resolved.

Replaces #8664.

### CODE REVIEW

**Comment by archilex** [comment]
Another positive side effect of wrapping the panel in a closure is that `auth()->user()` is now available inside the panel! Prior to this PR you had to use a policy if you wanted to conditionally hide/show/enable/disable a panel method because trying to use something like `auth()->user()->isAdmin()` would throw a `Target class [hash] does not exist` exception. Not anymore! 🎉

**Comment by danharrin** [comment]
Hmm, I'm pretty sure auth()->user() will still be unavailable because that is set in middleware?

But yeah, the hash facade should exist now

**Comment by lamberttraccard** [comment]
@danharrin I have just been bitten by this fix and breaking change 😥. How can we hook into user registration now?

**Comment by danharrin** [comment]
UserObserver sounds like the current easiest way

**Comment by lamberttraccard** [comment]
It would trigger for every user creation, not only the one made during registration. Would you be open to a PR that adds a FilamentRegistered event?

**Comment by danharrin** [comment]
`Filament\Events\Auth\Registered`

**Comment by lamberttraccard** [comment]
https://github.com/filamentphp/filament/pull/10727

**Pull request merged**
