### PR TITLE
Switch to Bunny Fonts Provider by default

### PR DESCRIPTION
**Pull request by Jubeki**
I found no place where the font will be changed depending on the config, therefor I simply made the changes necessary to have Bunny Font the Default one.

### CODE REVIEW

**Comment by zepfietje** [comment]
Could you revert de docs changes? These are still the v2 docs and will be updated before v3 launches anyway. Rest looks good to me.

@danharrin, Laravel also uses Bunny Fonts instead of Google Fonts as the default these days, so makes sense.

**Comment by zepfietje** [comment]
@Jubeki, mark as ready for review when you've reverted the docs.

**Comment by Jubeki** [comment]
I have reverted the docs.

**Comment by zepfietje** [comment]
Perfect, thanks. Waiting for @danharrin to merge.

**Comment by Muzicant** [comment]
**Issue: Sorting in Filament Table Keeps Loading Overlay Active**
**Context:**
1. Using Filament Admin Panel (v3.2) with Livewire (v3.5.12).
2. The table is built using Filament Tables, and sorting is enabled for multiple columns (e.g., "contact" and "category").

**Problem:**
When clicking on a column header to trigger sorting, the following happens:
1. The screen darkens, and a loading overlay appears.
2. After sorting is completed, the overlay does not disappear, leaving the screen blocked.
3. Sorting works correctly (confirmed via browser inspection), but the overlay remains active indefinitely.

**What I've checked:**

- Livewire hooks (message.processed) do not seem to trigger or are not functioning as expected after sorting.
- Tried hiding the overlay via JavaScript and CSS (manually removing .fi-modal-close-overlay), but this does not work reliably.
- Livewire is locked to v3.5.12, as per recommended compatibility.
- The issue exists both in local development and on production servers.
- Config settings in config/filament.php have been checked, but no relevant setting controls the loading overlay behavior.

**Expected Behavior:**

- Once sorting is completed, the loading overlay should disappear automatically, allowing interaction with the table again.
- Alternatively, the overlay should at least be removed once the Livewire request finishes.

**Additional Notes:**

- The issue occurs only when sorting a Filament table.
- Other Livewire components do not seem to have this problem.
- Manually removing the overlay (via browser inspector) reveals that sorting actually works fine—only the overlay remains stuck.
- No JavaScript errors appear in the browser console.

**Question:**
How can this issue be resolved or worked around?
Is this a known issue with Livewire & Filament's table sorting behavior?
Would downgrading/upgrading Livewire or Filament help in fixing this?

```
"require": {
    "php": "^8.2",
    "filament/filament": "^3.2",
    "laravel/framework": "^11.31",
    "laravel/tinker": "^2.9",
    "livewire/livewire": "3.5.12"
}
```

```
 Environment ......................................................................................................................................
  Application Name ......................................................................................................................... Laravel
  Laravel Version .......................................................................................................................... 11.41.3
  PHP Version ............................................................................................................................... 8.2.27
  Composer Version ........................................................................................................................... 2.8.5
  Environment ................................................................................................................................ local
  Debug Mode ............................................................................................................................... ENABLED
  Maintenance Mode ............................................................................................................................. OFF
  Timezone ..................................................................................................................................... UTC  
  Locale ........................................................................................................................................ en

  Cache ............................................................................................................................................
  Config ................................................................................................................................ NOT CACHED
  Events ................................................................................................................................ NOT CACHED
  Routes ................................................................................................................................ NOT CACHED
  Views ..................................................................................................................................... CACHED

  Drivers ..........................................................................................................................................
  Broadcasting ................................................................................................................................. log
  Cache ................................................................................................................................... database
  Database ................................................................................................................................... mysql
  Logs .............................................................................................................................. stack / single
  Mail ......................................................................................................................................... log
  Queue ................................................................................................................................... database
  Session ................................................................................................................................. database

  Filament .........................................................................................................................................
  Blade Icons ........................................................................................................................... NOT CACHED
  Packages ......................................................................................... filament, forms, notifications, support, tables
  Panel Components ...................................................................................................................... NOT CACHED
  Version ................................................................................................................................. v3.2.136
  Views .............................................................................................................................. NOT PUBLISHED

  Livewire .........................................................................................................................................
  Livewire ................................................................................................................................. v3.5.12

```

**Pull request merged**
