### PR TITLE
Update Login.php -> function authenticate()

### PR DESCRIPTION
**Pull request by FilipeNSV**
## Description

This pull request adds a session flush right after the authentication credentials are successfully verified. This ensures that any previous session data is cleared, enhancing session security and preventing conflicts. The session is regenerated to establish a new session ID for the authenticated user.

## Visual changes

No visual changes.

## Functional changes

- Added `session()->flush()` after successful authentication to clear old session data.

## Checklist

- [x] Code style has been fixed by running the `composer cs` command.
- [x] Changes have been tested to not break existing functionality.
- [ ] Documentation is up-to-date.

### CODE REVIEW

**Comment by malzariey** [comment]
In most cases, you need to store data in the session before login and process it after login.

**Comment by FilipeNSV** [comment]
It's true, but I believe it's important to clean the session after checking
credentials, before login. In my app, I had some problems with this. It's
just a simple suggestion, for me, I believe works better.

Em sex., 13 de set. de 2024 às 05:17, Majid Al Zariey <
***@***.***> escreveu:

**Comment by danharrin** [comment]
This is a breaking change for anyone relying on data set before login.

Also, neither Breeze nor Jetstream/Fortify do this, so I'm prepared to say it's not a best practice according to Laravel.

You can always change the behaviour by overriding this method on the login page in your panel.

**Comment by FilipeNSV** [comment]
Thank you so much for clarifying and taking the time to respond. I now
have a better understanding and truly appreciate your insights.

Em sex., 13 de set. de 2024 às 18:35, Dan Harrin ***@***.***>
escreveu:

**Pull request closed without merging**
