### PR TITLE
Get form state before rate limiter so the form is validated

### PR DESCRIPTION
**Pull request by pxlrbt**
Currently the rate limiter kicks in before the form is validated so you have to wait a whole minute if some input is invalid. In case of password validation this is really frustrating.

### CODE REVIEW

**Comment by zepfietje** [comment]
Isn't that the whole point of rate limiting login attempts?

**Comment by pxlrbt** [comment]
Okay, probably the login one was too much, but I don't want to rate limit users on registration if they haven't entered a valid password, right? 😅

**Comment by zepfietje** [comment]
I think all those rate limiters where correct originally.
The problem with registration now is that users can check if an account exists for an email without being rate limited.

**Comment by pxlrbt** [comment]
Hm, we should at least increase the limit to 5 then. Otherwise you enter a password, it says "please enter at least X digits" you enter a new password and are rate limited 🤔

**Comment by zepfietje** [comment]
Agree. Maybe also change the decay to 30 seconds instead?

**Comment by danharrin** [comment]
I agree that it was correct before.

**Comment by zepfietje** [comment]
What about the number of tries though, @danharrin?

**Comment by danharrin** [comment]
I think it should depend on the page. I think we can safely increase it to 2 on the registration page, but not on login.

**Comment by zepfietje** [comment]
But then you'd have to wait an entire minute when you accidentally type 1 character of your email address wrong..?

**Comment by danharrin** [comment]
Okay lets do 2 for all forms then

**Pull request merged**
