### PR TITLE
Add Latvian translations for support, forms and notifications

### PR DESCRIPTION
**Pull request by CreepPork**
Adds Latvian translations currently only for support, forms and notifications.

### CODE REVIEW

**Comment by zepfietje** [comment]
Is this ready to be reviewed, @CreepPork?

**Comment by CreepPork** [comment]
@zepfietje It is now. I hadn't translated some of the support ones. Now it's fixed.

**Comment by zepfietje** [comment]
Thanks!

Would you like to be appointed translation manager for Latvian?
If so, send a message in our Discord channel: https://discord.com/channels/883083792112300104/1016289001394684016. 🙂

**Comment by CreepPork** [comment]
@zepfietje Thanks, sure! Sadly though, the invite doesn't work for me.

**Comment by zepfietje** [comment]
Oh sorry, it was a direct link to the channel instead of invite: https://filamentphp.com/discord. Head over to the localization channel.

**Pull request merged**
