### PR TITLE
Remove secondary color

### PR DESCRIPTION
**Pull request by zepfietje**
- [x] Changes have been thoroughly tested to not break existing functionality.
- [x] New functionality has been documented or existing documentation has been updated to reflect changes.
- [x] Visual changes are explained in the PR description using a screenshot/recording of before and after.

Secondary color is optional, so no need to keep the key since we support adding custom named colors now anyway.

### CODE REVIEW

**Comment by zepfietje** [comment]
This is ready to be merged, @danharrin.

**Comment by danharrin** [comment]
I need to think about the BC consequences before I do

**Comment by zepfietje** [comment]
Sure.

**Comment by danharrin** [comment]
Since we have a rector for this, I think we're ok?

**Comment by zepfietje** [comment]
> Since we have a rector for this, I think we're ok?

Yeah, the new `secondary` color concept was only something we added in v3.

**Pull request merged**
