### PR TITLE
Support image URLs as icon

### PR DESCRIPTION
**Pull request by SebastiaanKloos**
As mentioned the option to add an image as icon

### CODE REVIEW

**Comment by SebastiaanKloos** [comment]
Ohh sorry @zepfietje I just noticed you marked it as draft

**Comment by zepfietje** [comment]
Wanted to tweak it a little. Can you test if it still works as expected?

**Comment by SebastiaanKloos** [comment]
@zepfietje thanks! Yeah looks way better. It still works 🚀

**Comment by zepfietje** [comment]
Awesome! 🚀
Ready for final review and merge by @danharrin.

**Comment by SebastiaanKloos** [comment]
You are amazing @zepfietje. Looking good. Love how it works

**Pull request merged**
