### PR TITLE
Allow spatie/invade 2.x

### PR DESCRIPTION
**Pull request by balu-lt**
- [ ] Changes have been thoroughly tested to not break existing functionality.
- [ ] New functionality has been documented or existing documentation has been updated to reflect changes.
- [ ] Visual changes are explained in the PR description using a screenshot/recording of before and after.

Trying to keep packages up to date.
Based on the `spatie/invade` [v2 change log](https://github.com/spatie/invade/releases/tag/2.0.0) it should be fine.

### CODE REVIEW

**Comment by danharrin** [comment]
Check the usages, I know for sure this will break one of them, where we use `->reflected` I think

**Comment by danharrin** [comment]
Mark this as ready when you've fixed that

**Comment by danharrin** [comment]
Not been tested properly, and not fixed with the breaking changes associated with v2 of that package. So reopen this PR when it is complete please.

**Comment by hamrak** [comment]
#9660

**Pull request closed without merging**
