### PR TITLE
feature: Filter modal

### PR DESCRIPTION
**Pull request by danharrin**
- [x] Changes have been thoroughly tested to not break existing functionality.
- [x] New functionality has been documented or existing documentation has been updated to reflect changes.
- [x] Visual changes are explained in the PR description using a screenshot/recording of before and after.

Screenshot 2023-10-23 at 11 28 31

Screenshot 2023-10-23 at 11 28 19

### CODE REVIEW

**Comment by zepfietje** [comment]
@danharrin I feel like close should be "Apply", though that would be confusing since the filters are automatically applied... What do you think?

**Comment by danharrin** [comment]
You're correct, it would be confusing. When we introduce a deferred filter feature, then we can introduce that instead.

**Comment by zepfietje** [comment]
Sounds good!

**Comment by imperiumbee** [comment]
Amazing! 
@danharrin Could you tell when are deferred filters expected?

**Comment by danharrin** [comment]
We don't have a date, you can PR it but previous PRs have failed due to unclear UX, so be prepared for a long review process

**Comment by imperiumbee** [comment]
What about #5116 ? Logic seems clear, or not?
there can add a confirmation on  the modal closing, apply filters or not

**Comment by danharrin** [comment]
Where would we store the old filter values to restore them to?

**Pull request merged**
