### PR TITLE
Fix sidebar header ring overflow-x

### PR DESCRIPTION
**Pull request by 4m1n0s**
- [x] Changes have been thoroughly tested to not break existing functionality.
- [x] New functionality has been documented or existing documentation has been updated to reflect changes.
- [x] Visual changes are explained in the PR description using a screenshot/recording of before and after.

Before:
image

After:

image

### CODE REVIEW

**Review by zepfietje — CHANGES_REQUESTED** [review]
Thanks for reporting this, @4m1n0s.
The use of box-shadow/ring is by design though, to match the positioning of content under the topbar, as the ring doesn't take up any space while the border does.

Could you rework this PR to just prevent overflow-x on the sidebar header? Similar approach is used on the topbar, though it may require a wrapping element.

**Comment by 4m1n0s** [comment]
@zepfietje in this case i think only a wrapping div like that is enough?

```html
<div class="overflow-x-clip">
    <header>.....</header>
</div>
```

**Comment by zepfietje** [comment]
I don't know, @4m1n0s.
Please test it and commit if it works. :)

**Review by zepfietje — APPROVED** [review]

**Comment by zepfietje** [comment]
Thanks!

**Pull request merged**
