### PR TITLE
Support relationGroups

### PR DESCRIPTION
**Pull request by ziming**
My PR Attempt on: https://github.com/laravel-filament/filament/discussions/2258

Some initial code, I'm not sure how to handle the $activeRelationManager part since there are now multiple tab groups. Feel free to take over and continue on this PR

### CODE REVIEW

**Comment by danharrin** [comment]
How are we gonna handle setting the group slug & tab label?

I'm thinking something like this:

```php
[
    'addresses' => AddressesRelationManager::class,
    'shop' => RelationManagerGroup::make([
        OrdersRelationManger::class,
        ReviewsRelationManger::class,
    ], 'Shop'),
    'comments' => CommentsRelationManager::class,
]
```

**Comment by danharrin** [comment]
Any other ideas syntax @ryangjchandler?

**Comment by ryangjchandler** [comment]
@danharrin I like the syntax you have there. I'd probably swap the label and array params around though.

**Comment by danharrin** [comment]
Fair 👍

**Comment by danharrin** [comment]
Done! Thanks.

**Pull request merged**
