### PR TITLE
Fix: Hide toggleable hidden column in column toggle dropdown

### LINKED ISSUE #12780: Toggle Checkbox Remains Visible When the Column is Hidden
### Package

filament/tables

### Package Version

v3.2.77

### Laravel Version

v11.7.0

### Livewire Version

v3.4.12

### PHP Version

PHP 8.3.7

### Problem description

```php
Tables\Columns\TextColumn::make('email')
    ->hidden(fn() => ...)
    ->toggleable(),
```

When the hidden condition is true, the toggle checkbox remains visible

image

### Expected behavior

The toggle checkbox also becames hidden

image

### Steps to reproduce

Clone the repo, make filament user, navigate to users resource, set hidden condition for `email` or `updated_at` column

### Reproduction repository

https://github.com/NathanaelGT/filament-toggleable-with-hidden

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by dev-idkwhoami**
## Description

This is related to issue #12780.

When deciding whether the dropdown action should be visible and when rendering the dropdown items the code did not check if the column is hidden.

## Visual changes

Before:
image

After:
image

## Functional changes

- [x] Code style has been fixed by running the `composer cs` command.
- [x] Changes have been tested to not break existing functionality.
- [x] Documentation is up-to-date.

### CODE REVIEW

**Comment by untillnesss** [comment]
This is what happened to me, and I need this, immediately merge and release this change!

**Comment by NathanaelGT** [comment]
This PR solves my issue 👍

**Comment by danharrin** [comment]
Can you please refactor this so `isHidden()` is checked inside the `isToggleable()` method, as an early return maybe? Then we don't need to worry about doing this in each place :)

> immediately merge and release this change!

@untillnesss patience... you're message comes across very demanding

**Comment by danharrin** [comment]
Thanks

**Pull request merged**
