### PR TITLE
Improve actions

### PR DESCRIPTION
**Pull request by zepfietje**
- [x] Changes have been thoroughly tested to not break existing functionality.
- [x] New functionality has been documented or existing documentation has been updated to reflect changes.
- [x] Visual changes are explained in the PR description using a screenshot/recording of before and after.

---

Adds support for:

- Nested notification action groups.
- Different views for notification action groups (button, link, etc.).
- Tooltips on actions.
- Notification action groups size.
- Notification action groups extra attributes.
- Outlined notification action groups.
- Actions of type badge.

### CODE REVIEW

**Comment by saade** [comment]
Great work!

With this PR's Bagded Actions, can we add support for passing it as a badge where possible? (we can force `->badge()` on the action for design consistency) e.g:

```php
NavigationItem::make('Foo')
  ->badge(
    Action::make('create-foo')
        ->badge()
  )
```

or

```php
Tab::make('Foo')
  ->badge(
    Action::make('show-foos')
        ->label(3)
        ->badge()
  )
```

For context: I have a sidebar showing blogs, calendars, and maps, and for each one i have a NavigationItem with a empty label and a badge `Create foo`, for now, i'm redirecting to the create page, but would be nice to trigger an action directly from the sidebar/ supported components

image

**Comment by zepfietje** [comment]
To be honest, that seems quite hacky from your screenshot. 😅
Accepting badge actions in those cases will probably not work out well, as you can't have nested buttons or links.

**Comment by saade** [comment]
It its hacky yes, but that's what i have working for now. I think adding a NavigationItem called "Create a Blog" will confuse perople because there's no diff from the items above.

 i'll remove the badges if/when #8434 gets merged.

**Comment by saade** [comment]
> To be honest, that seems quite hacky from your screenshot. 😅 Accepting badge actions in those cases will probably not work out well, as you can't have nested buttons or links.

Its hacky, yes, but that's what i have working for now. I think adding a NavigationItem called "Create a Blog" will confuse people because there's no diff from the items above.

i'll remove the badges if/when https://github.com/filamentphp/filament/pull/8434 gets merged.

**Comment by andrewdwallo** [comment]
@saade If you don't mind me asking, how did you do the design for your sidebar? I have been wanting to do that for a long time... Is this supported in Filament natively?

**Comment by zepfietje** [comment]
@andrewdwallo, please continue this discussion on Discord to not cause unnecessary notifications for other people in this pull request. 🙂

**Pull request merged**
