### PR TITLE
Support additional repeater and builder actions

### PR DESCRIPTION
**Pull request by yassine-kessal**
This PR adds the possibility of setting custom actions in the form's reapter field (other than predefined add, clone, etc. actions), using the repeater's registerActions method, example :

```php
Repeater::make('fields')
      ->collapsible()
      ->reorderableWithButtons()
      ->itemLabel(fn (array $state): ?string => $state['name'] ?? null)
      ->columns(2)
      ->registerActions([
          Action::make('field-settings')
              ->icon('heroicon-o-cog')
              ->iconButton(),
          Action::make('copy')
              ->icon('heroicon-o-clipboard')
              ->iconButton(),
      ]);
```

**Preview :** 
image

- [x] Changes have been thoroughly tested to not break existing functionality.
- [ ] New functionality has been documented or existing documentation has been updated to reflect changes.
- [x] Visual changes are explained in the PR description using a screenshot/recording of before and after.

### CODE REVIEW

**Comment by yassine-kessal** [comment]
Oupps sorry for commits sync on this branch, let me know if you want me to recreate the PR.

**Comment by yassine-kessal** [comment]
A little commit to add this feature for Builder form component and be more consistent.

**Comment by tonypartridger** [comment]
Thoughts on adding support to builder blocks too?

**Comment by danharrin** [comment]
This PR covers repeater and builder header actions.

**Comment by tonypartridger** [comment]
> This PR covers repeater and builder header actions.

It sure does, but unless I am missing something it doesn't cover Builder 'Block' actions.

**Comment by danharrin** [comment]
I do not understand what a block action is, compared to a header action.

**Comment by tonypartridger** [comment]
> I do not understand what a block action is, compared to a header action.

No problem, please see attached.
Screenshot 2023-12-11 at 09 23 44

**Comment by danharrin** [comment]
its a header action

**Comment by tonypartridger** [comment]
> its a header action

It's a header action of the builder block type yep. This PR only supports header actions on the repeater and the builder header actions not the builder block header actions as far as I can tell. 

I am asking what your thoughts are on adding it to the Builder Block Header Actions too.

**Comment by danharrin** [comment]
in your screenshot, they both look like `extraItemActions()` that are possible in this PR

**Comment by tonypartridger** [comment]
See attached the Builder\Block does not support extraItemActions. This is what I was suggesting we expand support to.

Screenshot 2023-12-11 at 09 54 30

**Comment by danharrin** [comment]
So are you asking for block-specific actions that are not added to every block type at once? Because they would look the same as the current solution

**Pull request merged**
