### PR TITLE
Feature: Added the option to modals to prevent closing on escape key press

### PR DESCRIPTION
**Pull request by borjajimnz**
## Description

Added the option to modals prevent it from closing when the Escape key is pressed. This enhancement ensures the modal remains on the screen, offering a more consistent user experience and eliminating accidental closures when required.

```
Action::make('updateAuthor')
    ->form([
        // ...
    ])
    ->action(function (array $data): void {
        // ...
    })
    ->closedByHittingEscape(false)
```

## Visual changes

No visual changes.

## Functional changes

- [X] Code style has been fixed by running the `composer cs` command.
- [X] Changes have been tested to not break existing functionality.
- [X] Documentation is up-to-date.

**Love Filament !! Good job 💕**

### CODE REVIEW

**Review by danharrin — CHANGES_REQUESTED** [review]
Please rename the terminology here to be `closedByEscaping` instead - "hitting" is a bit aggressive 🤣

**Comment by zepfietje** [comment]
Wouldn't `closedByPressingEscape` be clearer, @danharrin?

**Comment by danharrin** [comment]
Considered it, but I prefer what I suggested

**Comment by borjajimnz** [comment]
Changed @danharrin, regards!

**Comment by danharrin** [comment]
Thanks

**Pull request merged**
