### PR TITLE
Add Documentation about resource declaration within pages.

### PR DESCRIPTION
**Pull request by tonypartridge**
- [ ] Changes have been thoroughly tested to not break existing functionality.
- [ ] New functionality has been documented or existing documentation has been updated to reflect changes.
- [ ] Visual changes are explained in the PR description using a screenshot/recording of before and after.

### CODE REVIEW

**Comment by danharrin** [comment]
Hmm, can you explain a bit more? I don't think we changed anything here? Were you using Filament/Pages/Page before in v2?

**Comment by danharrin** [comment]
I'm going to close this until there is more clarity :)

**Comment by tonypartridge** [comment]
Sorry Dan, there was a discord issue; see:

https://discord.com/channels/883083792112300104/1171832702765371553

It looks like when custom pages may have been created and the definition is not declared. But I've asked in the chat for the whole start so we can see where they were extending from.

**Comment by tonypartridge** [comment]
So yeah it was extending:

use Filament\Resources\Pages\Page;

**Comment by danharrin** [comment]
That class in v2 also required `$resource`

**Comment by tonypartridge** [comment]
Thanks Dan, I've checked and in prod we have the attached. Which works flawlessly with filamentphp 2.17.52 

image

But requires the resource classification on V3. I've noticed a few posts about this now on Discord too.

**Comment by danharrin** [comment]
I think this only applies to pages that don't render, and redirect in `mount()`, but fair enough

**Pull request merged**
