### PR TITLE
Update 07-notifications.md

### PR DESCRIPTION
**Pull request by aliaxonbaig**
There is no reference to requirement of queue in the docs.

## Description
No reference to the requirement of queue in the documentation.

## Functional changes

- [* ] Code style has been fixed by running the `composer cs` command.
- [ n/a] Changes have been tested to not break existing functionality.
- [ *] Documentation is up-to-date.

### CODE REVIEW

**Comment by dreftas** [comment]
I suggest to do `queue:listen` instead of `queue:work`, because "`queue:listen` will continue to work after altering your code (you don't have to manually restart the worker), while `queue:work` needs to be restarted before reflecting the changes you made". So there will be less misunderstandings while coding.

**Review by aliaxonbaig — COMMENTED** [review]
Changes to commands added as suggested.

**Comment by danharrin** [comment]
Please move it to this section: https://filamentphp.com/docs/3.x/notifications/database-notifications#overview

**Review by danharrin — CHANGES_REQUESTED** [review]
Please move it to this section: https://filamentphp.com/docs/3.x/notifications/database-notifications#overview

**Comment by danharrin** [comment]
Please reopen when that change has been implemented, you'll probably want to use a new branch anyway

**Pull request closed without merging**
