### PR TITLE
Added a space before exclamation mark in command outputs

### PR DESCRIPTION
**Pull request by pullaf**
This will make the filename clickable in VScode's terminal window to automatically open the newly created file (or at least open the search window with the filename)

- [ X ] Changes have been thoroughly tested to not break existing functionality.

### CODE REVIEW

**Comment by danharrin** [comment]
Let's just remove the exclamation altogether, please

**Comment by danharrin** [comment]
Hi, are you able to work on this?

**Comment by pullaf** [comment]
I just committed a new version with the outputs updated to match Laravel's style

**Comment by wychoong** [comment]
Quoting Dan here https://github.com/filamentphp/filament/pull/8722#issuecomment-1741740125
Don’t use sprintf

**Comment by danharrin** [comment]
#8722 actually replaces this, so we probably don't need to take any action anymore. Thanks.

**Pull request closed without merging**
