### PR TITLE
Adding an extra repeater and builder header actions

### PR DESCRIPTION
**Pull request by devhoussam1998**
- [x] Changes have been thoroughly tested to not break existing functionality.
- [x] New functionality has been documented or existing documentation has been updated to reflect changes.
- [x] Visual changes are explained in the PR description using a screenshot/recording of before and after.

Same as modals have [the ability to Adding an extra modal action button to the footer](https://filamentphp.com/docs/3.x/actions/modals#adding-an-extra-modal-action-button-to-the-footer)

The Result will be in:

**Repeater**

Screenshot 2023-11-28 at 14 20 06

**Builder**

Screenshot 2023-11-28 at 14 19 59

### CODE REVIEW

**Comment by danharrin** [comment]
Duplicate of #8461 which will be released in 3.1

**Comment by devhoussam1998** [comment]
> Duplicate of #8461 which will be released in 3.1

I tested that it did not work but my PR works well

**Comment by danharrin** [comment]
What did not work

**Comment by danharrin** [comment]
It's not released yet, so please fix that existing feature instead of adding it again

**Comment by devhoussam1998** [comment]
> What did not work

After reviewing the code, I realized that there is a missing piece of code.

**For Repeater**

```
$this->registerActions([
    ...
    fn (Repeater $component): array => $component->getExtraItemActions(),
]);
```

**For Builder**

```
$this->registerActions([
    ...
    fn (Builder $component): array => $component->getExtraItemActions(),
]);
```

after adding it the `->requiresConfirmation()` works well.

**Check this out:**


https://github.com/filamentphp/filament/assets/121255432/e69e603d-75d8-446b-a417-28b061fa62d0

**Comment by danharrin** [comment]
You should not need to register the actions, because of how the actions are discovered using the HasHeaderActions interface

**Comment by devhoussam1998** [comment]
> You should not need to register the actions, because of how the actions are discovered using the HasHeaderActions interface

I think you are right I did not use the `HasHeaderActions` in my testing

**Comment by danharrin** [comment]
```
Forms\Components\Repeater::make('items')
                    ->extraItemActions([
                        Forms\Components\Actions\Action::make('test')
                            ->link()
                            ->requiresConfirmation(),
                    ])
```

You dont need to implement anything yourself

**Pull request closed without merging**
