### PR TITLE
Remove unused method

### PR DESCRIPTION
**Pull request by zepfietje**
I'm not 100% sure, so please have a good look, @danharrin.
To me it seemed like this method isn't used (anymore).

- [ ] Changes have been thoroughly tested to not break existing functionality.
- [ ] New functionality has been documented or existing documentation has been updated to reflect changes.
- [ ] Visual changes are explained in the PR description using a screenshot/recording of before and after.

### CODE REVIEW

**Comment by danharrin** [comment]
It's part of our public API, allowing you to disable the button across all create pages at once (since we dont have config anymore)

**Comment by zepfietje** [comment]
Ah totally missed this.
Though we may still want to rename `disableCreateAnother` to `createAnother`, just like in the other places?

**Comment by danharrin** [comment]
Sure, that's not bad. If it's in the v2 API, the old method will need to be deprecated too

**Comment by zepfietje** [comment]
Ah I see there's already a method `createAnother()` on the class that calls the `create()` method... Thoughts, @danharrin?

**Comment by danharrin** [comment]
Ah well we'll have to leave it as-is

**Pull request closed without merging**
