### PR TITLE
Support `hasCollapsibleNavigationWithText`

### PR DESCRIPTION
**Pull request by lam0819**
- [x] Changes have been thoroughly tested to not break existing functionality.
- [x] New functionality has been documented or existing documentation has been updated to reflect changes.
TBC
- [x] Visual changes are explained in the PR description using a screenshot/recording of before and after.

In this change, I added a collapsed menu with text UI. 
Following is the result and reference UI on the internet.
Here are some advantages.
- Improved clarity: Providing text labels alongside icons in the menu bar adds clarity by explicitly stating the purpose or function of each menu item. Users can quickly understand the options available to them without relying solely on visual cues.
- Enhanced accessibility: Text labels help users with visual impairments or color deficiencies to navigate the interface. Screen readers can read out the text, making the menu more accessible and inclusive.
- Reduced cognitive load: Icons alone can sometimes be ambiguous or require users to recall their meaning. By including text labels, users don't need to rely solely on their memory or guesswork to understand the purpose of each menu item. This reduces cognitive load and improves the overall user experience.
- Faster task completion: When users can quickly recognize and understand menu options, it speeds up their interaction with the application. Text labels provide clear and concise information, enabling users to locate the desired functionality more efficiently.
- Consistency and learnability: Text labels in the menu bar create consistency throughout the application. Users become familiar with the terminology and phrasing used in the labels, making it easier for them to navigate and learn the system. This consistency enhances the overall user experience and reduces the learning curve for new users.

image

Screenshot 2023-11-06 at 5 36 37 PM

Before

### CODE REVIEW

**Comment by zepfietje** [comment]
How would this work with sidebar items that don't have an icon and groups?
Judging from your screenshot, this PR still needs quite a bit of work.

Let's start with making sure it handles items without icons properly.
Please mark as ready for review when done, @lam0819.

**Comment by lam0819** [comment]
In fact, I have not highly customized the current sidebar menu.

For the group, the original sidebar menu setting with group 
image
Screenshot 2023-11-06 at 5 36 37 PM


In the current sidebar menu, I think we face the same issue, items without icons. 
image

in fact, I can show the text to cater above case.

**Comment by zepfietje** [comment]
Shouldn't that throw an exception, @danharrin? Using items with and without icon.

**Comment by danharrin** [comment]
I think it should, yeah

**Comment by lam0819** [comment]
I am not sure where or when will throw an exception. 
I try following code still work fine in  3.0 branch

image

->navigationItems([
                NavigationItem::make('Analytics2')
                    ->url('https://filament.pirsch.io', shouldOpenInNewTab: true)
                    ->sort(2),
                NavigationItem::make('Analytics')
                    ->url('https://filament.pirsch.io', shouldOpenInNewTab: true)
                    ->icon('heroicon-o-presentation-chart-line')
                    ->group('Reports')
                    ->sort(3),
                NavigationItem::make('dashboard')
                    ->label(fn (): string => __('filament-panels::pages/dashboard.title'))
                    ->url(fn (): string => Dashboard::getUrl())
                    ->isActiveWhen(fn () => request()->routeIs('filament.admin.pages.dashboard')),
                    NavigationItem::make('dashboard')
                    ->label(fn (): string => __('filament-panels::pages/dashboard.title'))
                    ->url(fn (): string => Dashboard::getUrl())
                    ->isActiveWhen(fn () => request()->routeIs('filament.admin.pages.dashboard')),NavigationItem::make('dashboard')
                    ->label(fn (): string => __('filament-panels::pages/dashboard.title'))
                    ->url(fn (): string => Dashboard::getUrl())
                    ->isActiveWhen(fn () => request()->routeIs('filament.admin.pages.dashboard')),
                // ...
            ])


and if grouped section without icon , it will show "dot" icon.
image

Or you want throw an exception when using this  navigation with text, icon is required.

**Comment by zepfietje** [comment]
Waiting for https://github.com/filamentphp/filament/pull/8102 to be implemented first.

**Comment by zepfietje** [comment]
@lam0819, could you update this PR to work with the latest 3.x changes?
Mark as ready for review when done. 🙂

**Comment by lam0819** [comment]
> @lam0819, could you update this PR to work with the latest 3.x changes?
> 
> Mark as ready for review when done. 🙂

I will look into it.

**Comment by lam0819** [comment]
updated latest filament code base 
revised now.
https://github.com/filamentphp/filament/assets/68211972/31a1d0f9-227e-464b-b6fa-51528d19761e

**Comment by zepfietje** [comment]
After another review, I don't think this API is suitable for our design system.
Thanks, @lam0819.

**Comment by danharrin** [comment]
Thanks Alan, you can probably override the view in this case quite safely

**Pull request closed without merging**
