### PR TITLE
fix: Delay panel registration

### LINKED ISSUE #7604: Cannot use trans in panel config after upgrade
### Package

filament/filament

### Package Version

v3.0.14

### Laravel Version

v10.18.0

### Livewire Version

_No response_

### PHP Version

PHP 8.2

### Problem description

Cannot use translation in panel config after upgrade from `v3.0.8` to `v3.0.14`

```
Target class [translator] does not exist.
```

```php
            ->userMenuItems([
                MenuItem::make()
                    ->label(__('My Profile')) // error right here
                    ->url(fn () => Profile::getUrl())
                    ->icon('heroicon-o-user-circle'),
            ]);
```

### Expected behavior

works

### Steps to reproduce

Use `trans()` or `__()` in admin panel service

### Reproduction repository

https://github.com/datlechin/filament

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by danharrin**
Fixes #7604.

### CODE REVIEW

**Comment by bram-pkg** [comment]
This seems to have broke having multiple panels for me, routes for anything but the default panel are not registering.

I can confirm that after reverting the change in the facade, routes are showing up again.

**Comment by danharrin** [comment]
Hey @bram-pkg, please clear all your caches and ensure that your service providers are registered correctly. I cannot reproduce your problem. Also, this PR is just me reverting the code to what it was before.

**Comment by bram-pkg** [comment]
Odd, when I clone this repo: https://github.com/bram-pkg/filament-issue-7649.git (so no cache, no nothing)

Running `php artisan route:list` does not return any of the tenant routes from the `AppPanelProvider`.

If I put a `dd('test')` inside the AppPanelProvider, it does get triggered, but something seems to be off about the route registration.

When I lock my version to 3.0.16, the `/login` and `/{tenant}/users` URLs show up again, after upgrading, even after clearing my `bootstrap/cache` and removing the vendor directory/composer install, they do not show up.

<details>
<summary> <code>php artisan route:list</code> when on v3.0.16</summary>
<pre>
  GET|HEAD   / .................................................... filament.app.tenant › Filament\Http › RedirectToTenantController
  POST       _ignition/execute-solution .............. ignition.executeSolution › Spatie\LaravelIgnition › ExecuteSolutionController
  GET|HEAD   _ignition/health-check .......................... ignition.healthCheck › Spatie\LaravelIgnition › HealthCheckController
  POST       _ignition/update-config ....................... ignition.updateConfig › Spatie\LaravelIgnition › UpdateConfigController
  GET|HEAD   admin ..................................................... filament.admin.pages.dashboard › Filament\Pages › Dashboard
  GET|HEAD   admin/login ................................................ filament.admin.auth.login › App\Filament\Admin\Pages\Login
  POST       admin/logout ............................................ filament.admin.auth.logout › Filament\Http › LogoutController
  GET|HEAD   admin/tenants .. filament.admin.resources.tenants.index › App\Filament\Admin\Resources\TenantResource\Pages\ListTenants
  GET|HEAD   admin/tenants/create filament.admin.resources.tenants.create › App\Filament\Admin\Resources\TenantResource\Pages\Creat…
  GET|HEAD   admin/tenants/{record}/edit filament.admin.resources.tenants.edit › App\Filament\Admin\Resources\TenantResource\Pages\…
  GET|HEAD   admin/users .......... filament.admin.resources.users.index › App\Filament\Admin\Resources\UserResource\Pages\ListUsers
  GET|HEAD   admin/users/create . filament.admin.resources.users.create › App\Filament\Admin\Resources\UserResource\Pages\CreateUser
  GET|HEAD   admin/users/{record}/edit filament.admin.resources.users.edit › App\Filament\Admin\Resources\UserResource\Pages\EditUs…
  GET|HEAD   api/user .............................................................................................................. 
  GET|HEAD   livewire/livewire.js ...................................... Livewire\Mechanisms › FrontendAssets@returnJavaScriptAsFile
  GET|HEAD   livewire/preview-file/{filename} ............. livewire.preview-file › Livewire\Features › FilePreviewController@handle
  POST       livewire/update ................................... livewire.update › Livewire\Mechanisms › HandleRequests@handleUpdate
  POST       livewire/upload-file ........................... livewire.upload-file › Livewire\Features › FileUploadController@handle
  GET|HEAD   login ................................................................ filament.app.auth.login › Filament\Pages › Login
  POST       logout .................................................... filament.app.auth.logout › Filament\Http › LogoutController
  GET|HEAD   sanctum/csrf-cookie ................................. sanctum.csrf-cookie › Laravel\Sanctum › CsrfCookieController@show
  GET|HEAD   {tenant} .................................................... filament.app.pages.dashboard › Filament\Pages › Dashboard
  GET|HEAD   {tenant}/tenants ... filament.app.resources.tenants.index › App\Filament\App\Resources\TenantResource\Pages\ListTenants
  GET|HEAD   {tenant}/tenants/create filament.app.resources.tenants.create › App\Filament\App\Resources\TenantResource\Pages\Create…
  GET|HEAD   {tenant}/tenants/{record}/edit filament.app.resources.tenants.edit › App\Filament\App\Resources\TenantResource\Pages\E…
  GET|HEAD   {tenant}/users ........... filament.app.resources.users.index › App\Filament\App\Resources\UserResource\Pages\ListUsers
  GET|HEAD   {tenant}/users/create .. filament.app.resources.users.create › App\Filament\App\Resources\UserResource\Pages\CreateUser
  GET|HEAD   {tenant}/users/{record}/edit filament.app.resources.users.edit › App\Filament\App\Resources\UserResource\Pages\EditUser
</pre>
</details>

<details>
<summary> <code>php artisan route:list</code> when on v3.0.19</summary>
<pre>
  POST       _ignition/execute-solution .............. ignition.executeSolution › Spatie\LaravelIgnition › ExecuteSolutionController
  GET|HEAD   _ignition/health-check .......................... ignition.healthCheck › Spatie\LaravelIgnition › HealthCheckController
  POST       _ignition/update-config ....................... ignition.updateConfig › Spatie\LaravelIgnition › UpdateConfigController
  GET|HEAD   admin ..................................................... filament.admin.pages.dashboard › Filament\Pages › Dashboard
  GET|HEAD   admin/login ................................................ filament.admin.auth.login › App\Filament\Admin\Pages\Login
  POST       admin/logout ............................................ filament.admin.auth.logout › Filament\Http › LogoutController
  GET|HEAD   admin/tenants .. filament.admin.resources.tenants.index › App\Filament\Admin\Resources\TenantResource\Pages\ListTenants
  GET|HEAD   admin/tenants/create filament.admin.resources.tenants.create › App\Filament\Admin\Resources\TenantResource\Pages\Creat…
  GET|HEAD   admin/tenants/{record}/edit filament.admin.resources.tenants.edit › App\Filament\Admin\Resources\TenantResource\Pages\…
  GET|HEAD   admin/users .......... filament.admin.resources.users.index › App\Filament\Admin\Resources\UserResource\Pages\ListUsers
  GET|HEAD   admin/users/create . filament.admin.resources.users.create › App\Filament\Admin\Resources\UserResource\Pages\CreateUser
  GET|HEAD   admin/users/{record}/edit filament.admin.resources.users.edit › App\Filament\Admin\Resources\UserResource\Pages\EditUs…
  GET|HEAD   api/user .............................................................................................................. 
  GET|HEAD   livewire/livewire.js ...................................... Livewire\Mechanisms › FrontendAssets@returnJavaScriptAsFile
  GET|HEAD   livewire/preview-file/{filename} ............. livewire.preview-file › Livewire\Features › FilePreviewController@handle
  POST       livewire/update ................................... livewire.update › Livewire\Mechanisms › HandleRequests@handleUpdate
  POST       livewire/upload-file ........................... livewire.upload-file › Livewire\Features › FileUploadController@handle
  GET|HEAD   sanctum/csrf-cookie ................................. sanctum.csrf-cookie › Laravel\Sanctum › CsrfCookieController@show
</pre>
</details>

Weirdly, when reverting the change done in this PR (changing the contents of `public static function registerPanel(Panel $panel): void` back to before this PR) the routes show up again.

**Comment by danharrin** [comment]
Please open an issue and I will look into it

**Comment by bram-pkg** [comment]
While writing the issue and making a minimally reproducible repository; I figured that this call in my AppPanelProvider (the second provider):

```php
->navigationItems([
    NavigationItem::make('Admin')
        ->url('/' . Filament::getPanel('admin')->getPath(), shouldOpenInNewTab: true)
        ->icon('heroicon-m-cube-transparent')
        ->visible(fn () => auth()->user()->getKey() === 1),
])
```
was causing the issue. The URL call on NavigationItem had to be a closure, as `Filament::getPanel('admin')` was failing when evaluated immediately.

**Comment by vertexer** [comment]
> While writing the issue and making a minimally reproducible repository; I figured that this call in my AppPanelProvider (the second provider):
> 
> ```
> ->navigationItems([
>     NavigationItem::make('Admin')
>         ->url('/' . Filament::getPanel('admin')->getPath(), shouldOpenInNewTab: true)
>         ->icon('heroicon-m-cube-transparent')
>         ->visible(fn () => auth()->user()->getKey() === 1),
> ])
> ```
> 
> was causing the issue. The URL call on NavigationItem had to be a closure, as `Filament::getPanel('admin')` was failing when evaluated immediately.

+1 Issue and solution confirmed (introduced after 3.0.16).

**Pull request merged**
