### PR TITLE
Fix issue where a collapsed section content was still filling space

### PR DESCRIPTION
**Pull request by lamberttraccard**
- [x] Changes have been thoroughly tested to not break existing functionality.
- [ ] New functionality has been documented or existing documentation has been updated to reflect changes.
- [x] Visual changes are explained in the PR description using a screenshot/recording of before and after.

## Before
CleanShot 2023-08-25 at 21 31 20@2x

## After
CleanShot 2023-08-25 at 21 32 11@2x

### CODE REVIEW

**Comment by zepfietje** [comment]
Thanks for the PR, @lamberttraccard.
However, I do think there's a reason for this approach.
I didn't implement it initially so turning to @danharrin again (this is what we talked about on that other PR last week too).

**Comment by danharrin** [comment]
The `h-0` should cover it. There is a reason why it's invisible but I can't remember

**Comment by lamberttraccard** [comment]
I can't tell you either 😅. Just that in the current state something is off. 🙂

**Comment by lamberttraccard** [comment]
Maybe the invisible was for a transition effect, but making it hidden doesn't seem to change anything, expect the current issue

**Comment by danharrin** [comment]
Note to future self: don't merge until you find the reason it was invisible

**Comment by danharrin** [comment]
Found the reason @lamberttraccard @zepfietje - #1967, to do with using a FileUpload inside it

Implemented in #1997

**Comment by zepfietje** [comment]
Right, and we can't use `x-if` instead of `x-show` because we'd lose field state?

**Comment by danharrin** [comment]
I haven't tried it, but I feel like it wouldnt be very performant

**Comment by lamberttraccard** [comment]
Thanks, I will have a look this weekend if I can find a workaround and why the problem occur sometimes

**Comment by danharrin** [comment]
We're going to need an explanation as to why `invisible h-0` doesn't work, and which browsers can reproduce this on 👍 Once you reattempt a different fix, you can submit a new PR

**Pull request closed without merging**
