### PR TITLE
Add hex color validation rule

### PR DESCRIPTION
**Pull request by binaryfire**
Add the new hex color validation rule

### CODE REVIEW

**Review by danharrin — APPROVED** [review]

**Comment by danharrin** [comment]
Is it worth adding validation by default to ColorPicker?

**Comment by zepfietje** [comment]
Default validation for color picker sounds good to me.

**Comment by danharrin** [comment]
Might mean we have to add custom rules for RGB etc

**Comment by binaryfire** [comment]
@danharrin The native color picker can handle hex, RGB and HSL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/color

Is it possible we might expand the field at some point to allow showing this color mode selector? Might be better to avoid making it check for hex by default.

**Comment by binaryfire** [comment]
@danharrin 
image

**Comment by danharrin** [comment]
You can already do it with TextInput::make()->type('color')

**Comment by binaryfire** [comment]
Oh right, I didn't realise the ColorPicker already [accepts other formats](https://filamentphp.com/docs/3.x/forms/fields/color-picker#setting-the-color-format).

Only `hex_color` was added to Laravel core so yeah, it would require custom rules. Wouldn't that be better in a separate PR? This one is just to keep the Filament rules up to date with core.

**Pull request merged**
