### PR TITLE
Validate MakePage command page name input.

### PR DESCRIPTION
**Pull request by Nuhel**
- [x] Changes have been thoroughly tested to not break existing functionality.
- [x] New functionality has been documented or existing documentation has been updated to reflect changes.
- [x] Visual changes are explained in the PR description using a screenshot/recording of before and after.

Last day while i was creating a page, I mistakenly provided a name that contained white space.
Which generated class with the white space.

### CODE REVIEW

**Comment by Nuhel** [comment]
@danharrin 

Check this, if u like this approach, i will merge this with other commands to. 

We can also use below regex to accept name with namespace 

>  ^[a-zA-Z_\x7f-\xff][a-zA-Z0-9_\x7f-\xff]*(\\[a-zA-Z_\x7f-\xff][a-zA-Z0-9_\x7f-\xff]*)*$

**Comment by danharrin** [comment]
Is there no built-in validation rule in Laravel we can use? Like `alpha_num`

**Comment by danharrin** [comment]
Or does that not allow `/` or something

**Comment by danharrin** [comment]
Hmm, I think it's okay if we leave out validation for now, thanks though

**Pull request closed without merging**
