### PR TITLE
Fix fileUpload button tooltip, Fix translate

### PR DESCRIPTION
**Pull request by killjin**
- [x] Changes have been thoroughly tested to not break existing functionality.
- [x] New functionality has been documented or existing documentation has been updated to reflect changes.
- [x] Visual changes are explained in the PR description using a screenshot/recording of before and after.

@js directive not working in @foreach? Change to Illuminate\Support\Js::from that's ok.

### CODE REVIEW

**Comment by zepfietje** [comment]
What are the `toHtml()` calls needed for?

Also, are you sure `{{ }}` works here in Blade component attributes? It doesn't always work IIRC.

**Comment by killjin** [comment]
@js is equivalent to from()->toHtml()
I test @js doesn't work here, {{}} works.

**Comment by danharrin** [comment]
I've made some changes, does it still work?

**Comment by killjin** [comment]
image
image

It won't work after modification

**Comment by danharrin** [comment]
Can you look into why that is? We should avoid `{{}}` inside Blade components if possible, hence why I concatenated it

**Comment by killjin** [comment]
According to my observation, @js doesn't work in @foreach loop, it may be a bug of blade.

In this file, {{ }} is used very frequently, and now the content of $action['label'] must be output, but @js does not work, and the php function Js::from can only be used instead.

**Comment by killjin** [comment]
```
<?php
//vendor/laravel/framework/src/Illuminate/View/Compilers/Concerns/CompilesJs.php

namespace Illuminate\View\Compilers\Concerns;

use Illuminate\Support\Js;

trait CompilesJs
{
    /**
     * Compile the "@js" directive into valid PHP.
     *
     * @param  string  $expression
     * @return string
     */
    protected function compileJs(string $expression)
    {
        return sprintf(
            "<?php echo \%s::from(%s)->toHtml() ?>",
            Js::class, $this->stripParentheses($expression)
        );
    }
}
```

@js is a short name for {{ Illuminate\Support\Js::from()->toHtml() }} , why can't it be used?

**Comment by killjin** [comment]
Sorry for not seeing the : before the code due to my carelessness, this works.

```
:x-tooltip="'{
        content: ' . \Illuminate\Support\Js::from($action['label']) . ',
        theme: $store.theme,
    }'"
```

**Comment by killjin** [comment]
Correct my mistake, @js works in @foreach, but it doesn't work in blade component attribute..

It's work:
```
@php
$vv = [
    'a' => ['label' => 'labela'], 'b' => ['label' => 'labelb'], 'c' => ['label' => 'labelc']
];
@endphp

@foreach ($vv as $v)
<a
    x-tooltip="{
        content: @js($v['label']),
        theme: $store.theme,
    }">vv</a>
@endforeach
```

Put it inside <x-filament::button and it won't work:
```
<x-filament::button 
    x-tooltip="{
        content: @js($v['label']),
        theme: $store.theme,
    }">vv</x-filament::button>
```

**Comment by danharrin** [comment]
So the current implementation in this PR works, right?

**Comment by killjin** [comment]
Yes, This PR is fine and works fine.

**Pull request merged**
