### PR TITLE
Laravel 11

### PR DESCRIPTION
**Pull request by danharrin**
Issues

- [x] [Service provider auto-registration](https://github.com/laravel/framework/blob/master/src/Illuminate/Foundation/Console/ProviderMakeCommand.php#L49-L52)
- [x] Tests are failing due to database setup issue

Dependencies that need updating for core packages to function:

- [x] https://github.com/AnourValar/eloquent-serialize
- [x] https://github.com/kirschbaum-development/eloquent-power-joins

Dependencies that need updating for CI to function:

- [x] https://github.com/spatie/laravel-medialibrary
- [x] https://github.com/spatie/laravel-ray
- [x] https://github.com/spatie/eloquent-sortable
- [x] https://github.com/spatie/laravel-tags
- [x] https://github.com/staudenmeir/belongs-to-through
- [x] https://github.com/staudenmeir/eloquent-has-many-deep

### CODE REVIEW

**Comment by tisuchi** [comment]
Hi @danharrin 

Thanks for the nice work. 

Does it mean that we need to Laravel 11 to merge this pull request?

If we want to install filament with laravel 11-dev, is there any way to do that?

**Comment by danharrin** [comment]
If you would like to use it, you can contribute to eloquent-serialize and power-joins with Laravel 11 support. Once those packages have support, we can merge this PR.

**Comment by atmonshi** [comment]
is there any knowing issues with eloquent-serialize and L11?
aside from adding `|^11.0`?
test it with fresh installation L11 seems all fine.
```php
$package = EloquentSerializeFacade::serialize(
        \App\Models\User::query()
            ->limit(2)
    );

    dump($package);
    
    $builder = EloquentSerializeFacade::unserialize($package);
    foreach ($builder->get() as $item) {
        dump($item);
    }
```

**Comment by danharrin** [comment]
I can't imagine there will be issues, just needs to be a PR

**Comment by staudenmeir** [comment]
> https://github.com/staudenmeir/belongs-to-through
> https://github.com/staudenmeir/eloquent-has-many-deep

Both packages now have versions for Laravel 11. The constraints in your `composer.json` don't need to be changed.

**Comment by danharrin** [comment]
Thanks @staudenmeir, will watch out for the tags

**Comment by mokhosh** [comment]
@danharrin seems like https://github.com/AnourValar/eloquent-serialize now supports Laravel 11 🎉

**Comment by danharrin** [comment]
I'm still unable to run CI because of spatie/eloquent-sortable which is required by spatie/laravel-tags @mokhosh

**Comment by mokhosh** [comment]
> I'm still unable to run CI because of spatie/eloquent-sortable which is required by spatie/laravel-tags @mokhosh

on it @danharrin https://github.com/spatie/eloquent-sortable/pull/171

**Comment by mokhosh** [comment]
https://github.com/spatie/eloquent-sortable/pull/171 done @danharrin

**Comment by mokhosh** [comment]
https://github.com/spatie/eloquent-sortable/releases/tag/4.2.0 tagged 🎉

👀

**Comment by mokhosh** [comment]
The failed tests seem to be related to `LazilyRefreshDatabase` but there are only two v10 changes to this trait. I didn't see any changes to it on `master`.
These are the changes:
https://github.com/laravel/framework/pull/49853
https://github.com/laravel/framework/pull/49914

It could also be https://github.com/laravel/framework/commits/master/src/Illuminate/Foundation/Testing/RefreshDatabase.php

**Comment by danharrin** [comment]
The first error is about a table not existing, maybe the rest of the errors are caught up because of that. Seems like maybe our migrations don't get picked up

**Comment by danharrin** [comment]
Seems to be a similar issue here, but it might be Passport related https://github.com/spatie/laravel-permission/pull/2605

**Comment by mokhosh** [comment]
im on mobile, and github is clunky on mobile, but i would check how laravel/passport has adapted its tests on `master` to support laravel11

**Comment by danharrin** [comment]
The PR I sent has not had the issue solved

**Comment by mokhosh** [comment]
I went through laravel/framework PRs and commits, but now I'm thinking it's a testbench issue. I created an issue here: https://github.com/orchestral/testbench/issues/393

**Comment by danharrin** [comment]
Thanks to @crynobone, the tests are now passing!

**Comment by mokhosh** [comment]
Awesome, thanks @crynobone and @danharrin

**Comment by AJenbo** [comment]
Glad to see you managed to solve it :+1:

**Comment by marcelloinfoweb** [comment]
Any news about this?

**Comment by mokhosh** [comment]
@marcelloinfoweb about what man?

**Comment by marcelloinfoweb** [comment]
> @marcelloinfoweb about what man?

If Filament is already supported in Laravel 11

**Comment by mokhosh** [comment]
It sure is @marcelloinfoweb

**Pull request merged**
