### PR TITLE
feat: add uzbek language support

### PR DESCRIPTION
**Pull request by asadbek-fayzulloev**
## Description

Added translated language resource in uzbek language

- [x] Visual changes (if any) are shown using screenshots/recordings of before and after.

## Code style

- [x] `composer cs` command has been run.

## Testing

- [x] Changes have been tested.

## Documentation

- [x] Documentation is up-to-date.

### CODE REVIEW

**Comment by asadbek-fayzulloev** [comment]
feat: Uzbek language support

**Comment by danharrin** [comment]
Hello, thanks for your contribution! However, we are not implementing new features / translations in v3, only bug and security patches to existing code.

You are able to define this language in your project's /lang/vendor directory, I think, so it shouldn't be a problem.

**Comment by asadbek-fayzulloev** [comment]
But most Uzbek php programmers use a Filament control panel. It is inconvenient to have to translate every time for a new project. These were the ones that new users appreciated

**Comment by danharrin** [comment]
All new projects will be built with v3 so I don't really think its too much of a problem?

**Pull request closed without merging**
