### PR TITLE
Support affix icon color

### PR DESCRIPTION
**Pull request by wychoong**
- [x] Changes have been thoroughly tested to not break existing functionality.
- [x] New functionality has been documented or existing documentation has been updated to reflect changes.
- [x] Visual changes are explained in the PR description using a screenshot/recording of before and after.

example
```php
Forms\Components\TextInput::make('postcode')
      ->debounce()
      ->suffixIcon(fn ($state) => $state ? 'heroicon-o-check-circle' : 'heroicon-o-x-circle', 
              iconColor: fn ($state) => $state ? 'success' : 'danger')
      ->prefixIcon(fn ($state) => 'heroicon-o-map-pin')
      ->required(),
```
image
image

### CODE REVIEW

**Comment by danharrin** [comment]
@zepfietje you can make the final call as to whether or not this gets merged, I'm neutral

**Comment by zepfietje** [comment]
Sure, I'll have to take a proper look.

**Comment by wychoong** [comment]
Hey, understand this is low priority. Is there anything missing to move this forward anytime soon?

**Comment by zepfietje** [comment]
Nothing missing, it's on my radar, @wychoong.

**Comment by danharrin** [comment]
Needs some short docs before merge please

**Comment by zepfietje** [comment]
Added docs, @danharrin.
I'm still finishing this PR before merging though.

**Review by zepfietje — APPROVED** [review]

**Pull request merged**
