### PR TITLE
Update 08-global-search.md

### PR DESCRIPTION
**Pull request by elmarzouguidev**

### CODE REVIEW

**Comment by zepfietje** [comment]
Closing this PR as in the example of a post you'd want to make the author and category foreign id columns non-nullable.

**Comment by elmarzouguidev** [comment]
What about when the category or author non exists it's throw an exception !!

**Comment by danharrin** [comment]
Okay, you can add `?->` to your code, but it's not necessary in our example since the category and author always exist.

**Comment by elmarzouguidev** [comment]
Hum that's Okay .. thanks

**Pull request closed without merging**
