### PR TITLE
spatie-laravel-translatable-plugin - Fix media bug

### PR DESCRIPTION
**Pull request by robertorinaldi-dev**
This should solve https://github.com/filamentphp/filament/issues/7591.
Or at least it works for me 😄

### CODE REVIEW

**Comment by atmonshi** [comment]
thank you

After a quick test, it seems to work for only the first language
If I edit, then change the language, then change the uploaded photo it won't save.

**Comment by robertorinaldi-dev** [comment]
You are right.
I made a patch that should fix it.
I don't like it very much but it seems to work. Unfortunately I don't have time to test it well right now.

**Comment by robertorinaldi-dev** [comment]
Basically, it always proceeds first with the currently active language and then continues with the others (copying the non-translatable fields from the first)

**Comment by atmonshi** [comment]
so far so good, will get more testers soon to confirm :)

**Comment by robertorinaldi-dev** [comment]
I don't know if it can create problems if there are other particular fields, like Repeater.
I also need to test it for the case where the media field is also translatable (in my case it is not)

**Comment by danharrin** [comment]
Can you please explain how this fixes the problem @robertorinaldi-dev ?

**Comment by robertorinaldi-dev** [comment]
Before the change $nonTranslatableData was taken in the initial state, which in the case of a media was a TemporaryUploadedFile and then it was being applied to all languages; this way when saving the second language (or third, fourth, ...) it resulted in what @awcodes noted [here](https://github.com/filamentphp/filament/issues/7591#issuecomment-1694483651), that is, it was trying to save the already saved file again and didn't find it anymore (it was deleted when saving the first language).
After the change, first it proceeds with saving the current language as it is, then it gets $nonTranslatableData form the language it just saved (therefore without TemporaryUploadedFile) and applies it to all other languages; this way it doesn't try to save the same file again.

I hope I explained myself well

**Comment by danharrin** [comment]
Thanks, and this isn't an issue with Create?

**Comment by robertorinaldi-dev** [comment]
How it works in creation is slightly different, so no, it doesn't seem to cause any problems to me

**Comment by danharrin** [comment]
Thanks mate, quality work as always

**Pull request merged**
