### PR TITLE
Feature: Table columns summary

### PR DESCRIPTION
**Pull request by studiowizjo**
With reference to #2929 it ads table columns summary feature:

image

Currently It supports columns: 
- TextColumn
- BooleanColumn
- Color Column
- IconColumn

For others I don't see use case (maybe for some of editable columns it should also work, but I haven't used it for now and have not inspected possibilities).

Usage:

```php
use Filament\Tables\Columns\Concerns\Summary\Sum;
use Filament\Tables\Columns\Concerns\Summary\Count;
use Filament\Tables\Columns\Concerns\Summary\FromTo;
use Filament\Tables\Columns\Concerns\Summary\CountUnique;

// --- Sum strategy ---
TextColumn('amount')
  ->summary(Sum::class), //sums all numeric values

// --- Count unique strategy ---
TextColumn('person')
  ->summary(CountUnique::class), //count all unique values

// --- Count strategy ---
TextColumn('person')
  ->summary(Count::class), //count all not null values

IconColumn::make('was_imported')
    ->boolean()
    ->summary(Count::class) //for boolean columns returns: ✓5 ✗4 -1 (5 true, 4 false, 1 null)

TextColumn::make('publish_at')
    ->date('d.m.Y')
    ->sortable()
    ->summary(Count::class) //for datetime columns returns: 6 past, 4 incoming

// --- From-to strategy ---

TextColumn::make('amount')
    ->summary(FromTo::class) //show range of displayed values, for numeric values returns: 100.67 - 1000.78

TextColumn::make('person')
    ->summary(FromTo::class) //For string values returns starting letters of first and last word sorted ascending. If letters matches, it takes next, up to 3 letters, eg: A - D, or: ABC - ABD

IconColumn::make('was_imported')
    ->boolean()
    ->summary(FromTo::class) //for boolean columns returns: "false" or "true" or "false - true"

TextColumn::make('publish_at')
    ->date('d.m.Y')
    ->sortable()
    ->summary(FromTo::class) //for datetime columns returns: from 01.01.2022 to 31.01.2022, splitted into two lines, to not stretch column. It respects user choosen date format or use default from config.
```

### CODE REVIEW

**Comment by studiowizjo** [comment]
I am not sure why test fails. Any prompt about this?

**Comment by ManojKiranA** [comment]
@studiowizjo I think the tests are failing because of https://github.com/laravel/framework/issues/44646

**Comment by studiowizjo** [comment]
Hmm, it doesn't look for me to be related. Is it?

**Comment by pxlrbt** [comment]
If we have this I think it should be combined with table footer.

**Comment by CreepPork** [comment]
Is it possible to add these summaries to the table header too?

**Comment by danharrin** [comment]
Thanks for the PR. The table builder has been internally refactored alot for v3, so we will be implementing this feature for v3 only - back-porting it to v2 would take a while. I will update this PR with a comment when I have merged this into v3.

**Comment by danharrin** [comment]
Implemented in #4910!

**Pull request closed without merging**
