### PR TITLE
fix: Disabled toggle

### LINKED ISSUE #7370: Toggle doesn't honor `disabled()`
### Package

filament/filament

### Package Version

v3.0.2

### Laravel Version

v10.17

### Livewire Version

v3-beta

### PHP Version

8.2

### Problem description

[Screencast from 08-02-2023 10:33:38 AM.webm](https://github.com/filamentphp/filament/assets/28250303/38a0b8cb-93ff-41f2-88a7-98bf0d1c099b)
As we can see from vide, toggle is not 'disabled' in view page (modal)

### Expected behavior

Cannot toggleable

### Steps to reproduce

Clone
Install
migrate --seed
Check user resource

### Reproduction repository

https://github.com/valpuia/v3-datetimepicker-bug

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by danharrin**
Fixes #7370.

### CODE REVIEW

**Comment by sakanjo** [comment]
@danharrin Thanks for the PR, but that doesn't fix the problem, right now it only disable the toggle if the property value is being changed but not when saving or updating which is a lot worse.

I've tried it before but it's not gonna help.

**Comment by sakanjo** [comment]
I think we should re-open the issue and revert the PR.

**Comment by danharrin** [comment]
None of the other fields are disabled onsave though, why should this one be?

**Comment by sakanjo** [comment]
the checkbox input is, replace `Toggle` with `Checkbox`.

**Comment by danharrin** [comment]
I don't understand why it needs to be? Thats much less of an issue than Toggle totally ignoring disabled() when its passed manually IMO

**Comment by sakanjo** [comment]
You are the author :smile:.

**Comment by danharrin** [comment]
Yeah but why do you think it needs disabling on save, what use case am I missing?

**Comment by sakanjo** [comment]
It's just a UX issue, since the all the elements on the form page gets disabled when fetching except the non-native input elements, like the button and the multi-select etc...

**Comment by sakanjo** [comment]
Livewire just doesn't handle non-native elements [supportDisablingFormsDuringRequest.js#L16](https://github.com/livewire/livewire/blob/main/js/features/supportDisablingFormsDuringRequest.js#L16).

**Pull request merged**
