### PR TITLE
Enhanced default `focusedDate` logic in `DateTimePicker`

### LINKED ISSUE #13988: DatePicker native False with Min and Max focus Chosen/Current month
### Package

filament/filament

### Package Version

3.1

### Laravel Version

11

### Livewire Version

3

### PHP Version

8.2

### Problem description

if the DatePicker is like this

now() = March

DatePicker::make( 'date' )
->minDate( April )
->maxDate( December )

If you click on the date field, the focus month will be minDate, not the current month.

### Expected behavior

If possible, if we can apply one of this options

1. we should have an option to choose which month to focus on when clicking the date field
2. auto focus the current day not the min date

### Steps to reproduce

have additional feature to set the focus date when click

### Reproduction repository (issue will be closed if this is not valid)

https://github.com/dharen008/demo

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by smiliyas**
## Description

Closes #13988 

**Before:** `minDate` was used as the default `focusedDate` when provided.  

**After:** The current date is set as the default `focusedDate` if it falls within the `minDate` and `maxDate` range; otherwise, `minDate` is used if provided, or `maxDate` if not.

## Functional changes

- [x] Code style has been fixed by running the `composer cs` command.
- [x] Changes have been tested to not break existing functionality.
- [ ] Documentation is up-to-date.

### CODE REVIEW

**Comment by danharrin** [comment]
Thank you!

**Comment by ziming** [comment]
This PR broke my site, I will send in a video later

**Comment by ziming** [comment]
Hi @smiliyas and @danharrin 

The latest release (3.2.109) broke my site and i believe this PR caused it. Here is a recording to demostrate it

CleanShot 2024-08-30 at 23 28 48

As you can see my date field, when clicked does not bring up anything

the code of my date field is like this

```php
// Working in 3.2.108 but not in 3.2.109
DatePicker::make('appointment_date')
                    ->native(false)
                    ->minDate(function (): CarbonInterface {
                        // some bunch of logic
                    })
                    ->maxDate(Carbon::now()->addWeeks(2))
                    ->disabledDates(function (Get $get): array {
                        // some bunch of logic
                    })
                    ->visible(fn (Get $get): bool => some logic here too)
                    ->live()
                    ->required(),
```

Hope it helps & I hope this PR can be reversed. Thank you

**Comment by daom89** [comment]
It's true i have same error:

```php
    public static function getDatePickerProgramacionFecha(): DatePicker
    {
        return DatePicker::make('fecha')
            ->label(__('general.labels.date'))
            ->required()
            //->rules(['required', 'date', self::getUniqueValidationRule()])
            ->timezone(config('app.timezone'))
            ->native(false)
            ->displayFormat('d/m/Y')
            ->format('Y-m-d')
            ->firstDayOfWeek(1)
            ->closeOnDateSelection()
            ->minDate(now()->subDays(1))
            ->maxDate(now()->addYear())
            ->disabledDates([
            ])
            ->suffixIcon('heroicon-o-calendar')
            ->prefixIcon('heroicon-m-calendar-days')
            ->prefixIconColor('primary')
            ->placeholder(__('general.placeholders.select_date'))
            ->weekStartsOnMonday()
            ->closeOnDateSelection()
            ->readonly(false); 
    }
```

**Comment by danharrin** [comment]
Reverting.

**Pull request merged**
