### PR TITLE
feature: Navigation sub groups

### PR DESCRIPTION
**Pull request by danharrin**
When a parent item is active, the sub items will be visible.

image

All items that have a parent item do not have an icon

Except when the sidebar is partially collapsed:

https://github.com/filamentphp/filament/assets/41773797/b8dd4ef9-31e8-4c74-b541-7a6296d925d7

We will not be going further than 3 navigation levels. This is the absolute limit we are prepared to support UI-wise in Filament.

### CODE REVIEW

**Comment by danharrin** [comment]
Please note that this does not cover top navigation, as there is extra complexity surrounding the fact that this is a "parent item" feature rather than another level of navigation groups, and there isn't an easy way to make the parent item clickable as well as being able to open the child item dropdown. This can be revisited at another time.

**Review by zepfietje — CHANGES_REQUESTED** [review]
Quick first thing I noticed from the screenshot.
The child items line and dot should start with a dot from the first item. Currently it starts with a line.

**Comment by danharrin** [comment]
IMO it should not do that, if the first child has a dot then it doesn't look like a child list anymore, it looks like it's at the top level of the parent

**Comment by zepfietje** [comment]
Hmm, fair point, but I still don't like it.

**Comment by danharrin** [comment]
As I said before, I'm just copying Shopify, this is basically how they do it 🤷

**Comment by zepfietje** [comment]
Yeah I noticed, though I prefer to not look at just 1 platform.
Having at least 3 gives us a more solid base.

**Comment by glennjacobs** [comment]
I am very much in favour of this and I think the design works OK. The solution is nice and simple (K.I.S.S.).

And of course, this would help us with our little Filament build ;-)

@zepfietje is it the UI design or the UX you're not sure on? If it's just the look of it, I'm happy to suggest a few ideas using Figma.

**Comment by zepfietje** [comment]
@glennjacobs, it's probably just the dot in front of nested items I'm unsure about. Probably we should also disallow having icons for nested items, as there's no visual hierarchy if you have icons for the parent and child items.

Apart from that, I've discussed the UX quite thoroughly with Dan and it turns out to basically be the same design as I suggested on that other PR.

Will review this PR, implement any fixes, and will let you know if there's something I'd love to have your thoughts on, @glennjacobs. 😊

Appreciate your input.

**Comment by glennjacobs** [comment]
I quite like the way Statamic do it. Might be worth checking out.

**Comment by zepfietje** [comment]
Yeah that's essentially the same thing, without icons for nested items.
GitHub does the same.

**Comment by danharrin** [comment]
As mentioned on Discord, no need to prevent icons from being added as they are used for the collapsed sidebar

**Comment by saade** [comment]
@zepfietje not related to this PR, but noticed that the the icons are not horizontally centered within collapsed sidebar. Worth going through this when reviewing this PR

image

**Comment by zepfietje** [comment]
@saade, is that a regression?
Please open a separate issue so we can have a look at the specifics (which OS/browser it occurs on, since I haven't run into it myself).

**Review by zepfietje — CHANGES_REQUESTED** [review]
Currently, the (also new in 3.1) sub-navigation feature doesn't support navigation subgroups. Maybe we need to move the sub-navigation to dropdowns instead of a select on mobile?

**Comment by saade** [comment]
> @saade, is that a regression? Please open a separate issue so we can have a look at the specifics (which OS/browser it occurs on, since I haven't run into it myself).

I don't think its a regression, its currently live in 3.x. I've just pasted here because of the design review you'll go through on this PR.

Your sidebar looks ok?

**Comment by danharrin** [comment]
Now supports subnavigation

**Review by zepfietje — APPROVED** [review]

**Pull request merged**
