### PR TITLE
Feat: Allow style attributes in html sanitizer config

### PR DESCRIPTION
**Pull request by awcodes**
Adds style as allowed attributes to the html sanitizer config to make it work with the new color system when using 'Htmlables'

### CODE REVIEW

**Comment by danharrin** [comment]
Refactored to use a different library for sanitising, how is it?

**Comment by awcodes** [comment]
I thought you did too, but when I pulled the lasted 3.x down it still had the other one. Maybe something just got messed up in local files. Sorry for the PR. I'll double check the new one in a couple hours.

**Comment by danharrin** [comment]
I did it in upg3 but this morning ported it over to 3.x

**Comment by awcodes** [comment]
Ah ok. Will let you know. Thanks.

**Pull request closed without merging**
