### PR TITLE
Add cell attributes to table columns

### PR DESCRIPTION
**Pull request by howdu**
Add attributes directly to the table cell `<td>` - `extraAttributes` is already added to a cell but it's nested 3 levels deep. 

Needed to change vertical alignment of particular column/cell.

### CODE REVIEW

**Comment by danharrin** [comment]
I think we can do the without modifying `cell.blade.php`. `<x-tables::cell {{ $column->getExtraCellAttributesBag() }}>`

**Comment by howdu** [comment]
@danharrin without it you get error from ComponentAttributeBag
> trim(): Argument #1 ($string) must be of type string, array given

**Comment by danharrin** [comment]
Sorry I mean `<x-tables::cell {{ $column->getExtraCellAttributeBag() }}>`

**Comment by danharrin** [comment]
Ah I was wrong, its actually possible through `:attributes` and `\Filament\Support\prepare_inherited_attributes()`

**Comment by danharrin** [comment]
Cleared up a few other places too

**Pull request merged**
