### PR TITLE
fixed scroll issue on wizard component

### PR DESCRIPTION
**Pull request by rafayrty**
- [ ] Changes have been thoroughly tested to not break existing functionality.
- [ ] New functionality has been documented or existing documentation has been updated to reflect changes.
- [ ] Visual changes are explained in the PR description using a screenshot/recording of before and after.

### CODE REVIEW

**Comment by rafayrty** [comment]
Issue fixed

**Comment by rafayrty** [comment]
The code has been updated on wizard.blade.php file to fix scrolling issue.

**Comment by rafayrty** [comment]
@danharrin

**Comment by danharrin** [comment]
Would be nice to have more info about the "scroll issue" as I have basically nothing to work from here. But I doubt this addition is gonna have negative effects.

**Comment by rafayrty** [comment]
Hi @danharrin This issue was occurring on the tabs component already refer for more info on:
https://github.com/filamentphp/filament/pull/6692

**Pull request merged**
