### PR TITLE
Fix double table border when no sorting or selection is enabled

### LINKED ISSUE #7632: Custom table row borders
### Package

filament/tables

### Package Version

v3.0.13

### Laravel Version

v10

### Livewire Version

_No response_

### PHP Version

8.2

### Problem description

If using `Split` and `Stack` within a table, the dividing border get rendered twice, currently also visible within the Demo's authors list:
https://demo.filamentphp.com/blog/authors

The primary cause seems to be [L503](https://github.com/filamentphp/filament/blob/3.x/packages/tables/resources/views/index.blade.php#L503)). 

There's also a double border between the header and the first row if you're not using at least one sortable column. Origin seems to be the divide-Class in [L381](https://github.com/filamentphp/filament/blob/3.x/packages/tables/resources/views/index.blade.php#L381)

As I do not know all the possbile combinations, I am quite stucked how to solve via a PR without breaking any other layout approach. Just wanted to bring this to your attention. If you have an idea how to solve this, I am happy to provide a PR. Thank you!

### Expected behavior

No double borders :)

### Steps to reproduce

Add `Split` and `Stack` columns to any table layout.
Test

### Reproduction repository

https://github.com/ajnsn/filament-demo-borders

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by ajnsn**
Fixes #7632 

- [x] Changes have been thoroughly tested to not break existing functionality.
- [x] Visual changes are explained in the PR description using a screenshot/recording of before and after.

This is a follow up for #7636. It changes the top part of the table to work with the parent `divide-y` by removing the css `hidden` class assignment when `! $isSelectionEnabled` and `! count($sortableColumns)` to an if-clause around the whole div. 

This is to hide the current double border within a grid table when you are not having selections enabled or any sortable columns.

As Dan already stated [here](https://github.com/filamentphp/filament/pull/7636#issuecomment-1675868848), the `hidden` class assignment must be there for a reason. But I cannot find any. If the table has no bulk actions, sortable columns etc, the part of the table imHo will always be hidden?

<details>
<summary>Before</summary>

before
before-dark
</details>

<details>
<summary>After</summary>

after
after-dark
after-with-sort-bulk
after-with-sort-bulk-dark
</details>

### CODE REVIEW

**Comment by zepfietje** [comment]
IIRC, `hidden` is there for performance reasons or some issue that occurred in the past, Dan said.

**Comment by wychoong** [comment]
fyi, its from one of my PR to solve an issue https://github.com/filamentphp/filament/pull/5977

**Comment by danharrin** [comment]
Can we replace `divide-y` with a class that accounts for hidden children? I feel like Tailwind does something very similar with `space-*`

**Comment by zepfietje** [comment]
@danharrin, that's what I used `x-bind:hidden` for in a couple of places, remember?

**Comment by danharrin** [comment]
@zepfietje is that an option here?

**Comment by ajnsn** [comment]
Thanks @wychoong for the reference!

Yes, we could apply the "hidden" attribute, either via an if statement or via `x-bind`, it's [described here](https://v2.tailwindcss.com/docs/upgrading-to-v2#add-hidden-to-any-template-tags-within-space-or-divide-elements). 

I can also change the PR, let me know which option do you prefer, Examples:

```blade
  <div
      @class([
          'flex items-center gap-4 gap-x-6 bg-gray-50 px-4 dark:bg-white/5 sm:px-6',
          'hidden' => (! $isSelectionEnabled) && (! count($sortableColumns)),
      ])
      {{-- x-bind:hidden="{{ (! $isSelectionEnabled) && (! count($sortableColumns)) }}" --}}
      {{-- x-bind:hidden="! (@js($isSelectionEnabled) || @js(count($sortableColumns)))" --}}
      @if (! $isSelectionEnabled && ! count($sortableColumns))
          hidden
      @endif
  >
```

In any case I see a lot of `@if`statements all over the place, e.g. alone in this div the `@if ($isSelectionEnabled && (! $isReordering))` and the `@if (count($sortableColumns))` are direct children. So for me it would be the increase the readability a lot if there's a simple `@if` above. This `hidden`-approach is difficult to interpret, imHo :)

**Comment by zepfietje** [comment]
It's hard for me to follow the exact issue and checking out the diff, but I guess simply using that Blade `@if` around everything is fine, as long as https://github.com/filamentphp/filament/pull/5977 isn't reintroduced?

**Comment by ajnsn** [comment]
Afaik the structure in this PR was different. Here are screens of this PR without anything (even without search). Looks good to me.

nothing
nothing-dark

**Comment by danharrin** [comment]
`@if ((! $isSelectionEnabled) && (! count($sortableColumns))) hidden @endif`

**Comment by zepfietje** [comment]
`hidden` attribute is only needed if a `divide-` child is rendered but hidden using `x-show`, @danharrin.

**Comment by danharrin** [comment]
Let's see if this presents any issues in the next release 👍

**Pull request merged**
