### PR TITLE
docs: How to disable clickable rows

### PR DESCRIPTION
**Pull request by jeffgreco13**

### CODE REVIEW

**Review by zepfietje — APPROVED** [review]

**Review by zepfietje — CHANGES_REQUESTED** [review]
Maybe we should add a section for record actions similar to the existing one about record URLs and add the new example there?

**Comment by jeffgreco13** [comment]
> Maybe we should add a section for record actions similar to the existing one about record URLs and add the new example there?

@zepfietje sure I can do this if you feel it's best! Just let me know which you prefer and I'll happily change and submit.

**Comment by zepfietje** [comment]
> Maybe we should add a section for record actions similar to the existing one about record URLs and add the new example there?

Agree, @danharrin?

**Comment by danharrin** [comment]
sure

**Comment by zepfietje** [comment]
@jeffgreco13, let us know when you've implemented the change by marking this PR as ready! 😊

**Comment by jeffgreco13** [comment]
Sorry this took a minute! @zepfietje

**Comment by zepfietje** [comment]
Sorry if my suggestion wasn't clear, @jeffgreco13.
I think we should add a `## Record actions (clickable rows)` section similar to the existing `## Record URLs (clickable rows)` section.

Then the snippet to disable the URL/action entirely can be added to both of these sections.
Clear? 😄

**Comment by jeffgreco13** [comment]
> Sorry if my suggestion wasn't clear, @jeffgreco13. I think we should add a `## Record actions (clickable rows)` section similar to the existing `## Record URLs (clickable rows)` section.
> 
> Then the snippet to disable the URL/action entirely can be added to both of these sections. Clear? 😄

@zepfietje I didn't see this comment and got busy!! So sorry I didn't check in and finish the job here. Thank you for completing it.

**Comment by zepfietje** [comment]
No worries, @jeffgreco13. Thanks for bringing this up!

**Pull request merged**
