### PR TITLE
Section heading with custom views

### PR DESCRIPTION
**Pull request by andresilvagomez**
Allow sections heading has custom views with his own behavior, not wrapped in h3

### CODE REVIEW

**Review by yelloalejo — APPROVED** [review]

**Review by JhonatanR89 — APPROVED** [review]

**Comment by danharrin** [comment]
I don't understand what you're trying to do

**Comment by danharrin** [comment]
This definitely doesn't work, with a normal heading there are 2 h3s and 2 icons?

**Comment by andresilvagomez** [comment]
Screenshot 2023-04-07 at 8 44 51 AM

@danharrin for example, in that case I built a UI with a button, but if is wrapper in h2 the button will not work correctly.

Or really build a complete header.

**Comment by danharrin** [comment]
This isn't the right solution, I think it's better if you create your own layout component instead of hacking the section to work how you want it to. You can copy the exact code from vendor so it is very easy.

**Pull request closed without merging**
