### PR TITLE
Add table cell loading skeleton

### LINKED ISSUE #13146: Table cell loading skeleton

### PR DESCRIPTION
**Pull request by binaryfire**
Continuation of https://github.com/filamentphp/filament/pull/9475 (which was accidentally closed).

Adds CSS-based table loading indicators

### CODE REVIEW

**Comment by malzariey** [comment]
Thank you for your wonderful effort, any updates on publishing this feature?

**Comment by zepfietje** [comment]
We'll release this once I've been able to work on it, @malzariey.

**Comment by karamyan94** [comment]
@zepfietje Thank you for your great job, any  estimate for when we will have this feature? )

**Comment by zepfietje** [comment]
No estimate as it still requires some work.

**Comment by zepfietje** [comment]
Going to create a fresh PR for this feature to make it more future-proof and handle missing cases. Thanks again for the groundwork and discussion on this everyone. 🙏

**Comment by binaryfire** [comment]
Just wondering if this will make it into v4? The lack of visual feedback on table state changes is still very noticeable on slow / high latency connections.

@archilex has implemented this in his Advanced Tables plugin: https://discord.com/channels/883083792112300104/883084832387760148/1330282909864820817. Maybe he could help

**Comment by Mathissou01** [comment]
---

In my case, I achieved this by registering a render hook for the resource list pages. It utilizes `wire:loading.delay` to display a floating overlay only when the table is refreshing.

You can add this in your `AppServiceProvider`'s `boot()` method:

```php
use Filament\Support\Facades\FilamentView;
use Filament\View\PanelsRenderHook;
use Illuminate\Support\Facades\Blade;

FilamentView::registerRenderHook(
    PanelsRenderHook::RESOURCE_PAGES_LIST_RECORDS_TABLE_BEFORE,
    fn (): string => Blade::render(<<<'HTML'
        <div
            wire:loading.delay
            x-transition:enter="transition ease-out duration-300"
            x-transition:enter-start="opacity-0 translate-y-2"
            x-transition:enter-end="opacity-100 translate-y-0"
            x-transition:leave="transition ease-in duration-200"
            x-transition:leave-start="opacity-100 translate-y-0"
            x-transition:leave-end="opacity-0 translate-y-2"
            class="absolute left-1/2 top-10 z-[99] -translate-x-1/2 transform"
        >
            <div class="flex items-center gap-3 p-4 bg-white rounded-xl dark:bg-gray-900 ring-1 ring-gray-900/5 dark:ring-white/10 border border-gray-200 dark:border-gray-800 shadow-lg">
                <svg
                    class="w-6 h-6 animate-spin text-primary-600 dark:text-primary-500"
                    xmlns="http://www.w3.org/2000/svg"
                    fill="none"
                    viewBox="0 0 24 24"
                >
                    <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
                    <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                </svg>

                <span class="text-sm font-semibold text-gray-700 dark:text-gray-200">
                    {{ __('Loading...') }}
                </span>
            </div>
        </div>
    HTML),
    scopes: [
        \App\Filament\Resources\X1Resource::class,
        \App\Filament\Resources\X2Resource::class,
    ],
);

```

Hope this helps!

**Pull request closed without merging**
