### PR TITLE
Update 07-relation-managers.md

### PR DESCRIPTION
**Pull request by VasasA**
Attaching with pivot attributes: Instead of using $action->getRecordSelect(), you can create a custom select field.

### CODE REVIEW

**Comment by danharrin** [comment]
You could just chain config onto `$action->getRecordSelect()->label('Test')`? Then you don't need to worry about the field name.

**Comment by zepfietje** [comment]
I don't think we need a separate section for this, as above-mentioned approach should be quite obvious.

Reopen if you disagree, @danharrin.

**Comment by VasasA** [comment]
@danharrin  @zepfietje 

This is weird: I have tested: the `$action->getRecordSelect()->label('Test')` doesn't work.
These work: `->options()`, `->required()`, `->searchable()`

**Comment by danharrin** [comment]
What about it doesnt work?

**Comment by VasasA** [comment]
@danharrin 
The label isn't displayed. The select field hasn't got label.

**Comment by danharrin** [comment]
Ah, try `->disableLabel(false)`

**Comment by VasasA** [comment]
👍  It works, thank You very much!
Should we mention this solution in the documentation?
(The `disableLabel` does not give results when searching in the documentation of filamentphp.com.)

**Comment by danharrin** [comment]
`disableLabel()` could be added to the Fields documentation aside the main label docs

**Pull request closed without merging**
