### PR TITLE
feat: collapsible chart widget

### PR DESCRIPTION
**Pull request by SupianIDz**
## Description

This allows wide charts to be collapsed when not needed so they don't interfere with tables or anything else.

related : https://github.com/filamentphp/filament/discussions/10036

By default collapsible is false, but users can set it to collapsible, by adding the code below to the Chart Widget class

```php
protected static bool $collapsible = true;
```

or

```php
public function isCollapsible() : bool
{
   // return true;
   return static::$collapsible;
}
```

## Visual changes

Without filters.

https://github.com/user-attachments/assets/e6d4208c-adcc-4027-924b-5ae584956696

With filters.

https://github.com/user-attachments/assets/a04056a7-4431-42c9-91c8-da054b478bb5

## Functional changes

- [x] Code style has been fixed by running the `composer cs` command.
- [x] Changes have been tested to not break existing functionality.
- [ ] Documentation is up-to-date.

### CODE REVIEW

**Comment by SupianIDz** [comment]
Update preview with filters.
https://github.com/user-attachments/assets/7bee205c-3099-4128-ab00-2628efb10e8b

**Comment by danharrin** [comment]
Hi, apologies but we are no longer accepting new features for v3 as per #13744. Also, please check out our [contributing guide](https://filamentphp.com/docs/3.x/support/contributing#development-of-new-features) which talks about proposing the feature before submitting the PR, to ensure you aren't spending time building something that we won't merge.

I would accept a PR for this feature when v4 is released, if you are still interested. Thank you!

**Comment by andrefelipe18** [comment]
@danharrin Will this be added in V4?

**Comment by danharrin** [comment]
I do not believe this has been PRed into v4 yet

**Comment by andrefelipe18** [comment]
@danharrin is there any problem with me adding this to v4?

**Comment by danharrin** [comment]
No but to be honest I would prefer it if you waited until it was released so that it does not increase my pre-release workload

**Pull request closed without merging**
