### PR TITLE
fix: Widgets dissapearing

### LINKED ISSUE #7567: Uncaught TypeError: "Snapshot missing on Livewire component with id: " is not a constructor
### Package

filament/filament

### Package Version

v3.0.12

### Laravel Version

v10.18.0

### Livewire Version

v3.0.0-beta7

### PHP Version

PHP 8.2

### Problem description

Having multiple widget classes on a resource causes dom diffing issues and causes the whole page to break

### Expected behavior

When livewire updates are made on a page with multiple widgets, the page should work without livewire issues breaking everything.

### Steps to reproduce

Load the repo I added below. Create a speaker and view that record (you need to get to the ViewSpeaker class).

When you get to that page and click a livewire button (for example, change the relation manager from one to the other), you'll see one of the widgets disappears. The dom diffing loses track of one of them, and everything ends up breaking. There is a console error that reads:

`Uncaught TypeError: "Snapshot missing on Livewire component with id: " is not a constructor`

Somehow those components are not getting a Livewire ID it seems.

I've tried many ways of adding a unique identifier to those widgets, but no matter what I do (wire:key, standard html id), after the first livewire update it loses track of them.

### Reproduction repository

https://github.com/iAmKevinMcKee/filament3

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by danharrin**
Fixes #7567.

### CODE REVIEW

**Comment by ZevedoAFT** [comment]
This problem also happens when you use multiple Forms\Components\Livewire in the same form. All the Forms\Components\Livewire disappear after save except the last one in the form

**Comment by danharrin** [comment]
Add a `key()` https://filamentphp.com/docs/3.x/forms/advanced#inserting-livewire-components-into-a-form

**Comment by ZevedoAFT** [comment]
Hi Dan,
Thank you for your quick answer but that doesn't solve the problem.

That's the code in the form:
Forms\Components\Livewire::make(Summary::class)->key('service-summary-livewire'),

Forms\Components\Livewire::make(CustomerCard::class)->key('service-customer-livewire'),

Forms\Components\Livewire::make(SatCard::class)->key('service-sat-livewire'),

Forms\Components\Livewire::make(ProductCard::class)->key('service-product-livewire'),

If I change the order of the Components, the one I put in last does not disappear after save, all the other components disappear.

I'm using Filament v3.1.
Once again thank you for your help and for your awesome work.

**Comment by danharrin** [comment]
Please open an issue with a reproduction repository

**Comment by ZevedoAFT** [comment]
I created a new project with the reproduction repository and the problem didn't ocurred. So I updated my filament from 3.1 to 3.2 and the problem was resolved in my project. Thank you

**Pull request merged**
