### PR TITLE
Fix KeyValue could not add row

### LINKED ISSUE #7785: KeyValue form component collapsing before can actually enter anything into the new rows when clicking add row
### Package

filament/filament

### Package Version

v3.0.22

### Laravel Version

v10.10

### Livewire Version

v3

### PHP Version

PHP 8.1.0

### Problem description

When clicking the add row button the table flashes to indicate the creation of the row, but quickly collapses back to no rows.

### Expected behavior

A row to be created, and able to enter information into.

### Steps to reproduce

This repository should demonstrate it on the user create page when you login to the admin panel. I notice (on windows) if I use sail down that the page, if it's still loaded will then start working.

### Reproduction repository

https://github.com/Cigoler/fv3-keyvalue-issue

### Relevant log output

_No response_

Link to discord help topic: https://discord.com/channels/883083792112300104/1140992574476267610

### PR DESCRIPTION
**Pull request by killjin**
- [x] Changes have been thoroughly tested to not break existing functionality.
- [x] New functionality has been documented or existing documentation has been updated to reflect changes.
- [x] Visual changes are explained in the PR description using a screenshot/recording of before and after.

This is change $wire.entangle to $wire.$entangle.

I guess $wire.entangle in Livewire 3.0 beta9 should be surrogate $wire.$entangle('state', true), adding $ it works as expected.

Under Livewire 3.0 beta7, the entangle will not be modified in real time.

This fixes a bug where KeyValue could not add rows in Livewire 3.0 beta9.

Fix #7785

### CODE REVIEW

**Comment by danharrin** [comment]
I don't get it, whats the difference?

**Comment by killjin** [comment]
I tried to change from $wire.entangle to $wire.$entangle. Adding a null value will not generate a request, and any value change will also have an interval, which is defer. 

https://github.com/filamentphp/filament/issues/7785
This problem has been solved after modification, and I don't understand the specific implementation of livewire.

**Comment by killjin** [comment]
> I don't get it, whats the difference?

https://github.com/livewire/livewire/blob/main/js/%24wire.js
Added code this week:
```js
return new Proxy({}, {
        get(target, property) {
            if (! component) component = closestComponent(el)

            if (property === 'entangle') {
                return generateEntangleFunction(component, cleanup)
            }

            return component.$wire[property]
        },

        set(target, property, value) {
            if (! component) component = closestComponent(el)

            component.$wire[property] = value

            return true
        },
    })
```
```js
if (property === 'entangle') {
    return generateEntangleFunction(component, cleanup)
}
```
However:
```js
wireProperty('$entangle', (component) => (name, live = false) => {
    return generateEntangleFunction(component)(name, live)
})
```

generateEntangleFunction:
https://github.com/livewire/livewire/blob/main/js/features/supportEntangle.js

$entangle returns the closure (name, live=false) with the default parameters of live, and re-nested a layer of generateEntangleFunction, while entangle uses the built-in obj's live = true.

**Comment by danharrin** [comment]
I don't really understand why `$entangle` is a better syntax, but ok :) Thanks

**Comment by margarizaldi** [comment]
Hi @killjin would you like to see https://discord.com/channels/883083792112300104/956270111176679516/1144318914961096776

I think $wire.$entangle causes this issue #7940 

Could you help to fix that?

**Pull request merged**
