### PR TITLE
widgets[feature]: separates chart-widget backgroundColor and borderColor

### PR DESCRIPTION
**Pull request by bezhanSalleh**
- [x] Changes have been thoroughly tested to not break existing functionality.
- [ ] New functionality has been documented or existing documentation has been updated to reflect changes.
- [x] Visual changes are explained in the PR description using a screenshot/recording of before and after.

This PR separates the backgroundColor and borderColor and uses the colors defined by filamnet's panel theme and makes the border use the solid color defined while for background a shade of it just like v2. Doing so also fixes the current responsiveness of the chart as well.

Current:
https://github.com/filamentphp/filament/assets/10007504/5ab5c6d3-8658-4ec9-8c20-e0c1bbbf80ff

PR:
https://github.com/filamentphp/filament/assets/10007504/4f10249b-8039-45a2-a848-c9ac59e8564b

### CODE REVIEW

**Comment by zepfietje** [comment]
Hmm, we had removed the background color on purpose.
Does this add it back to all charts by default?

**Comment by bezhanSalleh** [comment]
> Hmm, we had removed the background color on purpose. Does this add it back to all charts by default?

yeah, for all widget charts. I did ask dan in the support channel before making the PR.
Having same border color and background color makes the charts kinda seem funky and ***it forces plugin developers to hardcode them*** and given that filament has themeing and not being able to use it, makes it kinda counter intuitive.

**Comment by zepfietje** [comment]
@danharrin @bezhanSalleh this changed the fill of the data points:

Screenshot 2023-07-29 at 10 56 32

**Comment by zepfietje** [comment]
Looks weird in dark theme as it doesn't cover the line:

Screenshot 2023-07-29 at 10 57 31

**Comment by zepfietje** [comment]
No big issue though.
I see you used the background color of the stats overview widget card chart so that's consistent at least. 👍
Thanks, @bezhanSalleh!

**Comment by danharrin** [comment]
Yeah I saw. Do you prefer them with a solid fill? I think I do, but I don't really mind

**Comment by zepfietje** [comment]
I think the solid fill looks better in the way we use it, especially with this dark mode bug. But let's just leave it as is for now.

**Comment by danharrin** [comment]
its ok I'll fix it

**Pull request merged**
