### PR TITLE
show sidebar group collapse icon when sidebar is collapsed

### PR DESCRIPTION
**Pull request by maherelgamil**
this is the final result

image

### CODE REVIEW

**Comment by danharrin** [comment]
Thoughts @pxlrbt?

**Comment by maherelgamil** [comment]
> Thoughts @pxlrbt?

Just we help his thoughts 😄

**Comment by pxlrbt** [comment]
I can see that the collapsed sidebar is not that good when you have a lot of collapsed groups. But I feel like this clutters the collapsed sidebar. You still have no idea which caret belongs to which group. This would at least require a tooltip for the carets.

In my case I'd prefer to toggle the sidebar open the group I need and collapse it again. But I also don't have projects with that many resources yet.

**Comment by maherelgamil** [comment]
@pxlrbt @danharrin 

I think 
> toggle the sidebar open the group I need and collapse it again

is a good solution for this case, I thought about this solution also and tried to solve the current state.

so If there is consensus on this, I will start to change it

**Comment by ryangjchandler** [comment]
I wonder if maybe we uncollapse groups when the sidebar is closed?

**Comment by pxlrbt** [comment]
> I thought about this solution also and tried to solve the current state.

What do you mean? That's the current state. Manually open the sidebar, adjust your collapsed groups and collapse the sidebar again. But it's more manual work.

**Comment by pxlrbt** [comment]
> I wonder if maybe we uncollapse groups when the sidebar is closed?

Thought about this too when I first implemented this. But I thought that groups are collapsed for a reason and didn't want to interfere with the users decision. At least we should restore them when opening the sidebar again.

**Comment by ryangjchandler** [comment]
Yeah, definitely restore them. If we use `$store.sidebar.isOpen` inside of the collapse logic for the groups, it'll just work anyway.

**Comment by maherelgamil** [comment]
@pxlrbt 

I mean, trying to fix the current shape, like this 

image

**Comment by maherelgamil** [comment]
> I wonder if maybe we uncollapse groups when the sidebar is closed?

I think also, it's a good solution in this case

**Comment by ryangjchandler** [comment]
How about this: 
CleanShot 2022-03-24 at 11 15 57

**Comment by danharrin** [comment]
I back Ryan's suggestion

**Comment by pxlrbt** [comment]
Yeah, uncollapsing them is probably the best solution.

**Comment by pxlrbt** [comment]
I thought it would shift the items too much but the current solutions looks nasty with many collapsed groups 😅

**Comment by pxlrbt** [comment]
@ryangjchandler As you already have it up and running do you wanna PR that? 😅

**Comment by ryangjchandler** [comment]
Yeah, might as well open the pr haha

**Comment by ryangjchandler** [comment]
Closing in favour of https://github.com/laravel-filament/filament/pull/2003.

**Pull request closed without merging**
