### PR TITLE
Add color classes

### PR DESCRIPTION
**Pull request by zepfietje**
- [x] Changes have been thoroughly tested to not break existing functionality.
- [ ] New functionality has been documented or existing documentation has been updated to reflect changes.
- [ ] Visual changes are explained in the PR description using a screenshot/recording of before and after.

---

- Adds CSS classes to target elements based on their color (gray or custom).
- Adds CSS class hooks deprecation comments (https://github.com/filamentphp/filament/issues/8064).

### CODE REVIEW

**Comment by danharrin** [comment]
Hm, I think we should remove the deprecated comments to reduce the payload size. Maybe the active sidebar item is ok, but definitely not the button. And we should keep it consistent and not do it anywhere. Maybe a Blade comment is ok though.

**Comment by zepfietje** [comment]
Yeah I just added this as a concept, since you mentioned on that issue.
But I'll just move to Blade comments.

**Comment by danharrin** [comment]
Since this breaks the code formatter, we're just going to need to remove those comments for now if you want this merged in.

**Comment by zepfietje** [comment]
Worked around it by "escaping" the `@`.
Have created an issue in the formatter repo: https://github.com/Stillat/blade-parser-typescript/issues/79.

**Comment by zepfietje** [comment]
Ready for merge now, @danharrin.

**Pull request merged**
