### PR TITLE
Update Tailwind config preset and stub

### PR DESCRIPTION
**Pull request by zepfietje**
Edit: I just realized we probably want a different stub for apps using `filament/app` and those without. Thoughts?

### CODE REVIEW

**Comment by danharrin** [comment]
I agree, as the CSS-var based colours don't apply outside of the app framework

**Comment by danharrin** [comment]
The scaffolding isn't for building themes, it's for the individual packages. So I think how it is right now is fine

**Comment by zepfietje** [comment]
But we don't offer a scaffold for building themes?

**Comment by danharrin** [comment]
Not yet, that should probably be a separate `make:filament-theme` command

**Comment by danharrin** [comment]
this is the install command, remember

**Comment by zepfietje** [comment]
I know, but personally I often also need a Tailwind config for the non-Filament part of the app. Compile it all into a single stylesheet. But I see how this isn't needed if you're not customizing any of the Filament styling except colors and such for which PHP setters exist. Let's just leave this as is then.

**Comment by danharrin** [comment]
And if we want to push people towards using the app framework for everything then...

**Comment by zepfietje** [comment]
Agree. Marketing sites would be separate and out of scope for Filament core. 👍

**Pull request closed without merging**
