### PR TITLE
Fix: modal issues

### PR DESCRIPTION
**Pull request by awcodes**
Fixes modal state and DOM diffing issues by dispatching an event from the modal close which then unmounts the current action.

### CODE REVIEW

**Comment by danharrin** [comment]
that's fixed it on my end!

**Comment by awcodes** [comment]
This looks good to me and I like the implementation better.

**Comment by Roxeen12** [comment]
I think there was an issue 
image

**Comment by zepfietje** [comment]
How do you think it's related to this PR, @Roxeen12?

Would be best to open a new bug report so we can look into the issue.

**Comment by danharrin** [comment]
Yeah we absolutely need a reproduction repo in an issue to be able to fix this

**Pull request merged**
