### PR TITLE
Add current state to the error messages on column test assertions

### PR DESCRIPTION
**Pull request by gehrisandro**
## Description

This PR improves the assertion error message for column state tests by adding the current value.

Here is an example of the changed message:

_Failed asserting that a table column with name [title] has value of [My title] for record [1] on the [App\Models\Post] component. **Current value: [Other Title]**_

## Functional changes

- [x] Code style has been fixed by running the `composer cs` command.
- [x] Changes have been tested to not break existing functionality.
- [x] Documentation is up-to-date.

### CODE REVIEW

**Comment by danharrin** [comment]
I haven't tried this, but would switching from `assertTrue` to `assertSame` give the user more information here?

**Comment by gehrisandro** [comment]
I will give it a try.

**Comment by gehrisandro** [comment]
@danharrin `assertSame` works fine, but I went with `assertEquals` because before it used lazy comparison `==`.

**Comment by danharrin** [comment]
Thanks!

**Pull request merged**
