### PR TITLE
Hide Microsoft Edge password reveal control

### PR DESCRIPTION
**Pull request by zepfietje**
## Description

Follow-up to https://github.com/filamentphp/filament/pull/10956. Hides the native Microsoft Edge password reveal control when Filament's password reveal actions are used.

- [x] Visual changes (if any) are shown using screenshots/recordings of before and after.

## Code style

- [x] `composer cs` command has been run.

## Testing

- [x] Changes have been tested.

## Documentation

- [x] Documentation is up-to-date.

### CODE REVIEW

**Comment by zepfietje** [comment]
Handled this here for you, @andrewdwallo.

**Comment by andrewdwallo** [comment]
@zepfietje Awesome! Glad you found the solution regarding the affix issue. I tried that using CSS but the result wasn't perfect.

**Comment by andrewdwallo** [comment]
Also I didn't know the & in `[&::-ms-reveal]` is supported in this context.. does that not require postcss nesting plugin?

**Comment by zepfietje** [comment]
> Also I didn't know the & in `[&::-ms-reveal]` is supported in this context.. does that not require postcss nesting plugin?

The `&` here targets the current element. It's a Tailwind CSS feature of arbitrary selectors. I've checked the compiled CSS and it looks ok. Let me know once you've been able to test this in a real Edge browser on Windows though.

**Comment by andrewdwallo** [comment]
Oh okay, sounds good 👌🏻

**Pull request merged**
