### PR TITLE
Fix exporting relationship values

### PR DESCRIPTION
**Pull request by maartenpaauw**
## Description

- [ ] Visual changes (if any) are shown using screenshots/recordings of before and after.

## Code style

- [ ] `composer cs` command has been run.

## Testing

- [x] Changes have been tested.

## Documentation

- [ ] Documentation is up-to-date.

### CODE REVIEW

**Comment by maartenpaauw** [comment]
Fixes #10835

**Comment by danharrin** [comment]
Can you please explain the reduce?

**Comment by maartenpaauw** [comment]
@danharrin Assume we have the following columns configured:

```php
public static function getColumns(): array
{
    return [
        ExportColumn::make('spot.name')
            ->label('Spot name'),
        ExportColumn::make('allocation.contact.name')
            ->label('Contact name'),
        ExportColumn::make('uuid'),
    ];
}
```

I first dot the entire collection which results in the following:

```php
[
  "spot.name.isEnabled" => true,
  "spot.name.label" => "Name",
  "allocation.contact.name.isEnabled" => true,
  "allocation.contact.name.label" => "Contact name",
  "uuid.isEnabled" => true,
  "uuid.label" => "Uuid",
]
```

the reduce will manipulate the collection into the following:


```php
[
  "spot.name" => [
    "isEnabled" => true,
    "label" => "Name",
  ],
  "allocation.contact.name" => [
    "isEnabled" => true,
    "label" => "Contact name",
  ],
  "uuid" => [
    "isEnabled" => true,
    "label" => "Uuid",
  ],
]
```

**Comment by danharrin** [comment]
Yeah, after reading it a few times I don't understand why we would want an array with 2 levels of nesting?

**Comment by danharrin** [comment]
Ahhhh right yeah, makes sense

**Comment by danharrin** [comment]
Thanks

**Pull request merged**
