### PR TITLE
Add supporting to initial audio or video in upload file field

### PR DESCRIPTION
**Pull request by sbc640964**
Add supporting to initial audio or video to upload file

## Description

Until now the input could not play sound or video from a default or initial set, from now on it will be able to play them.

## Testing

- [x] Changes have been tested.

## Documentation

- [ ] Documentation is up-to-date.

### CODE REVIEW

**Comment by danharrin** [comment]
Can you please compile the assets with `npm run build`?

**Comment by danharrin** [comment]
Did you test this locally?

**Comment by sbc640964** [comment]
> Can you please compile the assets with ?`npm run build`

I got a little confused with this, how do I carry out your request?

**Comment by sbc640964** [comment]
> Did you test this locally?

Of course

**Comment by danharrin** [comment]
How did you test this locally without compiling the JavaScript?

**Comment by sbc640964** [comment]
> How did you test this locally without compiling the JavaScript?

Maybe I don't understand correctly,
When I do npm run build on a laravel project it also compiles laravel app assets, not just the package, am I wrong?

**Comment by danharrin** [comment]
You have to download the package repository, `npm install` and then run the command. What were the steps you took to ensure that this change works?

**Comment by sbc640964** [comment]
> You have to download the package repository, `npm install` and then run the command. What were the steps you took to ensure that this change works?

To testing, I changed a temporary file in the vendor file, I saw that it does work.

OK. Anyway I will follow the rules [here](https://github.com/filamentphp/filament?tab=readme-ov-file#contributing).
And then I will compile the assets and push the change, I Hope that I'm understood correctly.

**Comment by danharrin** [comment]
Changing this vendor file will not make a difference. To start, it isn't compiled, and secondly, it then needs to be published to /public.

So can you please double check that this is actually a problem that needs this fix?

**Comment by danharrin** [comment]
Hey @sbc640964, any updates?

**Comment by danharrin** [comment]
I've compiled it for you

**Comment by sbc640964** [comment]
> I've compiled it for you

Thank you!
you are awesome! I'm just busy and haven't found time for it (when I mean I'm also afraid maybe I didn't understand you correctly), anyway after you did it I got the idea, I hope it helps next time... :)

**Pull request merged**
