### PR TITLE
Add missing Spanish localizations

### PR DESCRIPTION
**Pull request by andresilvagomez**

### CODE REVIEW

**Review by yelloalejo — APPROVED** [review]

**Review by JhonatanR89 — APPROVED** [review]

**Comment by pathros** [comment]
@andresilvagomez There's a misspelling in "Selecionar/Deselecionar".  That should be "Seleccionar/Deseleccionar" (one "c" is missing in both words) in `packages/tables/resources/lang/es/table.php` file on lines 20 and 24.

**Comment by zepfietje** [comment]
Could you create a PR for this, @pathros?

**Comment by pathros** [comment]
@zepfietje , all right. I have just created a [PR](https://github.com/filamentphp/filament/pull/6150) for that.

**Comment by zepfietje** [comment]
Thanks, @pathros!

**Pull request merged**
