### PR TITLE
Add alias for color shades in button component

### PR DESCRIPTION
**Pull request by dvanscott**
- [x] Changes have been thoroughly tested to not break existing functionality.
- [ ] New functionality has been documented or existing documentation has been updated to reflect changes.
- [ ] Visual changes are explained in the PR description using a screenshot/recording of before and after.

Noticed this one when chatting with Dan about the other PRs I submitted.

### CODE REVIEW

**Comment by zepfietje** [comment]
@dvanscott @danharrin, I didn't add this yet as I was planning to move the color styles closer to the actual element (label, icon, etc.). This will impact the shades alias as well, as `button` no longer covers all then. Would be a breaking change, wouldn't it?

Let's discuss and update the approach before tagging a new release.

**Comment by danharrin** [comment]
This is currently on the outer element. @dvanscott as long as you `addShades()` instead of replacing them, you should be ok, as child elements will inherit the new shades.

**Comment by zepfietje** [comment]
That's right. 👍

**Comment by dvanscott** [comment]
@danharrin @zepfietje sounds good. Is it temporary that I'll need to use `addShades` instead of `replaceShades` or will that always be the case?

**Comment by zepfietje** [comment]
Advised until I've refactored this part. Though generally `addShades` is a little safer than replacing.

**Pull request merged**
