### PR TITLE
Load `az` locale from FilePond

### PR DESCRIPTION
**Pull request by nasimic**
- [x] Changes have been thoroughly tested to not break existing functionality.
- [x] New functionality has been documented or existing documentation has been updated to reflect changes.
- [x] Visual changes are explained in the PR description using a screenshot/recording of before and after.

### CODE REVIEW

**Comment by zepfietje** [comment]
Do we still need to wait for a new version of FilePond to be tagged?

**Comment by nasimic** [comment]
@zepfietje I guess we don't. Looks like FilePond not tagging offen 😅

**Comment by zepfietje** [comment]
Yeah that's why I'm wondering. 😅
We can't merge this PR if it's not available in FilePond yet, right?

**Comment by nasimic** [comment]
@zepfietje They are only pushing changes to master branch over 2 years. 
Would be great if they release a tag, but seems not going to happen. I guess there is no polite way to force update for end users 😄

**Comment by zepfietje** [comment]
What do you think, @danharrin?

**Comment by danharrin** [comment]
So isnt this PR broken without Filepond tagging? It hasnt been compiled

**Comment by zepfietje** [comment]
Yeah I think so.

**Pull request closed without merging**
