### PR TITLE
Replace abandoned html sanitizer with Symfony version

### PR DESCRIPTION
**Pull request by oddvalue**

### CODE REVIEW

**Comment by oddvalue** [comment]
Ah, guessing this hasn't been updated due to the lack of PHP 8.0 support.
Ignore me, as you were.

**Comment by tfevens** [comment]
Could this PR be reviewed and potentially pulled into 3.x?  One less dependency on an abandoned package.

**Comment by danharrin** [comment]
it already is?

**Comment by tfevens** [comment]
Apologies if it is.  I installed 3.0 beta earlier (`composer require filament/filament:"^3.0"`) and when completed it gave me abandoned package warnings:

Package league/uri-parser is abandoned, you should avoid using it. No replacement was suggested.
Package tgalopin/html-sanitizer is abandoned, you should avoid using it. Use symfony/html-sanitizer instead.

```
composer why league/uri-parser
tgalopin/html-sanitizer 1.5.0 requires league/uri-parser (^1.4.1)

composer why tgalopin/html-sanitizer
filament/support v3.0.0-alpha121 requires tgalopin/html-sanitizer (^1.5)```

**Comment by danharrin** [comment]
Thats weird, I can't see where in the codebase it is still required? It's been out of the codebase for a few weeks now.

**Comment by tfevens** [comment]
It was here - `packages/support/composer.json` - but as you say, it's not showing in GH.
So I ran a composer show to see which version of filament is installed:

```
composer show filament/filament
name     : filament/filament
descrip. : Effortlessly build TALL-stack apps and admin panels.
keywords :
versions : * v3.0.0-alpha121
```
No idea why I got the alpha version... I ran a `composer update` and see that it's pulled in `v3.0.0-beta4` and I'm not getting the notices.

Thanks @danharrin!

**Comment by danharrin** [comment]
Did you have LW2 installed while you installed Filament maybe?

**Comment by tfevens** [comment]
Was a brand new laravel install.  Had nothing else installed in project.
Checked any globally installed packages, but there was nothing there either.

**Pull request closed without merging**
