### PR TITLE
Merge extraAttributes with DatePicker button 

### PR DESCRIPTION
**Pull request by daggemarren**
Merge extraAttributes with DatePicker button  so you can modify roundness and paddings etc.

### CODE REVIEW

**Comment by danharrin** [comment]
I wonder how we can make this consistent across all fields & layout components, because at the moment there's so much variation.

**Comment by ekandreas** [comment]
Perhaps @daggemarren can provide us with more fixes around these fields that need adjustments. We like the PR's :-)

**Comment by danharrin** [comment]
I'm going to hold off on merging this PR until we find a consistent way to handle this across components.

**Comment by danharrin** [comment]
Alright, gonna close this and someone can open a discussion / submit a new PR if they want to talk to people about making this behaviour consistent. At the moment though, I've got lots of issues & features to work though so I'm not able to dedicate time to this myself.

**Comment by ekandreas** [comment]
I really don't understand this action. 
Instead of embracing a bugfix the PR is closed?

**Comment by danharrin** [comment]
> I really don't understand this action.
> Instead of embracing a bugfix the PR is closed?

@ekandreas Hi, thanks for the feedback. I still stand by my decision. While this might be a "bug fix" for one field, it will continue to cause inconsistency across all fields of the project. I did not say that this was unappreciated, nor that this is an issue we will not solve. I just said that I am holding off merging this fix until we find a consistent solution across all components.

If you'd like to see this fix merged, please suggest to me how we can make attribute merging consistent. I'm happy to discuss it here, or in a Discussion. Hope to hear from you soon!

**Comment by danharrin** [comment]
Hey @daggemarren @ekandreas, I've settled on a solution for this. I've made the changes in #935.

- All `extraAttributes()` are now always merged onto the outer HTML element of the component.
- The new `extraAlpineAttributes()` method always merges attributes onto the root Alpine element (the one containing `x-data`).
- The `extraTriggerAttributes()` method (specifically for date pickers), merges onto the trigger button. In the future, if other custom attribute bags are required for other components, we may use this syntax as a template.

**Pull request closed without merging**
