### PR TITLE
Fix: Add id for dom diff

### LINKED ISSUE #4680: Select all button still shows after selecting when filtered
### Package

filament/tables

### Package Version

2.16.36

### Laravel Version

9.36.4

### Livewire Version

2.10.6

### PHP Version

8.1.9

### Problem description

When select all searching and filtering result don't disappear Select All action

image

### Expected behavior

search or filter table then select all items when click on `Select All #` don't disappear .

### Steps to reproduce

Demo app tables for ex: https://demo.filamentphp.com/shop/products

### Reproduction repository

https://github.com/filamentphp/demo

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by awcodes**
Adds an id to force a dom update when $allRecordsCount changes. This is a know issue with x-show and livewire variables.

#4680

### CODE REVIEW

**Comment by zepfietje** [comment]
Shouldn't `wire:key` be used instead?

**Comment by awcodes** [comment]
This is an issue with alpine not livewire. A wire key won't force the the span to change the variable inside x-show.

**Comment by awcodes** [comment]
Just ran a test, after Dan told me he prefers wire:key, and wire:key had no effect on this when using a blade variable inside an x-show directive.

Seems like setting an id is the only way to get this to update properly in alpine.

**Comment by danharrin** [comment]
Okay understood, but could you please make sure the ID follows the same structure as other wire:keys on the page? Because also it needs to be unique for multiple tables on the same page

**Comment by awcodes** [comment]
Done. I think that's correct. Let me know if it's not.

**Comment by danharrin** [comment]
Thanks!

**Pull request merged**
