### PR TITLE
Select setting the correct data if canSelectPlaceholder is false

### PR DESCRIPTION
**Pull request by schmeits**
- [X] Changes have been thoroughly tested to not break existing functionality.
Added additional test

If you create a form with a select on it, and you set the canSelectPlaceholder(false) the first item of the select is selected, but the data is still null. This PR fixes the data to reflect the item being shown on your screen. Normally, you would have to set the default value in your Form component fetching the options again and selecting the first key as default value.

### CODE REVIEW

**Comment by danharrin** [comment]
I'm not sure that this is the desired behaviour. I feel like it could result in forms being filled out inaccurately.

Maybe the user doesn't notice that a field isn't filled out, because it has a first option selected. At the moment, an error will occur if they don't manually select an option. With this change, no error will occur, and the form will submit with potentially the wrong information.

I think it's probably the user's responsibility to implement this default value themselves, if they feel like it improves the UX of their own application. But having it there by default is probably a breaking change.

What do you think?

**Comment by danharrin** [comment]
The alternative is to make `canSelectPlaceholder()` simply disable the placeholder option, rather than hide it altogether. That will still force the user to select the option, but the first option in the select is not in the placeholder by default. I'm open to thoughts on that as well.

**Comment by schmeits** [comment]
Hi Dan, 

I get your point from a UX perspective, but It's also the default functionality of an HTML select element. If I create a select in a form without a placeholder item as the first item in the select (same as using the `canSelectPlaceholder(false)`) then the JS value of that select is also the value of the first element.

My use case is that the user must select one of 3 options, for example. Default, I want to select the first item of the select without giving the user the possibility to unselect it. The select is a reactive field triggering another section in the form with a dynamic form portion.

Poh It's a tough one, maybe make it optional some way to set the data value to the first item in the option list?

**Comment by schmeits** [comment]
My current solution is partially duplicating my code 

```
      ->options(fn () => Model::pluck('title', 'id'))
      ->default(fn () => Model::first()->id)

```

**Comment by danharrin** [comment]
However, the current implementation in this PR is also not efficient, it fetches all options just to get the first one. So `Model::all()` twice, once for the default and once for the options. This could be accomplished better if the user writes the `default()` themselves.

I think it's best if we leave this up to the user, I think there are too many unanswered questions, and passing a `default()` is quite easy.

**Pull request closed without merging**
