### PR TITLE
Prevent nested p tags

### PR DESCRIPTION
**Pull request by l3aro**
## Description

Before this PR, the notification body will try to render the content like below.
```
<p
    {{ $attributes->class(['some-classess']) }}
>
    {{ str($body)->sanitizeHtml()->toHtmlString() }}
</p>

```

Yes, it allows body to be rendered in html format. But when using RichEditor or MarkdownEditor, the content will wrap in `<p>` tag like these.
```
<p><strong>Hello</strong <em>World</em></p>
```
or
```
str('*Hello* **world!**')->markdown() 
# will turn into <p><em>Hello</em> <strong>world!</strong></p>
```

We expected the result will be like
```
<p
    {{ $attributes->class(['some-classess']) }}
>
    <p><em>Hello</em> <strong>world!</strong></p>
</p>

```

But since [Nested p tags are not allowed in HTML](https://stackoverflow.com/questions/46853349/can-i-nest-these-tags), we ended up receive this.
```
<p
    {{ $attributes->class(['some-classess']) }}
> </p>
    <p><em>Hello</em> <strong>world!</strong></p>
<p></p>

```

Change the body `<p>` tag into `<div>` will fix the problem, for now.
```
<div
    {{ $attributes->class(['some-classess']) }}
>
    <p><em>Hello</em> <strong>world!</strong></p>
</div>

```

- [x] Visual changes (if any) are shown using screenshots/recordings of before and after.

## Code style

- [x] `composer cs` command has been run.

## Testing

- [x] Changes have been tested.

## Documentation

- [x] Documentation is up-to-date.

### CODE REVIEW

**Comment by zepfietje** [comment]
I've reverted this PR, @l3aro @danharrin.
We've discussed before that when passing Markdown, `inlineMarkdown` should be used instead.
I do understand the difficulty with user-created content though, but I think we should discuss this a little deeper before merging.
For plain text body content, the `<p>` tag should still be used.

**Comment by danharrin** [comment]
@zepfietje I dont think I agree, in this case you could want multi-line content?

**Comment by l3aro** [comment]
@zepfietje let say we are good with `MardownEditor` + `inlineMarkdown()`, but how we resolve this thing when it comes to `RichEditor`?
image
image

**Comment by zepfietje** [comment]
Ideally single line text passed to the `body()` will be wrapped in a `<p>` tag.
Any idea how we could support that, while not wrapping multiline content in a paragraph element, @l3aro @danharrin?

**Comment by zepfietje** [comment]
I've reapplied the change of this PR in https://github.com/filamentphp/filament/commit/e24160a33fd45700b97ba09ea696848a0906651d.
At least it fixes the nested `<p>` tags, but if you can find a way to achieve what I outlined above, please open a new PR. 🙂

**Comment by l3aro** [comment]
> I've reapplied the change of this PR in [e24160a](https://github.com/filamentphp/filament/commit/e24160a33fd45700b97ba09ea696848a0906651d). At least it fixes the nested `<p>` tags, but if you can find a way to achieve what I outlined above, please open a new PR. 🙂

thank you!

**Pull request merged**
