### PR TITLE
Fix for bug introduced in #13074: Shift+Click to select records breaks spa mode

### LINKED ISSUE #13183: Filament breaks in SPA mode on page change in latest version
### Package

filament/filament

### Package Version

v3.2.87

### Laravel Version

v11.10.0

### Livewire Version

v3.5.0

### PHP Version

v8.3.4

### Problem description

In the latest version of Filament, SPA mode no longer works properly. When you change the page, everything disappears and the following error appears in the console:

image

### Expected behavior

No errors when changing pages.

### Steps to reproduce

1. activate SPA mode
2. change the page
3. everything disappears and the error is displayed in the console.

### Reproduction repository

https://github.com/filamentphp/demo

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by neverything**
## Description

- Workaround to get the `wire:id` when `this.$wire.id` is not yet available in `table.js` using `spa()` mode.
- fixes issue with spa() mode
- fixes issue with relationship managers in tabs
- see comments on release https://github.com/filamentphp/filament/discussions/13177#discussioncomment-9728588
- Fix for https://github.com/filamentphp/filament/issues/13183

## Functional changes

- [x] Code style has been fixed by running the `composer cs` command.
- [x] Changes have been tested to not break existing functionality.
   - Additional tests done in `spa()` mode
   - Checked multiple relationship managers in tabs
- [x] Documentation is up-to-date.

### CODE REVIEW

**Comment by danharrin** [comment]
Thank you

**Comment by neverything** [comment]
Thank you @danharrin and sorry for causing an issue and additional work. I hope this fixes it for now.

**Comment by danharrin** [comment]
No worries, thanks for the fix!

**Comment by zepfietje** [comment]
Thanks for the quick fix, @neverything!
(This issue also broke relation manager tabs, but can confirm this PR fixes that too.)

**Pull request merged**
