### PR TITLE
Fixed missing set state path in MorphToSelect

### PR DESCRIPTION
**Pull request by cheesegrits**
MorphToSelect currently blows up because of the missing state path.

### CODE REVIEW

**Comment by cheesegrits** [comment]
Added fix for the morph type $get selector, needs to be 'thingable.thingable_type', not just 'thingable_type'.  Without this fix, second selector will never show on a new record.

**Comment by cheesegrits** [comment]
Aaaand ... data isn't submitting, something messing up in getState ... it's returning the array, like ['reportable']['reportable_type'] and ['reportable']['reportable_id'] rather than shifting the individual items up into the main $data state path.

Working on it.

**Comment by cheesegrits** [comment]
Hmmm.  And, when creating a new record, ONLY the dotted path exists for $get(), when editing a record both paths exist (dotted and not dotted) and when saving, only the non-dotted.  So this is beyond my pay grade, there's something funky going on deep in the guts.

**Comment by danharrin** [comment]
As mentioned on Discord, please explain "blows up if there is no state path"

**Pull request closed without merging**
