### PR TITLE
Add github trending badge to readme file

### PR DESCRIPTION
**Pull request by liweiyi88**
- [X] Changes have been thoroughly tested to not break existing functionality.
- [X] New functionality has been documented or existing documentation has been updated to reflect changes.
- [X] Visual changes are explained in the PR description using a screenshot/recording of before and after.

[trendshift.io](https://trendshift.io/) captures the daily Github Trending data and generates a nice badge based on the highest achieved rank. This PR embeds the badge in the readme file, and hopefully, It helps to motivate contributors and attract users.

### CODE REVIEW

**Comment by zepfietje** [comment]
Thanks for the PR, @liweiyi88!
I'm not sure if we really need this though, also since we've already reached position 2 multiple times.

Will let @danharrin decide.

**Comment by liweiyi88** [comment]
@zepfietje No worries, this badge will be dynamically updated if filament achieved position 1, but feel free to close this PR if you dont think it is necessary 😄

**Comment by danharrin** [comment]
I don't mind it, but the dark mode version is a little hard to read, is there any way to fix that?

**Comment by liweiyi88** [comment]
@danharrin , currently we only provide light mode, once merged it should look like https://github.com/Pythagora-io/gpt-pilot. Or do you want to embed a dark mode which has indigo background with white text? If so I can make a dark mode when I get a chance today.

**Comment by liweiyi88** [comment]
OK, I think you were referring to the GitHub dark mode. I have updated my side, please review. If you still don't see the change, please do a hard browser refresh. and see attached updated version
Screenshot 2023-10-14 at 3 29 49 pm

**Pull request merged**
